### ISSUE TITLE
Adding new Elt instances

### ISSUE THREAD

**Issue by crockeea** [AccelerateHS/accelerate#100]
I'm trying to attempt to implement mod-q arithmetic on the GPU. My type is something like

```
newtype ZqBasic q = ZqBasic (IntTypeOf q)
```

where in practice, IntTypeOf q will be some bounded Integral type (Int, Int8, Int64, etc). I am not aware of any way to make the appropriate instances for this newtype, unless you are recommending the unsafe feature GeneralizedNewtypeDeriving. Similarly for complex numbers (as in the FFT example), it seems very unsafe (not to mention inefficient) for my program to convert between an untyped tuple and a well-typed Complex type, which is used for obvious reasons everywhere outside the Accelerate modules.

Is there some existing way of getting the appropriate instances (I'm still learning, but I think I would need IsScalar, IsBounded, IsNum, and IsIntegral for starters)?  If not, would this be possible to implement either via "deriving" support for these classes or via a wrapper?

Obviously I would be implementing the appropriate Num instances.

**Comment by tmcdonell** [comment]
Following aa2efd542ee6b12427de563b98bb48a805d5a1ff part of the problem here is solved, but there is still some work to do to actually make defining `Elt`/`Lift`/`Unlift`/etc. easier.
