### ISSUE TITLE
Classes like 'IsNum' should be extensible [was: Documentation for adding Elt instances for new types]

### ISSUE THREAD

**Issue by andygill** [AccelerateHS/accelerate#130]
We want a representation for Numeric Bits, so we wrote:

```
newtype Bit = Bit Word8

deriving instance Elt Bit
deriving instance Typeable Bit

type instance EltRepr' Bit = Word8
type instance EltRepr Bit = ((),Word8)
```

We have no idea if this is correct or not.

 * Can we have some documentation of how to add instances for Elt, including newtypes (which should be easier)  [see also #100]
 * An accelerate-th might help here.

**Comment by tmcdonell** [comment]
I think the core of this is fixed now. There is some discussion about possibly handling a packed representation, but let's put that into a separate issue.
