### ISSUE TITLE
nvcc terminated abnormally (double precision calculations)

### ISSUE THREAD

**Issue by wdanilo** [AccelerateHS/accelerate#133]
Hi!
When I'm compiling the example "accelerate-mandelbrot" from package accelerate-examples 0.14 (https://hackage.haskell.org/package/accelerate-examples)
(using all default package cabal settings but without -fllvm flag)
the program starts, but after pressing "d" it crashesh with error 

```
/tmp/accelerate-cuda-32536/dragon32536.cu(18): error: identifier "indexDArray" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00007f25_00000000-6_dragon32536.cpp1.ii".
accelerate-mandelbrot: nvcc terminated abnormally (2)
```

I've noticed that "d" option toggles the `double precision calculations (if supported)` - I understand, that this error indicates, that double precision calculations are not supported by my Quadro FX 880M?
If so - are there any ways to check if something is supported in runtime and disable this option and prevent final user from crashing the entirle application?

**Comment by tmcdonell** [comment]
I still think this would be good to add, but I'm just going to close this anyway because anything which does not support double precision is no longer supported by nvidia anyway.
