### ISSUE TITLE
Preloading large matrixes

### ISSUE THREAD

**Issue by andygill** [AccelerateHS/accelerate#138]
I want a way of pre-loading an array on the GPU, for example as a kernel that returns the matrix. Right now, my vector/matrix bit multiply example is dominated by the loading of a matrix, rather than the multiply itself.

I've looked through the documentation, and can not find anything that might work.

I'm imagining something like `use`, but with an implied `run`.

The array is 384 x 1024 bits.

**Comment by tmcdonell** [comment]
I think this has more or less all been implemented by now.
