### ISSUE TITLE
Please write a bit in the Accelerate language section

### ISSUE THREAD

**Issue by nh2** [AccelerateHS/accelerate#139]
https://github.com/AccelerateHS/accelerate/wiki/The-Accelerate-language

Would be very helpful!

**Comment by tmcdonell** [comment]
I think this is mostly fixed now with the improved haddocks. There is also a short tutorial [here](http://www.acceleratehs.org/examples/mandelbrot.html) (and hopefully I will find time to write a few more).

There is probably more that could be written from a _developer_ perspective, i.e. for people hacking on the compiler, but I guess that is not what you meant.

Feel free to open another issue if this doesn't actually solve what you wanted!
