### ISSUE TITLE
Wrong CUDA backend results (while interpreter ones are good)

### ISSUE THREAD

**Issue by wdanilo** [AccelerateHS/accelerate#141]
Hi!
I've got an example, where I faced a strange problem. I'm reading an BMP image (Word32) and I'm decomposing it to 4 channels (r,g,b and a, each Word8). Then I'm composing it back (to Word32) and the result is different than original image when using CUDA backend and identical when using interpreter.

I want to ask you, If you could look at this example and tell me if it is a bug in Accelerate or there are some not allowed operations in CUDA backend, which are working in Interpreter by accident?

Example: https://github.com/wdanilo/AccelerateHS-tests/tree/master/channels 

It bases on Canny accelerate example (to parse cmd arguments) and there is not much code - all example specific code is placed inside the 'src' directory.
There is also a sample image attached. 
To run the example write: `./dist/build/test/test small.bmp small2.bmp`

The program prints its values to the screen. 
When running on CUDA, we get:
`Image {_channels = fromList [("rgba",Raw Array (Z :. 3 :. 3) [0,0,0,33153,8454273,8487168,0,0,0])]})`
and with interpreter:
`Right (Image {_channels = fromList [("rgba",Raw Array (Z :. 3 :. 3) [4278255615,4294902015,4294967040,4278222976,4286578816,4286611456,4278190335,4278255360,4294901760])]})
` (which is the correct value)

**Comment by tmcdonell** [comment]
I think this was just a bug with the (now dead) `accelerate-cuda` backend; closing.
