### ISSUE TITLE
Monoid array in accelerate

### ISSUE THREAD

**Issue by wdanilo** [AccelerateHS/accelerate#169]
Hello! Is it possible to create a Monoid instance for Accelerate arrays? 
We would love to have a datatype

```
data Image = Map String (Acc (Array ix a))
```

and a function `insertChannels`, which would take list of `(String, Acc (Array ix a))` and insert it to an empty Image, inserting on the beginning `("red", mempty)`, `("green", mempty)` and `("blue", mempty)` (just to ensure, that such channels are available). After inserting some channels, the mempty ones should be just black images if not overriden by arguments of the `insertChannels` function.

Is it possible? We were talking about it on IRC lastly, but without any solution so far.
CC: @zgredzik

**Comment by tmcdonell** [comment]
I think the decision was that this is not possible without fixing the size of the arrays, so closing.
