### ISSUE TITLE
llvm-native: accelerate-nofib wrongly reports errors

### ISSUE THREAD

**Issue by tvh** [AccelerateHS/accelerate#182]
When I run `accelerate-nofib` with `+RTS -N4`, It reports errors where there aren't any.

```
        square: [Failed]
*** Failed! Falsifiable (after 8 tests and 2 shrinks): 
Array (Z :. 1 :. 3) [1,-2,1]
*** Expected:
Array (Z :. 1 :. 3) [1,4,1]
*** Received:
Array (Z :. 1 :. 3) [1,4,1]
```

**Comment by tmcdonell** [comment]
Okay, so `run` itself is not thread-safe (which is annoying, but also why there is `runWith`), and we weren't correctly telling `test-framework` to only run a single test at a time for the LLVM CPU backend. The latter at least is [fixed](https://github.com/AccelerateHS/accelerate-examples/commit/a34c74538e353b6a16c7360f766d98a258ff487e).
