### ISSUE TITLE
llvm: missing FFI

### ISSUE THREAD

**Issue by tvh** [AccelerateHS/accelerate#183]
Both LLVM backend lack a FFI interface at the moment. I wonder what the right design would be here.
In the native case this could really be just an ordinary Haskell function, but I am not sure if that is the desired way. Another option would be a function pointer.

**Comment by tmcdonell** [comment]
Both LLVM backends have an FFI now. See the [accelerate-fft](https://github.com/AccelerateHS/accelerate-fft) package for an example.
