### ISSUE TITLE
llvm-native: unfair scheduling

### ISSUE THREAD

**Issue by tvh** [AccelerateHS/accelerate#189]
When I execute `accelerate-nofib +RTS -N4`, the test often stops at a point before continuing. In the end it catches up and blazes through the following tests. While this happens, the CPU is still active.
I assume this is because it starts running later tests without finishing the earlier tests first.

**Comment by tmcdonell** [comment]
`test-framework` is now correctly configured in `accelerate-examples` to run one test at a time regardless of `+RTS -N` setting.
