### ISSUE TITLE
accelerate-cuda: launch time-out when fusing `fold1` with `replicate`

### ISSUE THREAD

**Issue by amigalemming** [AccelerateHS/accelerate#193]
I got the following code in a complex application:

```
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/CUDA/State.hs:85:9: (unhandled): CUDA Exception: the launch timed out and was terminated
```

I tried extensively to cut it down to a simple test case, but the smaller the test becomes, the less reliably I can reproduce the error. Here is the smallest bit I can provide:
http://code.haskell.org/~thielema/accelerate-utility/bug/contained/ContainedBug.hs
The reduced program does not make anything sensible, its only purpose is to provoke the compile time-out.
You also need this simple helper package:
http://code.haskell.org/~thielema/accelerate-utility/bug/contained/accelerate-utility-0.0.tar.gz
Even if the compilation does not time-out, I think it is pretty long.

**Comment by tmcdonell** [comment]
related: #140
