### ISSUE TITLE
accelerate: Internal error in package accelerate: (determineScopesAcc): unbound shared subtrees

### ISSUE THREAD

**Issue by silver** [AccelerateHS/accelerate#198]
## Steps to reproduce:
1. download zip snapshot of the master branch (hash is b8f358d03d8d7c6ad0281b983229de4c337785e6 in my case)
2. unpack it and `cd` to the target directory
3. create cabal sandbox: `cabal sandbox init`
4. install accelerate dependencies: `cabal install --only-dependencies`
5. create a _test.hs_ with the test code (see contents below)
6. build _test.hs_: `cabal exec ghc -- test.hs` (cabal exec allows ghc to see sandbox)
7. run `test.exe`
#### Result:

Program outputs:

```
test.exe:
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
.\Data\Array\Accelerate\Trafo\Sharing.hs:1627:13: (determineScopesAcc): unbound shared subtrees[AccNodeCount 3 2]
```

Note that if one changes `step` to `step'` program works fine.
#### Test code:

``` haskell
import Data.Array.Accelerate
import Data.Array.Accelerate.Interpreter

type Weight = Int32
type Graph = Array DIM2 Weight

step' :: Acc Graph -> Acc Graph
step' g = generate (shape g) sp
 where
   sp :: Exp DIM2 -> Exp Weight
   sp ix = lift (3 :: Int32)

step :: Acc Graph -> Acc Graph
step g = generate (shape g) sp
 where
   sp :: Exp DIM2 -> Exp Weight
   sp ix = let
             (Z :. i :. j) = unlift ix
           in
             g ! (index2 i j)

main = do
    putStrLn $ show $ run $ step (use (fromList (Z:.3:.3) [1..9]))
```

If you need some additional info or some tests to be performed feel free to ask.
## Machine and software details:
1. Windows 7 64-bit
2. Haskell Platform 2014.2.0.0
3. Cabal

```
cabal-install version 1.18.0.5
using version 1.18.1.3 of the Cabal library
```

and

```
cabal-install version 1.20.0.3
using version 1.20.0.2 of the Cabal library
```

Installed in sandbox for `ncabal exec` command, where `ncabal` is just an alias to sandboxed cabal
4. Installed haskell packages:
https://gist.github.com/silver/dd36144fd086b754b242#file-gistfile1-txt
5. ghc --info
https://gist.github.com/silver/1b8789f9b8f58dbc7f8e#file-ghc-info
6. cygwin bash

```
$ bash --version
GNU bash, version 4.1.11(2)-release (x86_64-unknown-cygwin)
```

If you need more info or any tests to be performed feel free to ask.

**Comment by tmcdonell** [comment]
This seems to have been fixed at some point.
