### ISSUE TITLE
The Accelerate project should have a logo

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#200]

**Comment by tmcdonell** [comment]
Does Futhark use the warm fuzzy thing with speed lines? That is pretty cute @Athas

![Futhark](http://futhark-lang.org/images/gottagofast.png)

**Comment by Athas** [comment]
Sonic is Futhark's spirit animal!

I like fmma's suggestion.  Maybe just add a few more speed lines to make it even more distinct from the Haskell logo?

**Comment by anmolsahoo25** [comment]
My first post on Github, so please excuse any inappropriate behaviour. 

Came up with a few designs based on what people were thinking regarding speed lines and stuff. 

I have attached the files below and added my own twist. The parallel stripes to me represent abstract parallel tasks with the Haskell Lambda representing - using Haskell to solve them. 

Open to suggestions. Please feel free to shoot them down. I'm not much of a designer. 
![h1](https://user-images.githubusercontent.com/7543539/35161257-a2bab6ae-fd65-11e7-9b8f-b1ccb8c8efa6.png)
![h2](https://user-images.githubusercontent.com/7543539/35161258-a2f2a69a-fd65-11e7-9dab-52ffb6bb0bf2.png)
![h3](https://user-images.githubusercontent.com/7543539/35161259-a3305990-fd65-11e7-879f-975dab91cf75.png)

Everything is work in progress. So I can change them according to what people feel would be a better design.

**Comment by tmcdonell** [comment]
Hi @anmolsahoo25, welcome! Thanks for the suggestions, they are pretty cool (:

**Comment by tmcdonell** [comment]
For other ideas, the [alacritty](https://github.com/jwilm/alacritty) project has a pretty cool icon.

**Comment by anmolsahoo25** [comment]
Hi @tmcdonell, thanks for the warm welcome. 

Did you mean this one? 
![29689079-c428d0fe-88d6-11e7-96ef-32eeef13ea55](https://user-images.githubusercontent.com/7543539/35180526-36afef6a-fdd8-11e7-8ad5-d343b7180229.png)

Also posting the link here, in case anyone wants to have a look. 
https://github.com/jwilm/alacritty/issues/285

**Comment by tmcdonell** [comment]
I took an alternate route when I realised that the logo/mascot doesn't actually have to have anything to do with the language itself.

https://github.com/AccelerateHS/accelerate-logo

![](https://github.com/AccelerateHS/accelerate-logo/raw/master/accelerate-logo.png)
