### ISSUE TITLE
Add NFData instance for Array

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#208]
Originally suggested on the mailing list.
The current benchmarks just use `seq`, which seems to work fine.

**Comment by robstewart57** [comment]
More on this.. the mailing list thread in question is https://groups.google.com/forum/#!topic/accelerate-haskell/9S7nm-JiX90 .

Why is `seq` deemed an adequate benchmark tool, as opposed to using `deepseq` to traverse the entire array data structure evaluating it completely? What components of an accelerate array not evaluated with `seq`, and is this saving a fair reflection on accelerate performance?

**Comment by tmcdonell** [comment]
All array elements are stored unboxed, so demanding one is equivalent to evaluating the entire thing. There will be nothing left unevaluated after `seq`. Still, having an `NFData` instance is reasonable even if it doesn't really do any work (because peace of mind is always valuable).

Accelerate [computation] performance has no relation at all to `seq`, since Accelerate [the language] is strict. In this case, the use of `seq` is to ensure that the lazy [non-strict] Haskell language kicks off the computation to begin with, and that you aren't instead benchmarking thunk creation performance.
