### ISSUE TITLE
Type representation improvements

### ISSUE THREAD

**Issue by robeverest** [AccelerateHS/accelerate#210]
Our current method of representing the types that Accelerate supports is lacking. Our typeclasses `Arrays`, `Elt` and `IsTuple` don't necessarily capture everything we might want to do. I'll show this by highlighting a couple of problems.
#### User-defined types

Supposing the user has this type

``` haskell
data Box a = Box a a
```

In order to use it with Accelerate the user has to then create instances for both `Elt` and `IsTuple` as well as type family instances for `EltRepr` and `EltRepr'`. 

``` haskell
type instance ArrRepr (Box a) = ArrRepr (a,a)
type instance ArrRepr' (Box a) = ArrRepr' (a,a)

instance Elt a => Elt (Box a) where
  eltType (_::Box a)
    = eltType (undefined :: (a,a))
  fromElt (Box a b)  = (fromElt a, fromElt' b)
  toElt (Box a b)  = (toElt a, toElt' b)

  eltType' (_::Box a)
    = eltType' (undefined :: (a,a))
  fromElt' (Box a b)  = (fromElt a, fromElt' b)
  toElt' (Box a b)  = (toElt a, toElt' b)

instance IsTuple (Box a) where
  type TupleRepr (Box a) = TupleRepr (a,a)
  fromTuple (Box a a) = fromTuple (a,a)
  toTuple (((),a),a) = Box a a
```

While this works, there is a lot of repetition just to say something is equivalent to a tuple. Ideally, this should be relatively easy for a user to do.
### Transforms at the type level

The perhaps more serious drawback of our current method is that it doesn't work for type level transforms. For example, in the vectoriser I have a transform of the form

``` haskell
liftAcc :: Acc a -> Acc (Vector' a) 
```

`Vector'` here represents a vector of arrays or tuples of arrays. A simple definition would be something like this.

``` haskell
newtype Vector' a = Vector' (ArrRepr' (Vector' a))

type instance ArrRepr (Vector' a) = LiftedRepr (ArrRepr a)
type instance ArrRepr' (Vector' a) = LiftedRepr (ArrRepr' a)

type family LiftedRepr a where
  LiftedRepr () = ((), Scalar Int)
  LiftedRepr (Array sh e) = (((),Segments sh), Vector e)
  LiftedRepr (b, a) = (LiftedRepr b, LiftedRepr a)
```

We have to do the lifting over the representation type. Why? The whole idea is that the set of valid surface types is extendable, so we can't match on them. 

While it's easy enough to make an `Arrays` instance for `Vector'` defined in this way, it's impossible to construct a valid `IsTuple` instance that retains the structure of the original `a`. By that I mean one that allows us to have the necessary function.

``` haskell
liftTupIdx :: TupleIdx (TupleRepr t) a -> TupleIdx (TupleRepr (Vector' t)) (Vector' a)
```

It is possible to change the definition of `Vector'` to allow for an `IsTuple` instance that does permit this function, but it does not then allow an instance of `Arrays`. We can have one OR the other.

Another way of looking at this problem is that each type accelerate supports has two different representations. One is the `TupleRepr` which flattens the type at the top level only. The other is `ArrRepr` or `EltRepr` that flattens the type all the way down. However, we don't capture the relationship between the two representations. 

I was able to solve this problem in the streaming fork (see #150) by generalising `IsTuple` to `IsProduct` and adding a method `prod` that reified the structure of products. I also had to add a method `flavour` to `Arrays` that captured, at least in part, the relationship between the `IsProduct` and `Arrays`.

``` haskell
data ArraysFlavour arrs where
  ArraysFunit  ::                                            ArraysFlavour ()
  ArraysFarray :: (Shape sh, Elt e)                       => ArraysFlavour (Array sh e)
  ArraysFtuple :: (IsAtuple arrs, ArrRepr' arrs ~ (l,r))  => ArraysFlavour arrs

class Arrays a where
...
flavour  :: a {- dummy -} -> ArraysFlavour a
...
```

While this works, it makes our method of type representation even more complex. In practice I found it also involves a lot of traversing structures just to generate witnesses for constraints. 
### Solutions

One way of solving this would be to define `ArrRepr` and `EltRepr` in terms of `TupleRepr` (or `ProdRepr` as it is now known) like so.

``` haskell
type family ArrRepr a where
  ArrRepr a = ArrProdRepr (ProdRepr a)

type family ArrProdRepr a where
  ArrProdRepr () = ()
  ArrProdRepr (Array sh e) = Array sh e
  ArrProdRepr (a,b) = (ArrTupleRepr a, ArrTupleRepr b)
```

This assumes that we have an instance of `IsProduct` for a single array, but that can be done, and I don't think is unreasonable. 

I haven't tried, but I believe it should be possible using this method to remove the need for users to create their own instances of `Arrays` or `Elt`. Or at the very least, they can create an instances like so.

``` haskell
instance IsProduct Elt (Box a) where
  ... --All the IsProduct stuff

instance Elt a => Elt (Box a)
  -- No need to define any of the methods as they are all taken care of by default signatures
```

Another solution would be to leverage one of the existing generics library. It seems like the problems we are trying to solve here with representation types are very much in the domain of generic programming. It would be especially nice if we could use GHC.Generics. If that were the case, a user could do most of what was necessary by just deriving Generic on their types. The disadvantage of this approach is it could possibly be slow, as the generic programming libraries often are.  

Whatever solution we come up with, I think it would also be a nice idea to use type level lists instead of left-nested tuples. If nothing else, it's easier on the eyes.

**Comment by tmcdonell** [comment]
Here is an approach that I took that redefines `EltRepr` in terms of `TupleRepr` directly: tmcdonell/Accelerate@91db9492128fbf1dddf42fc7bc8aa08162c6ddab; and for `ArrRepr` tmcdonell/Accelerate@b728e683c8cfd2c3ff906841d926756c4d942bab.

This change was enough (but necessary) to allow me to make progress with the typed llvm work, where I also needed to know the relationship between `EltRepr` and `ProdRepr`. I also took the opportunity to flatten the representation to a single type, since `EltRepr'` is really only used at the leaves, and that isn't necessary anymore.

@robeverest Would this change also help with your work?

**Comment by tmcdonell** [comment]
@mchakravarty Any comments about removing the `EltRepr` / `EltRepr'` distinction?

**Comment by mchakravarty** [comment]
@tmcdonell I never liked the distinction, so I'm glad for it to go. In fact, I started essentially with what you are proposing. I did run into problems with it as I needed to distinguish between leaves and inner nodes in some class or type family instances. If that isn't necessary anymore, I'm all for making it simpler. :+1:

**Comment by robeverest** [comment]
@tmcdonell This doesn't entirely fix my problems. I still can't construct an instance like this,

```haskell
instance Arrays a => Arrays (Vector' a) where
  ...
```

but this does simplify matters. I can still use the hack I was using before where I traverse the structure returned by `arrays` in order to generate a proof for a given instance. That should do for now. I'll look for a better solution when I get the chance.

**Comment by tmcdonell** [comment]
Ah, one problem with the `EltRepr` change is that `to/fromIArary` no longer work.

**Comment by yongqli** [comment]
Hi, I'm trying to port `linear-accelerate` to the latest version of accelerate.

Do these instances look right? They do compile.

    instance (cst a) => IsProduct cst (V0 a) where
      type ProdRepr (V0 a)  = ()
      fromProd _ V0         = ()
      toProd _ ()           = V0
      prod _ _              = ProdRunit

    instance (cst a) => IsProduct cst (V1 a) where
      type ProdRepr (V1 a)  = ((), a)
      fromProd _ (V1 x)     = ((), x)
      toProd _ ((), x)      = V1 x
      prod _ _              = ProdRsnoc ProdRunit

    instance (cst a) => IsProduct cst (V2 a) where
      type ProdRepr (V2 a)  = ProdRepr (a,a)
      fromProd p (V2 x y)   = fromProd p (x,y)
      toProd p t            = case toProd p t of
                                (x, y) -> V2 x y
      prod _ _              = ProdRsnoc $ ProdRsnoc ProdRunit

    instance (cst a) => IsProduct cst (V3 a) where
      type ProdRepr (V3 a)  = ProdRepr (a,a,a)
      fromProd p (V3 x y z) = fromProd p (x,y,z)
      toProd p t            = case toProd p t of
                                (x, y, z) -> V3 x y z
      prod p _              = ProdRsnoc (prod p (undefined :: (a, a)))

    instance (cst a) => IsProduct cst (V4 a) where
      type ProdRepr (V4 a)  = ProdRepr (a,a,a,a)
      fromProd p (V4 x y z w) = fromProd p (x,y,z,w)
      toProd p t            = case toProd p t of
                                (x, y, z, w) -> V4 x y z w
      prod p _              = ProdRsnoc (prod p (undefined :: (a,a,a)))

    instance (cst a) => IsProduct cst (Quaternion a) where
      type ProdRepr (Quaternion a) = ProdRepr (a,a,a,a)
      fromProd p (Quaternion x (V3 y z w)) =
        fromProd p (x,y,z,w)
      toProd p t =
        case toProd p t of
          (x, y, z, w) -> Quaternion x (V3 y z w)
      prod p _  =
        ProdRsnoc (prod p (undefined :: (a,a,a)))

**Comment by robeverest** [comment]
@yongqli Those instances look correct to me.

**Comment by tmcdonell** [comment]
@yongqli I've pushed the changes I mentioned earlier into master now. It doesn't change the Product representations, so you might not have to do anything.

**Comment by tmcdonell** [comment]
I'm just going to tack this on here, although it could be a different ticket.

How about we convert all the representation types to closed type families? At the moment there is the tacit agreement that these will only consist of `()`, `(,)`, and primitive types, but since we have closed families now we could actually encode that.

**Comment by mchakravarty** [comment]
> How about we convert all the representation types to closed type families?

I always thought it would be better to use closed type families as soon as we can drop support for all versions of GHC that pre-date the introduction of closed families.

**Comment by robeverest** [comment]
I was thinking closed type families would probably be the way to go when I first raised this.

@tmcdonell Were you thinking something along the lines of the solution I have above, or something else?

I'm actually using closed families in the vectoriser, but in  a way that could easily be changed to use open families. What do we now consider the minimum version go GHC we support?

**Comment by tmcdonell** [comment]
We still allow ghc-7.6, but I just checked and the Haskell Platform now ships with 7.8.3, so it is not unreasonable to upgrade to that. (Closed families were introduced in 7.8).

@robeverest I'll have to check if that works with the LLVM backend, but whatever we choose should solve all the problems (:

**Comment by mchakravarty** [comment]
I agree 6.8 is totally reasonable.

**Comment by tmcdonell** [comment]
FYI, Accelerate silently stopped supporting 7.6 a while ago, due to (at least) use of `AllowAmbigiousTypes` and `Data.Proxy`. The `cuda` bindings package also accidentally dropped 7.6 support due to use of `EmptyCase`, although that is now fixed.

Accelerate is currently building with 7.8 and 7.10, but not HEAD.
https://travis-ci.org/tmcdonell/accelerate

**Comment by tmcdonell** [comment]
I think this can be closed; at lot of these problems seem to be fixed/avoided now...
