### ISSUE TITLE
unsafe versions of toByteString and formByteString

### ISSUE THREAD

**Issue by zgredzik** [AccelerateHS/accelerate#211]
Would it be possible to add `unsafeToByteString` and `unsafeFromByteString` to the accelerate-io package?
E.g. by using the functionalities from [Data.Vector.Storable.ByteString](http://hackage.haskell.org/package/spool-0.1/docs/src/Data-Vector-Storable-ByteString.html).

**Comment by tmcdonell** [comment]
Adding a note after playing with this for a little while: the ByteString structure has an offset field from the pointer base address. This is currently ignored by Data.Array or Accelerate (I am not sure which, although Data.Array appears to have this as well?) so we can't do a constant-time `ByteString` to Accelerate conversion if this is non-zero.

**Comment by tmcdonell** [comment]
At some point I implemented this in `accelerate-io`; closing. Thanks again for the idea!
