### ISSUE TITLE
>-> optimization guide

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#222]
It is my understanding that `x >-> y` prevents `x` and `y` from being fused into a single kernel, and thus prevents problems from arising caused by an overly large kernel. In my application I've found that I was able to get some performance boost by linking two steps with `Prelude..` and then linking those two units with `>->`. It would be nice for accelerate to either automatically figure out the optimal degree of combination or provide guidance to the user of the library.

Thanks for the great work on accelerate, by the way, it is amazing :).

**Comment by amigalemming** [comment]
I also discussed the issue in google groups:
https://groups.google.com/forum/#!topic/accelerate-haskell/cXeiq0JUJs4

**Comment by tmcdonell** [comment]
I added some examples to the documentation covering `(>->)`, so closing for now.
