### ISSUE TITLE
Passing multiple arguments to a GPU program

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#223]
I'm interested in passing multiple arguments to a GPU program. Passing in a single big vector and then using `slit` and `reshape` seems to be slow. Is there a better way?

**Comment by amigalemming** [comment]
My utility package performs tupling and untupling of parameters and results for you:
https://hackage.haskell.org/package/accelerate-utility-0.1/docs/Data-Array-Accelerate-Utility-Lift-Run.html
