### ISSUE TITLE
"CUDA Exception: invalid device context"

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#236]
On a Ubuntu computer with two GPUs, I get the error "CUDA Exception: invalid device context". The program works fine on OSX. Is this due to not specifying a GPU?

**Comment by tmcdonell** [comment]
No, it will just pick the "best" GPU available. I've not had this problem on our Ubuntu box with multiple GPUs.

Is this compiled or running in ghci?

**Comment by yongqli** [comment]
Ok, it looks like maybe the "Tesla K40m" isn't turned on by default? Running nvidia-smi seems to have fixed the problem.
