### ISSUE TITLE
c2hs error when trying to install the examples

### ISSUE THREAD

**Issue by viclib** [AccelerateHS/accelerate#237]
I get the following error when running `cabal install` on accelerate-examples:

    vh:accelerate-examples-0.15.0.0 apple1$ cabal install
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /Users/apple1/Viclib/Haskell/accelerate-examples-0.15.0.0/.cabal-sandbox
    Configuring accelerate-cuda-0.15.0.0...
    Configuring cufft-0.1.1.0...
    Building accelerate-cuda-0.15.0.0...
    Failed to install accelerate-cuda-0.15.0.0
    Build log ( /Users/apple1/Viclib/Haskell/accelerate-examples-0.15.0.0/.cabal-sandbox/logs/accelerate-cuda-0.15.0.0.log ):
    Configuring accelerate-cuda-0.15.0.0...
    Building accelerate-cuda-0.15.0.0...
    Preprocessing library accelerate-cuda-0.15.0.0...
    [ 1 of 33] Compiling Data.Array.Accelerate.CUDA.Execute.Event ( Data/Array/Accelerate/CUDA/Execute/Event.hs, dist/dist-sandbox-8e37b8e0/build/Data/Array/Accelerate/CUDA/Execute/Event.o )
    [ 2 of 33] Compiling Paths_accelerate_cuda ( dist/dist-sandbox-8e37b8e0/build/autogen/Paths_accelerate_cuda.hs, dist/dist-sandbox-8e37b8e0/build/Paths_accelerate_cuda.o )
    [ 3 of 33] Compiling Data.Array.Accelerate.CUDA.CodeGen.Type ( Data/Array/Accelerate/CUDA/CodeGen/Type.hs, dist/dist-sandbox-8e37b8e0/build/Data/Array/Accelerate/CUDA/CodeGen/Type.o )
    Loading package ghc-prim ... linking ... done.
    Loading package integer-gmp ... linking ... done.
    Loading package base ... <command line>: can't load .so/.DLL for: libiconv.dylib (dlopen(libiconv.dylib, 9): image not found)
    Building cufft-0.1.1.0...
    Failed to install cufft-0.1.1.0
    Build log ( /Users/apple1/Viclib/Haskell/accelerate-examples-0.15.0.0/.cabal-sandbox/logs/cufft-0.1.1.0.log ):
    [1 of 1] Compiling Main             ( /var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/cufft-0.1.1.0-84822/cufft-0.1.1.0/dist/dist-sandbox-8e37b8e0/setup/setup.hs, /var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/cufft-0.1.1.0-84822/cufft-0.1.1.0/dist/dist-sandbox-8e37b8e0/setup/Main.o )
    Linking /var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/cufft-0.1.1.0-84822/cufft-0.1.1.0/dist/dist-sandbox-8e37b8e0/setup/setup ...
    Configuring cufft-0.1.1.0...
    checking for gcc... /usr/bin/gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether /usr/bin/gcc accepts -g... yes
    checking for /usr/bin/gcc option to accept ISO C89... none needed
    checking build system type... x86_64-apple-darwin14.0.0
    checking host system type... x86_64-apple-darwin14.0.0
    checking target system type... x86_64-apple-darwin14.0.0
    checking for nvcc... /usr/local/cuda/bin/nvcc
    checking ghc architecture... <command line>: can't load .so/.DLL for: libiconv.dylib (dlopen(libiconv.dylib, 9): image not found)

    checking for Apple Blocks extension... yes
    checking how to run the C preprocessor... /usr/bin/gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking cufft.h usability... yes
    checking cufft.h presence... yes
    checking for cufft.h... yes
    checking for library containing cufftPlan1d... -lcufft
    configure: creating ./config.status
    config.status: creating cufft.buildinfo
    Building cufft-0.1.1.0...
    Preprocessing library cufft-0.1.1.0...
    c2hs: C header contains errors:

    /usr/include/stdlib.h:177: (column 46) [ERROR]  >>> Syntax error !
    The symbol `__OSX_AVAILABLE_BUT_DEPRECATED_MSG' does not fit here.

    cabal: Error: some packages failed to install:
    accelerate-cuda-0.15.0.0 failed during the building phase. The exception was:
    ExitFailure 1
    accelerate-examples-0.15.0.0 depends on cufft-0.1.1.0 which failed to install.
    accelerate-fft-0.15.0.0 depends on cufft-0.1.1.0 which failed to install.
    cufft-0.1.1.0 failed during the building phase. The exception was:
    ExitFailure 1
    gloss-accelerate-1.8.15.0 depends on accelerate-cuda-0.15.0.0 which failed to
    install.
    gloss-raster-accelerate-1.8.15.0 depends on accelerate-cuda-0.15.0.0 which
    failed to install.

What could be the cause?

**Comment by robeverest** [comment]
This is because the version of cufft on hackage doesn't work on OSX Yosemite. I've just uploaded a new version of it to hackage which should fix the problem. Run `cabal update` and try again.

**Comment by viclib** [comment]
Wow. Thank you very much!
