### ISSUE TITLE
Examples compile fine, but there is no option to run using CUDA.

### ISSUE THREAD

**Issue by viclib** [AccelerateHS/accelerate#239]
I've installed CUDA on my OSX Yosemite. I've downloaded the accelerate-examples package and compiled it with `cabal install`. It compiled correctly. When I ran the examples, though, I noticed they do not offer a option to run under CUDA. For example:

    vh:accelerate-crystal apple1$ ./accelerate-crystal
    EKG monitor started at: http://localhost:8000
    
    accelerate-crystal (c) [2011..2013] The Accelerate Team
    
    Usage: accelerate-crystal [OPTIONS]
    
    Available backends:
      *  interpreter  reference implementation (sequential)

This makes them run slow (and, obviously, beat the purpose). How do I enable CUDA on the compiled examples?

**Comment by tmcdonell** [comment]
The first thing would be to check that accelerate-cuda did install correctly and is available (e.g. by importing `Data.Array.Accelerate.CUDA` in ghci).

If that works, try installing the examples again with `cabal install accelerate-examples -fcuda`

**Comment by viclib** [comment]
Thank you very much. Seems like it didn't, regardless of me remembering it did. My bad (but it did, I swear). When installing again, I got this: http://lpaste.net/118683

So I tried just `cabal install cuda` and I got this:

    vh:accelerate-examples-0.15.0.0 apple1$ cabal install cuda
    Resolving dependencies...
    Notice: installing into a sandbox located at
    /Users/apple1/Viclib/haskell/accelerate-examples-0.15.0.0/.cabal-sandbox
    Configuring cuda-0.6.5.1...
    Failed to install cuda-0.6.5.1
    Build log ( /Users/apple1/Viclib/haskell/accelerate-examples-0.15.0.0/.cabal-sandbox/logs/cuda-0.6.5.1.log ):
    [1 of 1] Compiling Main             ( /var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/cuda-0.6.5.1-99649/cuda-0.6.5.1/dist/dist-sandbox-11691035/setup/setup.hs, /var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/cuda-0.6.5.1-99649/cuda-0.6.5.1/dist/dist-sandbox-11691035/setup/Main.o )
    Linking /var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/cuda-0.6.5.1-99649/cuda-0.6.5.1/dist/dist-sandbox-11691035/setup/setup ...
    Configuring cuda-0.6.5.1...
    checking for gcc... /usr/bin/gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/fl/5630t6sd4lgctzq57lvq782c0000gn/T/cuda-0.6.5.1-99649/cuda-0.6.5.1':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    cabal: Error: some packages failed to install:
    cuda-0.6.5.1 failed during the configure step. The exception was:
    ExitFailure 77

I couldn't find any `config.log` on the accelerate-examples dir and on the `~/.cabal` dir. I find it very weird, I really swear I managed to install both successfully yesterday. Maybe I was in a sandbox or something. My bad. I will be investigating the issue on the next hours, but if you have an insight, please tell me! Thank you.

**Comment by tmcdonell** [comment]
You should be able to get the `config.log` thusly:

```
cabal get cuda
cd cuda
cabal configure
```

I'm not sure how useful that will be though...

It looks like your installation of `gcc` and/or `nvcc` is broken somehow, maybe after a system upgrade? Do those still work independently?

**Comment by tmcdonell** [comment]
New releases of the cuda and accelerate packages are out. If you still have problems, please re-open the ticket (or create a new one if you get a significantly different error). Thanks!
