### ISSUE TITLE
Missing field in record construction Data.Array.Accelerate.Trafo.vectoriseSequences

### ISSUE THREAD

**Issue by pmlodawski** [AccelerateHS/accelerate#241]
Hi! I'm getting runtime error when using accelerate-cuda from master:

    Main: Data/Array/Accelerate/CUDA.hs:(404,11)-(411,3): Missing field in record construction Data.Array.Accelerate.Trafo.vectoriseSequences

sample code which causes error:

    module Main where

    import Data.Array.Accelerate as A
    import Data.Array.Accelerate.CUDA as C

    main :: IO ()
    main = print $ C.run $ A.use (fromList (Z:.1) [1..10] :: Vector Double)

**Comment by tmcdonell** [comment]
Sorry about that. Thanks for the report.

**Comment by pmlodawski** [comment]
Thanks for fixing it so fast! :)
