### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#242]
@fmma Why is there `build1` and `build1Simple`? That's just... 

https://github.com/AccelerateHS/accelerate-cuda/blob/master/Data/Array/Accelerate/CUDA/Compile.hs#L452

**Comment by tmcdonell** [comment]
@robeverest FYI.

We can't let the code base get out of hand with crap like this. There are other examples I've seen that should be cleaned up.

**Comment by robeverest** [comment]
@tmcdonell Yeah, you're right. I'm doing a bit of a clean up now, starting with this. Let me know if there is anything else in particular you think needs fixing.

**Comment by tmcdonell** [comment]
I noticed the other day that the ray trace program spends a long time in the front-end, ~5 seconds. I can't remember if that always happened, is a regression in master, something I introduced (discovered while doing llvm hacking) or otherwise, but we should investigate.

I'll spend some time after ICFP looking for other stuff.
