### ISSUE TITLE
-f-cuda not working

### ISSUE THREAD

**Issue by rzil** [AccelerateHS/accelerate#243]
I'm trying to install accelerate-examples on my MacBook Pro using this
`cabal install -f-cuda accelerate-examples`

For some reason, however, it is still trying to install the cuda package which doesn't work because my graphics card doesn't support CUDA.

**Comment by tmcdonell** [comment]
hm, can you `cabal install -f-cuda accelerate-examples --dry-run` and show the list. I am guessing that cabal isn't applying the `-f-cuda` bit to all packages, and something else is still trying to pull it in still; maybe `accelerate-fft` or `gloss-[raster-]accelerate`.

**Comment by rzil** [comment]
cabal install -f-cuda accelerate-examples --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
cuda-0.6.5.1
accelerate-cuda-0.15.0.0
cufft-0.1.1.0 (latest: 0.1.2.0)
accelerate-fft-0.15.0.0
gloss-accelerate-1.8.15.0
gloss-raster-accelerate-1.8.15.0
accelerate-examples-0.15.0.0

**Comment by tmcdonell** [comment]
Try the following?

```
cabal install accelerate-fft -f-cuda
cabal install gloss-accelerate -f-cuda
cabal install gloss-raster-accelerate -f-cuda
```

**Comment by rzil** [comment]
Of course. So I have now installed accelerate-examples on my MacBook Pro. Unfortunately the example programs aren't working. The graphical programs fail to launch. Also see the output below of accelerate-nofib

  prefix sum:
    Int32:
      scanl: [OK, passed 100 tests]
      scanl': [OK, passed 100 tests]
      scanl1: [OK, passed 100 tests]
      scanr: [OK, passed 100 tests]
      scanr': [OK, passed 100 tests]
      scanr1: [OK, passed 100 tests]
      scanl1Seg: [OK, passed 100 tests]
      scanr1Seg: [OK, passed 100 tests]
      scanlSeg: [Failed]
accelerate-nofib: ./Data/Array/Accelerate/Array/Representation.hs:131:24: (iter1): empty iteration space

Help?

Ruben

**Comment by rzil** [comment]
That worked as far as installing it is concerned. I also had to `brew install llvm` and create some symlinks but yeah, it installed. Only problem is that the example programs don't work!

**Comment by tmcdonell** [comment]
If you're running under the interpreter, I am guessing that the example programs do actually work, but they just take longer to compute than you were willing to wait (;

```
accelerate-crystal --benchmark
```

May be informative...

The interpreter is only meant to be a reference implementation for the semantics of the language, it is not designed for speed. For that, you'll either need to install the CUDA backend (which doesn't work on your machine) or one of the (incomplete) CPU backends.

**Comment by rzil** [comment]
Oh I see. I was hoping to use OpenCL but now I can see that it is not available for some reason.

**Comment by tmcdonell** [comment]
Yes, the OpenCL backend has languished. If you know OpenCL, then we could use your expertise... (;

Moving forward, we could support AMD GPUs via the LLVM backend.

**Comment by mchakravarty** [comment]
> Moving forward, we could support AMD GPUs via the LLVM backend.

Makes the most sense to me, especially give SPIR-V: https://www.khronos.org/vulkan

**Comment by rzil** [comment]
I checked out the source for accelerate-opencl and I am updating it. I’m stuck at the following error. What happened to these objects Let2 and PairArrays?

Data/Array/Accelerate/OpenCL/CodeGen.hs:91:9:
    Not in scope: data constructor ‘Let2’
    Perhaps you meant ‘Let’ (imported from Data.Array.Accelerate.AST)

Data/Array/Accelerate/OpenCL/CodeGen.hs:95:9:
    Not in scope: data constructor ‘PairArrays’

Ruben

**Comment by tmcdonell** [comment]
Ah, that was replaced by `Atuple` and `Aprj` quite a while ago...  (AccelerateHS/accelerate@298a3f2b20cd669c16ceeee5f50dd186e62a9622)
So getting that backend up to speed could take some effort.
