### ISSUE TITLE
Remove support for loading arrays through the texture cache

### ISSUE THREAD

**Issue by robeverest** [AccelerateHS/accelerate#244]
While implementing an LRU based memory manager I ended up briefly breaking support for loading arrays through the texture cache. It wasn't hard to fix, but it made me think it's really not something we need to do any more. It's just another part of Accelerate that can be broken by future changes.

In CUDA 6.5 support for compute 1.x capable devices was deprecated. If Nvidia isn't willing to support these devices any more, I'm not sure there is a lot of point in us doing it.

I guess the only argument against it is there are still a lot of compute 1.x devices being used. It should be noted, however, that they will still work, just without that particular optimisation.

@tmcdonell What do you think?

**Comment by tmcdonell** [comment]
Well, performance on them is going to be terrible... which will be unfortunate if your main test machine is still tesla? On the other hand, NVIDIA support was kinda poor for texture arrays, e.g. #58.

LLVM can't support 1.x devices, so if we want to transition to the grand-unified-LLVM architecture in the future, leaving this behind to support old devices might be good.

I think a couple of the flowbox guys are using 1.x cards in their development machines (old mac laptops probably).

**Comment by robeverest** [comment]
I am still using tesla, but I've been meaning to move over to kepler anyway. 

If our plan is still to make an accelerate 1.0 release in the near future. Perhaps we should leave texture cache support in for that, but take it out for 2.0?

**Comment by tmcdonell** [comment]
That's a good plan. Let's keep it in for the 1.0 release at least. Then, let's mark it as deprecated and remove it if it becomes a problem.

**Comment by mchakravarty** [comment]
> If our plan is still to make an accelerate 1.0 release in the near future. Perhaps we should leave texture cache support in for that, but take it out for 2.0?

I like that plan, too.

**Comment by tmcdonell** [comment]
completed via deprecating `accelerate-cuda` entirely.
