### ISSUE TITLE
Can't build again.

### ISSUE THREAD

**Issue by pioole** [AccelerateHS/accelerate#245]
Hello,
I'm working with @zgredzik on a task, which he metioned here:
https://github.com/AccelerateHS/accelerate-llvm/issues/4

I'm trying to build accelerate-llvm using this script:

https://gist.github.com/pioole/d5e46624be54f9fe2baa

but, I'm constantly getting this error:

```Data/Array/Accelerate/LLVM/CodeGen/IR.hs:127:23:
Couldn't match type ‘((), CUChar)’ with ‘CUChar’
Expected type: a
Actual type: EltRepr a
In the expression: pack
In an equation for ‘ir’: ir (TypeCUChar _) = pack
In the instance declaration for ‘IROP NonNumType’
```

(full log: https://gist.github.com/pioole/2f516a1e888041fecdd2)

**Comment by tmcdonell** [comment]
Ah, I have "dev/llvm" branches for a few of the Accelerate packages, wherever I needed to change something, but I'm going to merge this in to main in the next couple of days.

**Comment by tmcdonell** [comment]
This has been merged into master now.
