### ISSUE TITLE
Z :. Int :. sh -> Z :. Int :. Int :. sh

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#246]
I want to replicate a array of `Z :. numRows :. numCols` to be, say, `Z :. stepId :. numRows :. numCols`. It does not seem that there is an easy way to do this generically, for any shape. Is this correct? Is there even a way to encode `Z :. Int :. Int :. sh` in the type system? It's not clear what type `sh` would have.

**Comment by tmcdonell** [comment]
The first is a standard replicate, if I interpret what you are asking correctly:

```
stepID :: Int
stepID = 10

rep = A.replicate (constant (Z :. stepID :. All :. All)) xs
```

As for the second question, no I don't think you'll be able to do that.
