### ISSUE TITLE
Negatives in shapes

### ISSUE THREAD

**Issue by projanen** [AccelerateHS/accelerate#248]
These are instantiable arrays in Accelerate:

```
Array (Z :. 3 :. -3 :. 5) []
Array (Z :. 2 :. -2 :. -2) [1,2,3,4,5,6,7,8]
```

**Comment by projanen** [comment]
This would be a good time to reconsider how zeroes are allowed in shapes too.  And to see if enough testing is in place to ensure they're handled properly if allowed to be used.

**Comment by tmcdonell** [comment]
There are some runtime checks to catch this sort of thing, so I guess this fixed enough to close for now. Thanks again for the report!
