### ISSUE TITLE
unlift several times

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#249]
I would like to `unlift` a `Exp ((Int, Int), (Int, Int))` into a `((Exp Int, Exp Int), (Exp Int, Exp Int))` "automatically", with a single `unlift`. Would it possible to write instances that allows this? 

With a single `unlift`, we get to `(Exp (Int, Int), Exp (Int, Int))`. We need to do more `unlift`s to get this to be `((Exp Int, Exp Int), (Exp Int, Exp Int))`. I would prefer `unlift` to be smart enough to "look inside" and keep trying.

**Comment by yongqli** [comment]
Ok, I've got an implementation of this working. 

Basically, the problem is that we might already have a function `f :: Num a => (V3 (V3 a), a) -> a`. If we have an `Array Vector (V3 (V3 Double), Double)`, it's very tedious to keep `unlift`ing to get to `(V3 (V3 (Exp Double)), Exp Double)`. Just as `Plain` will strip all surface constructors `c` from a type, wherever they may be, I want something that will "push" the `Exp` as deep as possible. I've called this type `Lowest`, which probably isn't the best name.

To make this work, I needed to define more instances for `Unlift`. Here is the implementation:

    module Data.Array.Accelerate.Lower where

    import Linear
    import Linear.Accelerate
    import Data.Array.Accelerate
    import Data.Array.Accelerate.Smart
    import Data.Array.Accelerate.Product
    import Data.Array.Accelerate.Array.Sugar
    import Data.Array.Accelerate.Data.Complex ()


    instance Unlift Exp (Exp a) where
      unlift = id



    class Unlift c (c e) => Lower c e where
      type Lowest c e
      lower :: c e -> Lowest c e


    instance (Elt a, Elt b, Lower Exp a, Lower Exp b) => Lower Exp (a, b) where
      type Lowest Exp (a, b) = (Lowest Exp a, Lowest Exp b)
      lower (unlift -> (aExp :: Exp a, bExp :: Exp b)) =
        (lower aExp, lower bExp)

    instance ( Elt a, Elt b, Elt c
             , Lower Exp a, Lower Exp b, Lower Exp c) => Lower Exp (a, b, c) where
      type Lowest Exp (a, b, c) = (Lowest Exp a, Lowest Exp b, Lowest Exp c)
      lower (unlift -> (aExp :: Exp a, bExp :: Exp b, cExp :: Exp c)) =
        (lower aExp, lower bExp, lower cExp)

    instance ( Elt a, Elt b, Elt c, Elt d
             , Lower Exp a, Lower Exp b, Lower Exp c, Lower Exp d) => Lower Exp (a, b, c, d) where
      type Lowest Exp (a, b, c, d) = (Lowest Exp a, Lowest Exp b, Lowest Exp c, Lowest Exp d)
      lower (unlift -> (aExp :: Exp a, bExp :: Exp b, cExp :: Exp c, dExp :: Exp d)) =
        (lower aExp, lower bExp, lower cExp, lower dExp)

    instance ( Elt a, Elt b, Elt c, Elt d, Elt e
             , Lower Exp a, Lower Exp b, Lower Exp c, Lower Exp d, Lower Exp e) => Lower Exp (a, b, c, d, e) where
      type Lowest Exp (a, b, c, d, e) = (Lowest Exp a, Lowest Exp b, Lowest Exp c, Lowest Exp d, Lowest Exp e)
      lower (unlift -> (aExp :: Exp a, bExp :: Exp b, cExp :: Exp c, dExp :: Exp d, eExp :: Exp e)) =
        (lower aExp, lower bExp, lower cExp, lower dExp, lower eExp)




    instance (Elt a, Lower Exp a) => Lower Exp (V1 a) where
      type Lowest Exp (V1 a) = V1 (Lowest Exp a)
      lower (unlift -> ve) =
        fmap lower ve

    instance (Elt a, Lower Exp a) => Lower Exp (V2 a) where
      type Lowest Exp (V2 a) = V2 (Lowest Exp a)
      lower (unlift -> ve) =
        fmap lower ve

    instance (Elt a, Lower Exp a) => Lower Exp (V3 a) where
      type Lowest Exp (V3 a) = V3 (Lowest Exp a)
      lower (unlift -> ve) =
        fmap lower ve



    instance Lower Exp Double where
      type Lowest Exp Double = Exp Double
      lower = id

    instance Lower Exp Float where
      type Lowest Exp Float = Exp Float
      lower = id

    instance Lower Exp Bool where
      type Lowest Exp Bool = Exp Bool
      lower = id

    instance Lower Exp Int where
      type Lowest Exp Int = Exp Int
      lower = id

`lower (Exp (V3 (V3 Double), Double))` should return a `(V3 (V3 (Exp Double)), Exp Double)`


I believe others, especially users of the `linear` library, would also find this useful. Would it possible to get this added to `accelerate`?

**Comment by tmcdonell** [comment]
Looks interesting. I have been playing with the linear library recently, but haven't quite figured it out, or where this fits in ):

Out of curiosity, I know there is a different approach to un/lifting several times in the [accelerate-utility](http://hackage.haskell.org/package/accelerate-utility) package, but I haven't used that either. Did you happen to try that one? I'm just curious if you have any comments comparing the two approaches.

**Comment by yongqli** [comment]
No, I haven't tried it yet.

I've settled on just 

    class Lower c e where
      type Lowest c e
      lower :: c e -> Lowest c e

so that I can define `lower` for things that can't be unlifted. So now it's just a convenience typeclass I suppose, without any "laws".

**Comment by tmcdonell** [comment]
An alternative is perhaps [`lens-accelerate`](https://hackage.haskell.org/package/lens-accelerate).
