### ISSUE TITLE
Matrix Multiplication error

### ISSUE THREAD

**Issue by aesadde** [AccelerateHS/accelerate#250]
Hi, 

I'm posting here because I got this error while benchmarking a matrix multiplication implementation 

`*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/CUDA/State.hs:85:9: (unhandled): CUDA Exception: an illegal memory access was encountered`

I am using criterion to run the benchmarks. 
The matrix multiplication code I'm using is this:

``` haskell
matMul a b = A.run $ sum' (prod aCube bCube)
  where
    sum' = A.fold (+) 0
    prod = A.zipWith (*)
    t    = A.transpose b
    getRow = A.indexHead . A.indexTail
    getCol = A.indexHead
    rowsA = getRow (A.shape a)
    colsB = getCol (A.shape b)
    sliceA = lift (Z :. All :. colsB :. All)
    sliceB = lift (Z :. rowsA :. All :. All)
    aCube = A.replicate sliceA a
    bCube = A.replicate sliceB t
```

I get the error when using square matrices of side 2^13 or larger.

Thanks,

**Comment by robeverest** [comment]
I'm having trouble reproducing this. Even with `cuda-memcheck` running I don't seem to be getting any illegal memory accesses. Could you give more information about what card you're using?

**Comment by tmcdonell** [comment]
@aesadde are you using a 32-bit ghc?

**Comment by aesadde** [comment]
Sorry for the late reply. I'm in a place with limited internet access. 
I'm running everything on an amazon EC2 instance with 
```
CUDA device query (Driver API, statically linked)
CUDA driver version 6.5
Detected 1 CUDA capable device

Device 0: GRID K520
  CUDA capability:                    3.0
  CUDA cores:                         1536 cores in 8 multiprocessors (192 cores/MP)
  Global memory:                      4 GB
  Constant memory:                    64 kB
  Shared memory per block:            48 kB
  Registers per block:                65536
  Warp size:                          32
  Maximum threads per multiprocessor: 2048
  Maximum threads per block:          1024
  Maximum grid dimensions:            2147483647 x 65535 x 65535
  Maximum block dimensions:           1024 x 1024 x 64
  GPU clock rate:                     797.0 MHz
  Memory clock rate:                  2.5 GHz
  Memory bus width:                   256-bit
  L2 cache size:                      512 kB
  Maximum texture dimensions         
    1D:                               65536
    2D:                               65536 x 65536
    3D:                               4096 x 4096 x 4096
  Texture alignment:                  512 B
  Maximum memory pitch:               2 GB
  Concurrent kernel execution:        Yes
  Concurrent copy and execution:      Yes, with 2 copy engines
  Runtime limit on kernel execution:  No
  Integrated GPU sharing host memory: No
  Host page-locked memory mapping:    Yes
  ECC memory support:                 No
  Unified addressing (UVA):           Yes
  PCI bus/location:                   0/3
  Compute mode:                       Default
    Multiple host threads can use the device simultaneously```

I'll get back to you as soon as I recover internet connectivity. 
Thanks!

**Comment by tmcdonell** [comment]
If you could run this in ghci and let me know what it returns:

```
Foreign.Storable.sizeOf (undefined::Int)
```

**Comment by aesadde** [comment]
Hi, 
I get this:
```haskell
Prelude Foreign> Foreign.Storable.sizeOf (undefined::Int)
8
```
Here is the code that reproduces the error:
```haskell
import Criterion.Main

import Prelude
import qualified Prelude as P hiding (zipWith,sum,take,drop,iterate)

import Data.Array.Accelerate as A hiding ((++))
import Data.Array.Accelerate.CUDA as A

matMul a b = A.run $ sum' (prod aCube bCube)
  where
    sum' = A.fold (+) 0
    prod = A.zipWith (*)
    t    = A.transpose b
    getRow = A.indexHead . A.indexTail
    getCol = A.indexHead
    rowsA = getRow (A.shape a)
    colsB = getCol (A.shape b)
    sliceA = lift (Z :. All :. colsB :. All)
    sliceB = lift (Z :. rowsA :. All :. All)
    aCube = A.replicate sliceA a
    bCube = A.replicate sliceB t

main = do
    let side = 2^13
    let size = side * side

    -- Accelerate configuration
    let mb = (A.fromList (Z :. side :. side) (P.replicate size 2) :: Array DIM2 Int)
    let ma = (A.fromList (Z :. side :. side) (P.replicate size 2) :: Array DIM2 Int)

    defaultMain
      [
        bench "Accelerate" $ whnf (matMul (A.use ma)) (A.use mb)
      ]
```

**Comment by robeverest** [comment]
I tried this on our Tesla machine and I got out of memory errors. Even though it has 4GB of memory, and it's supposedly all free, malloc fails allocating a 512MB array. This makes it very hard to test this.

@aesadde Could you possible give the output of running this example with `+ACC -ddump-gc -ACC`?

**Comment by yongqli** [comment]
@robeverest that sounds like it might be related to https://github.com/AccelerateHS/accelerate/issues/255, as my program runs fine on small inputs but fails on inputs it should be able to handle.

**Comment by robeverest** [comment]
@yongli What are the errors you're getting? Are they being reported by Accelerate or just `+RTS -xc`?

**Comment by yongqli** [comment]
@robeverest it's described more in #255, but if the inputs gets too large my program seems to freeze. In practice it seems to be trying to allocate memory over and over again and failing, as revealed by `+RTS -xc`. I'm trying to isolate a test case, but it's hard because each function runs fine on its own (even with large inputs), but somehow in combination triggers the bug.

**Comment by robeverest** [comment]
@yongqli What we've added recently is a graduated response to memory exhaustion. If allocation fails we first force GHC to perform a garbage collection to free any old arrays. If we still can't allocate, we start copying arrays back into host memory. This could explain the behaviour you're seeing. The repeated failures would be it trying to allocate after every array it copies. Either way, it's definitely different to what I described above. What I said above was more a commentary on the tesla hardware itself, the fact it seemed to not let us allocate 512MB despite nothing having been previously allocated. We should probably move this discussion over to #255. I will say more there.

**Comment by aesadde** [comment]
Hi, at last I am in a zone with proper internet. 

Here is the output of ``` +ACC -ddump-gc -ACC```

```
0.000:gc: initialise default context
0.028:gc: initialise context #0x00007f1874009650
0.028:gc: push context: #0x00007f1874009650
2.016:gc: initialise CUDA state
2.016:gc: initialise CUDA memory table
2.016:gc: malloc/context not found
2.016:gc: initialise memory table
2.016:gc: malloc: 512 MB
2.020:gc: malloc/new
2.020:gc: insert: 0
2.020:gc: lookup/found: 0
2.020:gc: withRemote/using: 0
2.160:gc: useArray/malloc: 512 MB @ 3.525 GB/s, gpu: 141.853 ms, cpu: 140.000 ms
4.164:gc: malloc: 512 MB
4.168:gc: malloc/new
4.168:gc: insert: 1
4.168:gc: lookup/found: 1
4.168:gc: withRemote/using: 1
4.308:gc: useArray/malloc: 512 MB @ 3.533 GB/s, gpu: 141.524 ms, cpu: 140.000 ms
4.312:gc: mallocArray: 512 MB
4.312:gc: malloc: 512 MB
4.312:gc: malloc/new
4.312:gc: insert: 2
4.320:gc: lookup/found: 1
4.320:gc: withRemote/using: 1
4.320:gc: lookup/found: 0
4.320:gc: withRemote/using: 0
4.320:gc: lookup/found: 2
4.320:gc: withRemote/using: 2
4.320:gc: finalise event 0x00007f187424b710
4.320:gc: finalise event 0x00007f187424a2a0
6.636:gc: pop context: #0x00007f1874009650
test.out:
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
```

Thanks,
