### ISSUE TITLE
Without profiling, program enters <<loop>>

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#251]
I'm currently using `accelerate 0.15.0.0`, and I have a strange bug where if my program is compiled with profiling turned off, it would get terminated with `<<loop>>`; but this does not happen if profiling is turned on. I believe this is caused by some initialization step in `accelerate`, as based on print statements that is when the `<<loop>>` happens. Any ideas?

**Comment by yongqli** [comment]
Using the compacting GC with `+RTS -c` does not help.

**Comment by yongqli** [comment]
Sorry, this is not an accelerate bug, my bad :(.

* * *

In case you were curious: I should have heeded the warning that "... for many monads (those for which the `>>=` operation is strict) this (Kleisli) instance will not satisfy the right-tightening law ..." It looks like using the strict state monad can cause `<<loop>>` under certain circumstances. It's not clear what exactly triggers it, as slightly altering the code can cause whatever optimization to be not applied and the `<<loop>>` to disappear.

**Comment by tmcdonell** [comment]
From memory we are using the strict state monad in various parts of the code, so I guess that is it.

If you find anything in our code that you think could alleviate your problems, let us know and maybe we can work around it somehow.

**Comment by yongqli** [comment]
This was actually an GHC bug https://ghc.haskell.org/trac/ghc/ticket/10218
