### ISSUE TITLE
error in hackage docs

### ISSUE THREAD

**Issue by projanen** [AccelerateHS/accelerate#252]
The explanation of fromIndex is "Inverse of fromIndex."

http://hackage.haskell.org/package/accelerate-0.14.0.0/docs/Data-Array-Accelerate.html#v:fromIndex

**Comment by robeverest** [comment]
Well spotted. Thanks.

**Comment by tmcdonell** [comment]
agh, pipped at the post!
that one has only been there for three years... *cough*
