### ISSUE TITLE
Does not compile on ghc 7.8.3

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#253]
Any ideas?

    Data/Array/Accelerate/CUDA/Array/Table.hs:107:16:
        Could not deduce (Data.Array.Accelerate.Array.Data.ArrayPtrs a
                          ~ GHC.Ptr.Ptr b)
        from the context (Typeable a, Typeable b)
          bound by the type signature for
                     lookup :: (Typeable a, Typeable b) =>
                               Context -> MemoryTable -> ArrayData a -> IO (Maybe (DevicePtr b))
          at Data/Array/Accelerate/CUDA/Array/Table.hs:103:11-103
        Relevant bindings include
          arr :: ArrayData a
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:104:19)
          lookup :: Context
                    -> MemoryTable -> ArrayData a -> IO (Maybe (DevicePtr b))
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:104:1)
        In the expression: MT.lookup mt arr
        In a case alternative: Just mt -> MT.lookup mt arr
        In the expression:
          case IM.lookup (contextId ctx) ct of {
            Nothing -> trace "lookup/context not found" $ return Nothing
            Just mt -> MT.lookup mt arr }

    Data/Array/Accelerate/CUDA/Array/Table.hs:118:20:
        Could not deduce (Data.Array.Accelerate.Array.Data.ArrayPtrs a
                          ~ GHC.Ptr.Ptr b)
        from the context (Typeable a, Typeable b, Storable b)
          bound by the type signature for
                     malloc :: (Typeable a, Typeable b, Storable b) =>
                               Context -> MemoryTable -> ArrayData a -> Int -> IO (DevicePtr b)
          at Data/Array/Accelerate/CUDA/Array/Table.hs:112:11-126
        Relevant bindings include
          ad :: ArrayData a
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:113:19)
          malloc :: Context
                    -> MemoryTable -> ArrayData a -> Int -> IO (DevicePtr b)
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:113:1)
        In the second argument of ‘($)’, namely ‘MT.malloc mt ad n’
        In a stmt of a 'do' block:
          mp <- blocking $ MT.malloc mt ad n :: IO (Maybe (DevicePtr b))
        In the expression:
          do { mt <- modifyMVar ref $ \ ct -> blocking $ do { ... };
               mp <- blocking $ MT.malloc mt ad n :: IO (Maybe (DevicePtr b));
               case mp of {
                 Nothing -> throwIO (ExitCode OutOfMemory)
                 Just p -> return p } }

    Data/Array/Accelerate/CUDA/Array/Table.hs:129:16:
        Could not deduce (Data.Array.Accelerate.Array.Data.ArrayPtrs a
                          ~ GHC.Ptr.Ptr b0)
        from the context (Typeable a)
          bound by the type signature for
                     free :: Typeable a =>
                             Context -> MemoryTable -> ArrayData a -> IO ()
          at Data/Array/Accelerate/CUDA/Array/Table.hs:125:9-68
        The type variable ‘b0’ is ambiguous
        Relevant bindings include
          arr :: ArrayData a
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:126:17)
          free :: Context -> MemoryTable -> ArrayData a -> IO ()
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:126:1)
        In the expression: MT.free mt arr
        In a case alternative: Just mt -> MT.free mt arr
        In the expression:
          case IM.lookup (contextId ctx) ct of {
            Nothing -> message "free/context not found"
            Just mt -> MT.free mt arr }

    Data/Array/Accelerate/CUDA/Array/Table.hs:142:14:
        Could not deduce (Data.Array.Accelerate.Array.Data.ArrayPtrs a
                          ~ GHC.Ptr.Ptr b)
        from the context (Typeable a, Typeable b)
          bound by the type signature for
                     insertUnmanaged :: (Typeable a, Typeable b) =>
                                        Context -> MemoryTable -> ArrayData a -> DevicePtr b -> IO ()
          at Data/Array/Accelerate/CUDA/Array/Table.hs:136:20-108
        Relevant bindings include
          ptr :: DevicePtr b
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:137:33)
          arr :: ArrayData a
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:137:28)
          insertUnmanaged :: Context
                             -> MemoryTable -> ArrayData a -> DevicePtr b -> IO ()
            (bound at Data/Array/Accelerate/CUDA/Array/Table.hs:137:1)
        In the second argument of ‘($)’, namely
          ‘MT.insertUnmanaged mt arr ptr’
        In a stmt of a 'do' block: blocking $ MT.insertUnmanaged mt arr ptr
        In the expression:
          do { mt <- modifyMVar ref $ \ ct -> blocking $ do { ... };
               blocking $ MT.insertUnmanaged mt arr ptr }

     % ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3

**Comment by yongqli** [comment]
I'm also getting the warnings:

    Data/Array/Accelerate/CUDA/CodeGen/Constant.hs:54:15: Warning:
        accepting non-standard pattern guards (use PatternGuards to suppress this message)
            IntegralDict <- integralDict ty

    Data/Array/Accelerate/CUDA/CodeGen/Constant.hs:83:39: Warning:
        accepting non-standard pattern guards (use PatternGuards to suppress this message)
            IntegralDict <- integralDict ty

    Data/Array/Accelerate/CUDA/CodeGen/Constant.hs:84:39: Warning:
        accepting non-standard pattern guards (use PatternGuards to suppress this message)
            NonNumDict <- nonNumDict ty

    Data/Array/Accelerate/CUDA/CodeGen/Constant.hs:87:39: Warning:
        accepting non-standard pattern guards (use PatternGuards to suppress this message)
            IntegralDict <- integralDict ty

    Data/Array/Accelerate/CUDA/CodeGen/Constant.hs:88:39: Warning:
        accepting non-standard pattern guards (use PatternGuards to suppress this message)
            NonNumDict <- nonNumDict ty

    Data/Array/Accelerate/CUDA/CodeGen/Constant.hs:91:11: Warning:
        accepting non-standard pattern guards (use PatternGuards to suppress this message)
            FloatingDict <- floatingDict ty

**Comment by robeverest** [comment]
Oops, sorry. This one is my fault. I forgot to push some changes to accelerate-cuda. Should be fixed now. The warnings have been there for a while, but while I'm thinking about it, might as well fix that too.

**Comment by yongqli** [comment]
Excellent, complies now.
