### ISSUE TITLE
accelerate-examples nofib does not build

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#254]
examples/quickcheck/Test/Base.hs:64:10:
        Duplicate instance declarations:
          instance Eq Z -- Defined at examples/quickcheck/Test/Base.hs:64:10
          instance Eq Z -- Defined in ‘Data.Array.Accelerate.Array.Sugar’
    cabal: Error: some packages failed to install:
    accelerate-examples-0.12.1.0 failed during the building phase. The exception
    was:
    ExitFailure 1

**Comment by tmcdonell** [comment]
The problem is that you are trying to install a very old version of accelerate-examples. Probably you are using the github version of `accelerate` but not the `accelerate-examples` package as well?

**Comment by yongqli** [comment]
Yep, that was the issue.
