### ISSUE TITLE
context is destroyed

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#256]
*** Internal error in package accelerate ***
    *** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
    ./Data/Array/Accelerate/CUDA/State.hs:84:9: (unhandled): CUDA Exception: context is destroyed

**Comment by yongqli** [comment]
On long running processes I see really weird errors like:

    *** Internal error in package accelerate ***
    *** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
    ./Data/Array/Accelerate/CUDA/State.hs:84:9: (unhandled): CUDA Exception: function named symbol not found: foldAll

**Comment by tmcdonell** [comment]
Oh dear...

Are your long running programs generating lots of unique kernels, or are they reusing the same kernels over and over? I'm wondering if we are hitting some kind of internal limit to the number of kernel modules we can load at any one time (and whether we have to start unloading old ones).

**Comment by tmcdonell** [comment]
Also not sure about the destroyed context error. Are you using the default contexts? That is, `run` or `run1`, not any `runWith` variants where you pass the context explicitly? The default variants should just keep the context alive forever.

**Comment by yongqli** [comment]
I'm also seeing `[2]    15859 segmentation fault (core dumped)`

There should only be 3 or so kernel in my program. I'm using only `run` and `run1`.

The errors are very non-deterministic -- sometime it happens quickly, other times only after 40 minutes or so. Thus it seems like another race condition of some sort to me.

I'll try to create a test case.

**Comment by yongqli** [comment]
There shouldn't be an issue with using CUDA Toolkit 7, right?

**Comment by tmcdonell** [comment]
I haven't tried CUDA-7 yet, but I wouldn't expect that to be a problem.

**Comment by robeverest** [comment]
It is possible this is related to the use of `mkWeak#`. It was causing me segfaults in other contexts. It could also explain the context being destroyed, if the finalizer is running early. I'll fiddle with it now and see what happens.

**Comment by tmcdonell** [comment]
@robeverest I think something must have changed since I initially wrote all the finaliser code that we are now having so many problems. I feel bad that you have to clean up after all this \:

**Comment by robeverest** [comment]
I think the problem is largely to do with attaching a weak pointer to an `Addr#`. I'm not sure if this has ever been supported, or if it just used to fail silently so we never noticed it wasn't working. 

You've had to fix bugs I've created far more often than the other way round.  :-)

**Comment by tmcdonell** [comment]
Yeah, using `Addr#` might not work. Anyway, finaliser code does indeed fail silently (or at least it used to...), and I never saw any errors/exceptions raised from finaliser code.

**Comment by robeverest** [comment]
I noticed that if you ran withthe debug RTS turned on, you would sometimes get an assertion failure when the GC tried to mark as dead a weak pointer that was attached to an `Addr#`. However, it was pretty rare. The assertion that failed was one that checked if the pointer "looked like" an `StgPtr`. It wouldn't surprise me if we just haven't noticed it before. 

For future note, it's probably a good idea to run everything with the debugging RTS before each release.

**Comment by robeverest** [comment]
So I've just pushed a fix for the context finalizers. This should hopefully fix the context related errors. However, I suspect it will not fix the `function named symbol not found`.

@yongqli As we don't really have a reliable test case for this, can you perhaps run your code again and see if this has in fact fixed the problem?

@tmcdonell I suspect the problem is not that we're loading too many modules, rather that once again we're attaching a weak pointer to a non-primitive and it's causing the finalizer to fire early. In this case, there's no obvious primitive to attach the weak pointer to, as the internals of `Module` are not exposed, but I think I have a way around that. I'm experimenting with it now.

**Comment by mchakravarty** [comment]
Attaching a finalizer to `Addr#` should be fine, because that is what GHC's implementation of `ForeignPtr` does. (`ForeignPtr`s are just a wrapper around `Addr#`). However, if you look at the implementation, you'll see that it is all a bit tricky: https://github.com/ghc/packages-base/blob/master/GHC/ForeignPtr.hs#L321

**Comment by robeverest** [comment]
@mchakravarty Actually, unless I'm very mistaken, the weak pointer (and also the finalizers) are attached to the `MutVar#` contained within an IORef. It gets a bit confusing because the `Add#` of the underlying pointer is passed to `addCFinalizerToWeak#`, but the finalizer is actually attached to the weak pointer, which is made from the `IORef`.

I'm actually working on a structure that works in a similar way to `ForeignPtr`, but can store more than just pointers. I figure if we have that, constructed carefully and with well defined behaviour, we can just use when needed and not keep on running into problems.

**Comment by robeverest** [comment]
@yongqli I think I may have also fixed the `function named symbol` error as well now, let me know how it works out.

**Comment by yongqli** [comment]
Awesome, I was just going to post the results of the earlier fix, but let's see how this new fix works out :). :+1:

**Comment by yongqli** [comment]
It seems to be much less frequent now, but still occasionally happens.

**Comment by yongqli** [comment]
Do you still don't know why the CUDA exceptions happen? The function involved changes, btw. Sometimes it is `map`. It is very hard to reproduce.

**Comment by yongqli** [comment]
From the debug logs, it looks like a successful invocation looks like:

    6065.087:cc: entry function 'map' used 16 registers, 0 bytes smem, 0 bytes lmem, 0 bytes cmem
          ... multiprocessor occupancy 100.0% : 2048 threads over 64 warps in 16 blocks
    6065.087:gc: lookup/found: 46340
    6065.087:gc: withRemote/using: 46340
    6065.088:gc: lookup/found: 46341
    6065.088:gc: withRemote/using: 46341
    6065.088:gc: lookup/found: 46342
    6065.088:gc: withRemote/using: 46342
    6065.088:gc: lookup/found: 46349
    6065.088:gc: withRemote/using: 46349
    6065.088:gc: lookup/found: 46350
    6065.088:gc: withRemote/using: 46350
    6065.088:gc: lookup/found: 46351
    6065.088:gc: withRemote/using: 46351
    6065.089:cc: entry function 'foldAll' used 26 registers, 0 bytes smem, 0 bytes lmem, 0 bytes cmem
          ... multiprocessor occupancy 100.0% : 2048 threads over 64 warps in 2 blocks



While a failing one looks like:

    6107.127:cc: entry function 'map' used 16 registers, 0 bytes smem, 0 bytes lmem, 0 bytes cmem
          ... multiprocessor occupancy 100.0% : 2048 threads over 64 warps in 16 blocks
    6107.127:gc: lookup/found: 47328
    6107.127:gc: withRemote/using: 47328
    6107.127:gc: lookup/found: 47329
    6107.127:gc: withRemote/using: 47329
    6107.127:gc: lookup/found: 47330
    6107.127:gc: withRemote/using: 47330
    6107.127:gc: lookup/found: 47337
    6107.127:gc: withRemote/using: 47337
    6107.127:gc: lookup/found: 47338
    6107.127:gc: withRemote/using: 47338
    6107.128:gc: lookup/found: 47339
    6107.128:gc: withRemote/using: 47339
    [1]    9441 segmentation fault (core dumped)


So it seems that a bad pointer was found? Can you add more logging info, maybe check that the array found actually exists?

**Comment by yongqli** [comment]
Here's another one:

    6396.813:gc: lookup/found: 50575
    6396.813:gc: withRemote/using: 50575
    6396.817:gc: mallocArray: 2 MB
    6396.817:gc: malloc: 2 MB
    6396.817:gc: malloc/nursery
    6396.818:gc: insert: 50576
    6396.818:gc: mallocArray: 2 MB
    6396.818:gc: malloc: 2 MB
    6396.818:gc: malloc/nursery
    6396.818:gc: insert: 50577
    6396.818:gc: mallocArray: 2 MB
    6396.818:gc: malloc: 2 MB
    6396.818:gc: malloc/nursery
    6396.819:gc: insert: 50578
    6396.819:gc: mallocArray: 2 MB
    6396.819:gc: malloc: 2 MB
    6396.819:gc: malloc/nursery
    6396.819:gc: insert: 50579
    6396.819:gc: lookup/found: 50570
    6396.819:gc: withRemote/using: 50570
    6396.819:gc: lookup/found: 50571
    6396.819:gc: withRemote/using: 50571
    6396.819:gc: lookup/found: 50572
    6396.819:gc: withRemote/using: 50572
    6396.819:gc: lookup/found: 50573
    6396.819:gc: withRemote/using: 50573
    6396.819:gc: lookup/found: 50574
    6396.819:gc: withRemote/using: 50574
    6396.820:gc: lookup/found: 50575
    6396.820:gc: withRemote/using: 50575
    6396.820:gc: lookup/found: 50576
    6396.820:gc: withRemote/using: 50576
    6396.820:gc: lookup/found: 50577
    6396.820:gc: withRemote/using: 50577
    6396.820:gc: lookup/found: 50578
    6396.820:gc: withRemote/using: 50578
    6396.820:gc: lookup/found: 50579
    6396.820:gc: withRemote/using: 50579
    [1]    26827 segmentation fault (core dumped)

**Comment by yongqli** [comment]
The only thing unconventional with my code is that I basically do `arrayZip xsA ysA = GPGPU.run $ A.zip (A.use xsA) (A.use ysA)`, where a `ysA` is zipped with several `xsA`s. That shouldn't trigger any sort of double-frees, right?

**Comment by yongqli** [comment]
12927.974:gc: withRemote/using: 59296
    12927.977:gc: mallocArray: 4 MB
    12927.977:gc: malloc: 4 MB
    12927.977:gc: malloc/nursery
    12927.977:gc: insert: 59297
    12927.977:gc: mallocArray: 4 MB
    12927.977:gc: malloc: 4 MB
    12927.977:gc: malloc/nursery
    12927.977:gc: insert: 59298
    12927.977:gc: mallocArray: 4 MB
    12927.977:gc: malloc: 4 MB
    12927.977:gc: malloc/nursery
    12927.977:gc: insert: 59299
    12927.977:gc: mallocArray: 4 MB
    12927.977:gc: malloc: 4 MB
    12927.977:gc: malloc/nursery
    12927.977:gc: insert: 59300
    12927.977:cc: entry function 'map' used 20 registers, 0 bytes smem, 0 bytes lmem, 0 bytes cmem
          ... multiprocessor occupancy 100.0% : 2048 threads over 64 warps in 16 blocks
    12927.977:gc: lookup/found: 59291
    12927.978:gc: withRemote/using: 59291
    12927.978:gc: lookup/found: 59292
    12927.978:gc: withRemote/using: 59292
    12927.978:gc: lookup/found: 59293
    12927.979:gc: withRemote/using: 59293
    12927.979:gc: lookup/found: 59294
    12927.979:gc: withRemote/using: 59294
    12927.979:gc: lookup/found: 59295
    12927.979:gc: withRemote/using: 59295
    12927.979:gc: lookup/found: 59296
    12927.979:gc: withRemote/using: 59296
    12927.979:gc: lookup/found: 59297
    12927.979:gc: withRemote/using: 59297
    12927.979:gc: lookup/found: 59298
    12927.979:gc: withRemote/using: 59298
    12927.979:gc: lookup/found: 59299
    12927.979:gc: withRemote/using: 59299
    12927.979:gc: lookup/found: 59300
    12927.979:gc: withRemote/using: 59300
    12927.980:gc: mallocArray: 4 MB
    12927.980:gc: malloc: 4 MB
    12927.980:gc: malloc/nursery
    12927.980:gc: insert: 59301
    12927.980:gc: mallocArray: 4 MB
    12927.980:gc: malloc: 4 MB
    12927.980:gc: malloc/nursery
    12927.980:gc: insert: 59302
    12927.980:cc: entry function 'generate' used 14 registers, 0 bytes smem, 0 bytes lmem, 0 bytes cmem
          ... multiprocessor occupancy 100.0% : 2048 threads over 64 warps in 16 blocks
    12927.980:gc: lookup/found: 59284
    12927.980:gc: withRemote/using: 59284
    12927.984:gc: lookup/found: 59285
    12927.984:gc: withRemote/using: 59285
    12927.984:gc: lookup/found: 59291
    12927.984:gc: withRemote/using: 59291
    12927.984:gc: lookup/found: 59292
    12927.984:gc: withRemote/using: 59292
    12927.984:gc: lookup/found: 59293
    12927.984:gc: withRemote/using: 59293
    12927.984:gc: lookup/found: 59294
    12927.984:gc: withRemote/using: 59294
    12927.984:gc: lookup/found: 59295
    12927.984:gc: withRemote/using: 59295
    12927.984:gc: lookup/found: 59296
    12927.984:gc: withRemote/using: 59296
    12927.984:gc: lookup/found: 59301
    12927.984:gc: withRemote/using: 59301
    12927.984:gc: lookup/found: 59302
    12927.984:gc: withRemote/using: 59302
    12927.984:gc: lookup/found: 59297
    12927.984:gc: withRemote/using: 59297
    12927.984:gc: lookup/found: 59298
    12927.984:gc: withRemote/using: 59298
    12927.984:gc: peekArray: 4 MB @ 7.785 GB/s, gpu: 459.360 µs, cpu: 0.000 s
    12927.984:gc: peekArray: 4 MB @ 6.918 GB/s, gpu: 516.928 µs, cpu: 0.000 s
    12927.984:gc: lookup/found: 59299
    12927.984:gc: withRemote/using: 59299
    12927.985:gc: lookup/found: 59300
    12927.985:gc: withRemote/using: 59300
    12927.986:gc: peekArray: 4 MB @ 7.861 GB/s, gpu: 454.944 µs, cpu: 290.000 µs
    12927.986:gc: peekArray: 4 MB @ 7.038 GB/s, gpu: 508.128 µs, cpu: 537.000 µs
    12927.986:gc: lookup/found: 59301
    12927.986:gc: withRemote/using: 59301
    12927.987:gc: lookup/found: 59302
    12927.988:gc: withRemote/using: 59302
    12927.988:gc: peekArray: 4 MB @ 7.696 GB/s, gpu: 464.704 µs, cpu: 1.145 ms
    12927.989:gc: pop context: #0x00007f5af00297c0
    12927.989:gc: peekArray: 4 MB @ 8.011 GB/s, gpu: 446.400 µs, cpu: 517.000 µs
    12927.989:gc: malloc: 8 kB
    12927.989:gc: malloc/nursery
    12927.989:gc: insert: 59303
    12927.989:gc: lookup/found: 59303
    12927.989:gc: withRemote/using: 59303
    12927.990:gc: malloc: 8 kB
    12927.990:gc: malloc/nursery
    12927.990:gc: insert: 59304
    12927.990:gc: lookup/found: 59304
    12927.990:gc: withRemote/using: 59304
    12927.990:gc: useArray/malloc: 8 B @ 213.410 kB/s, gpu: 36.608 µs, cpu: 0.000 s
    12927.990:gc: useArray/malloc: 8 B @ 117.885 kB/s, gpu: 66.272 µs, cpu: 159.000 µs
    12927.990:gc: malloc: 8 kB
    12927.990:gc: malloc/nursery
    12927.990:gc: insert: 59305
    12927.990:gc: lookup/found: 59305
    12927.990:gc: withRemote/using: 59305
    12927.991:gc: finalize cache: 59305
    12927.991:gc: finalize cache: 59304
    12927.991:gc: mallocArray: 396 MB
    12927.991:gc: useArray/malloc: 8 B @ 601.332 kB/s, gpu: 12.992 µs, cpu: 18.000 µs
    12927.992:gc: malloc: 396 MB
    12927.992:gc: malloc/nursery
    12927.992:gc: insert: 59306
    12927.992:gc: lookup/found: 59306
    12927.992:gc: withRemote/using: 59306
    *** Error in `./dist/build/APU2/APU2': munmap_chunk(): invalid pointer: 0x00007f5997698d90 ***
    [1]    33163 abort (core dumped)

**Comment by robeverest** [comment]
I don't think the issue is a bad pointer. If that were the case, you'd get exceptions from the CUDA runtime, not a host-side segfault. I thought these segfaults were from the misuse of `mkWeak#`, which I have seen before, but it looks like there must be something else involved as well. 

You also should be able to use an array many times without it being freed more than once. 

You can try running your program with `gdb`, or similar, to see what is causing a segfault, but it is likely we'll need an example to really track this down. You can also try passing `-debug` to GHC to get it to build with the debugging RTS, which may yield an assertion error instead of a segfault.

**Comment by mchakravarty** [comment]
> I'm actually working on a structure that works in a similar way to ForeignPtr, but can store more than just pointers. I figure if we have that, constructed carefully and with well defined behaviour, we can just use when needed and not keep on running into problems.

Ok. Sounds good.

**Comment by yongqli** [comment]
Looks like this is fixed. Thanks.
