### ISSUE TITLE
Interpreter backend bit rot?

### ISSUE THREAD

**Issue by yongqli** [AccelerateHS/accelerate#262]
I'm getting an exception from the Interpreter backend with a unit test that runs fine on CUDA: `Exception: ./Data/Array/Accelerate/Array/Representation.hs:110:39: (toIndex): index out of bounds: (15,15)`.

Any advice on debugging this other than deleting code piece and piece and seeing where the error goes away?

**Comment by yongqli** [comment]
Data.Array.Accelerate.Array.Representation.toIndex.\,
    called from Data.Array.Accelerate.Array.Representation.toIndex,
    called from Data.Array.Accelerate.Array.Sugar.toIndex,
    called from Data.Array.Accelerate.Interpreter.evalPreOpenExp,
    called from Data.Array.Accelerate.Interpreter.evalPreOpenFun,
    called from Data.Array.Accelerate.Interpreter.evalPreFun,
    called from Data.Array.Accelerate.Interpreter.evalOpenAcc.evalF,
    called from Data.Array.Accelerate.Array.Representation.iter.iter',
    called from Data.Array.Accelerate.Array.Representation.iter.\,
    called from Data.Array.Accelerate.Array.Representation.iter,
    called from Data.Array.Accelerate.Array.Representation.iter,
    called from Data.Array.Accelerate.Array.Sugar.iter,
    called from Data.Array.Accelerate.Interpreter.generateOp,
    called from Data.Array.Accelerate.Interpreter.evalOpenAcc,
    called from Data.Array.Accelerate.Interpreter.evalOpenAfun,
    called from Data.Array.Accelerate.Interpreter.run1,

**Comment by tmcdonell** [comment]
What program/operation are you having a problem with? I know that the implementation of segmented scan is currently not working for empty arrays/segments, although the CUDA backend might not error.

**Comment by yongqli** [comment]
No, I'm not using that. I have a bunch of simple operations on `linear` vectors like `V2`, `V3`, etc.

**Comment by tmcdonell** [comment]
Hm, if you could send an example that would be good. The CUDA backend is less likely to generate errors, and we would like that the interpreter to be known to always do the right thing.

**Comment by yongqli** [comment]
This turned out to be a bug in my code. It looks like the CUDA backend is more tolerant of accessing out of bounds memory.

**Comment by tmcdonell** [comment]
Ah! Anyway, yes, it is very difficult for the CUDA backend to catch/throw all exceptions, which is why we want to make sure that the interpreter works, so thanks for the report anyway (:
