### ISSUE TITLE
Hackage releases for ghc-7.10

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#265]
We should make a Hackage release that compiles with 7.10. Either a patch release on the 0.15 branch, or make the effort to push 1.0.

 - [x] accelerate
 - [x] accelerate-cuda
 - [x] accelerate-io
 - [x] accelerate-fft
 - [x] accelerate-examples
 - [x] cuda
 - [x] cufft
 - [x] gloss-accelerate
 - [x] gloss-raster-accelerate

**Comment by tmcdonell** [comment]
Now with external pressure: fpco/stackage#378

**Comment by tmcdonell** [comment]
I'm going to make some patch releases on the 0.15 branches.

@robeverest if the cufft bindings on Hackage compile with 7.8 and 7.10, please check off that item.

**Comment by tmcdonell** [comment]
ping #233

**Comment by tmcdonell** [comment]
ping #275

**Comment by tmcdonell** [comment]
ping #274

**Comment by tmcdonell** [comment]
ping #277

**Comment by tmcdonell** [comment]
Okay, 0.15.1 patch releases for ghc-7.8 and 7.10 are (finally) out.

That was significantly more difficult than it should have been. Lots of different changes that had to be untangled (`Tuple`/`Product`, `EltRepr`, and streaming operations).

**Comment by mchakravarty** [comment]
Thank you!!
