### ISSUE TITLE
error in installing accelerate-cuda

### ISSUE THREAD

**Issue by intersense** [AccelerateHS/accelerate#275]
when I was installing accelerate-cuda using "cabal install accelerate-cuda", I got the following error. 
ghc: 7.8.4
cabal: 1.22.0
ubuntu 14.10
cuda 7.0
Could anyone help me?

[26 of 33] Compiling Data.Array.Accelerate.CUDA.Array.Sugar ( Data/Array/Acceler                                                                                                                               ate/CUDA/Array/Sugar.hs, dist/build/Data/Array/Accelerate/CUDA/Array/Sugar.o )

Data/Array/Accelerate/CUDA/Array/Sugar.hs:42:19:
    Couldn't match expected type ‘Array dim0 e1’
                with actual type ‘IO (Array dim e0)’
    Relevant bindings include
      arr :: IO (Array dim e0)
        (bound at Data/Array/Accelerate/CUDA/Array/Sugar.hs:40:7)
      sh :: dim
        (bound at Data/Array/Accelerate/CUDA/Array/Sugar.hs:39:15)
      allocateArray :: dim -> CIO (Array dim e)
        (bound at Data/Array/Accelerate/CUDA/Array/Sugar.hs:39:1)
    In the first argument of ‘mallocArray’, namely ‘arr’
    In a stmt of a 'do' block: mallocArray arr

Data/Array/Accelerate/CUDA/Array/Sugar.hs:43:14:
    Couldn't match expected type ‘Array dim e’
                with actual type ‘IO (Array dim e0)’
    Relevant bindings include
      arr :: IO (Array dim e0)
        (bound at Data/Array/Accelerate/CUDA/Array/Sugar.hs:40:7)
      sh :: dim
        (bound at Data/Array/Accelerate/CUDA/Array/Sugar.hs:39:15)
      allocateArray :: dim -> CIO (Array dim e)
        (bound at Data/Array/Accelerate/CUDA/Array/Sugar.hs:39:1)
    In the first argument of ‘return’, namely ‘arr’
    In a stmt of a 'do' block: return arr
cabal: Error: some packages failed to install:
accelerate-cuda-0.15.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by tmcdonell** [comment]
Ah, sorry about that. I'll upload a fixed version to Hackage ASAP.

The versions on github should compile fine, if you want to use those.

**Comment by intersense** [comment]
Thank you tmcdonell! I'll try that.

**Comment by intersense** [comment]
Thank you tmcdonell! 
It works!

**Comment by tmcdonell** [comment]
accelerate-cuda-0.15.1.0 is out on Hackage which fixes this. Sorry for the delay.
