### ISSUE TITLE
Reduce using Acc (Vector a) -> Acc (Scalar a)

### ISSUE THREAD

**Issue by johncant** [AccelerateHS/accelerate#279]
Hello!

Is there a standard way to apply a vector-to-scalar function across a dimension of an array? Obviously using `the` and `generate` won't work, since it would introduce nested data parallelism. I can't find anything in the docs or the code, so is there anything I've missed? What should it be called, since in lists it would just be map?

```
somefunc :: (Elt a, Elt b, Shape sh) => (Acc (Vector a) -> Acc (Scalar b)) -> Exp Int -> Acc (Array sh:.Int a)-> Acc (Array sh b)
somefunc f a = undefined
```

If not, I'll try and transform the surface level AST of `f` to include the dimensions of a. Hope it can be of use somewhere!

**Comment by robeverest** [comment]
So unfortunately there is no way to write a function like this  in Accelerate. Nested parallelism like this is something we're working on, but it's not quite ready for prime time yet. We are experimenting with adding streams to the language, which, if you're very brave, you can checkout on the `streaming` branch and would let you write a function like this, but I wouldn't recommend it.

Can I ask what you're wanting to do with a map like this? Usually you can work around needing nested parallelism in the context of a more concrete example.

**Comment by tmcdonell** [comment]
From your example type signature above, it looks like you just need the regular multidimensional reduction. Since this reduces over the innermost dimension of the array only, you might need to transpose your data first to select the dimension you want. If that's not what you need, we'll need a concrete example...

**Comment by johncant** [comment]
Thankyou for replying. I am trying to implement symbolic differentiation for Accelerate, for the purposes of making deep learning easier. I have something working for most Exp functions, and now I need to extend it to deal with jacobians and grad. This in itself doesn't require the function I'm after, but I'm testing my implementations by comparing results to the numerical derivative. Evaluating grad of some accelerate function numerically seems to require the ability to apply a vector-to-scalar function along one dimension of a matrix.

I'd be very grateful to anyone who'd like to take a look at my repo and contribute or critique it: https://github.com/johncant/accelerate-symdiff. You may notice a few very dirty hacks!

**Comment by tmcdonell** [comment]
I guess this can be closed, feel free to reopen or start a new issue if you have further questions.
