### ISSUE TITLE
Build error "Not in scope: ‘CUDA.useContext’"

### ISSUE THREAD

**Issue by neiljamieso** [AccelerateHS/accelerate#282]
Found same errors as #281.  Also once those eliminated as suggested had this error in compiling Data/Array/Accelerate/CUDA/Context.hs (repeated in various locations).  useContext is explicitly hidden.

**Comment by tmcdonell** [comment]
Oh, is this using the CUDA package from Github, or Hackage? I have been changing it quite a bit recently...

**Comment by neiljamieso** [comment]
From github.  Would I be better to use the hackage version?

**Comment by tmcdonell** [comment]
Hackage version should still work, but I'll fix the github version shortly.

**Comment by tmcdonell** [comment]
I finally released a new version of the CUDA bindings package to Hackage, so everything should work again.
