### ISSUE TITLE
Memory leak / performance regression

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#286]
@cpdurham submitted the attached program, which looks to be a performance regression when using ghc-7.10 and the vector package. From the email:

> I'm creating a whole bunch of images and then through the pipes package sending them to either an accelerate consumer or a vector consumer, which are commented. The function adds up the elements in the vector/array and accumulates the result. The vector consumer stays around 5mb in memory, the accelerate version keeps going.
> 
> To test my conversion methods from a vector, i also included a version that uses fromList to create the arrays and a separate producer, same leak.

Sample program: https://gist.github.com/tmcdonell/9c32d1c91e9541220db9

**Comment by tmcdonell** [comment]
Interestingly, the problem is present with both GPU backends (`accelerate-cuda` and `accelerate-llvm-ptx`), but not the CPU backend (`accelerate-llvm-native`). My (completely unfounded at this point) guess is that the hash tables used by the GPU backends to track device memory keeps resizing as new arrays are allocated, but never shrinks after they are deleted. Actually, I just noticed that the [hashtables documentation](https://hackage.haskell.org/package/hashtables-1.2.1.0/docs/Data-HashTable-ST-Basic.html) (now?) mentions that workloads heavy with deletes (which we have) will clutter the table with delete markers, which could also be contributing. It could also just be that we are not running finalisers quickly enough.

**Comment by tmcdonell** [comment]
This was just a standard space leak in the LRU use counts (ping @robeverest). Should be all good now.

![llvm-ptx-286](https://cloud.githubusercontent.com/assets/728113/20780183/5b72cee6-b7cd-11e6-9f7c-7ede5c111cdc.png)

**Comment by robeverest** [comment]
Ah, well spotted.
