### ISSUE TITLE
Image file created by `writeImageToBMP` flipped vertically

### ISSUE THREAD

**Issue by robstewart57** [AccelerateHS/accelerate#289]
Given this program:

``` haskell
{-# LANGUAGE TypeOperators,ScopedTypeVariables,FlexibleContexts #-}

module Main where

import Data.Array.Accelerate hiding (map,(++))
import Data.Array.Accelerate.Interpreter
import qualified Data.Array.Accelerate as A
import qualified Data.Array.Accelerate.IO as A

main :: IO ()
main = do
  let blue    = [0,46,184]
      red     = [184,0,46]
      shape2x3x3 = Z :. 2 :. 3 :. 3
  let imageData = blue ++ red  ++ blue
               ++ red  ++ blue ++ red
  let imgArr    = A.fromList shape2x3x3 imageData
      imgRGBA32 = A.map A.packRGBA32 (img3dTo2d 2 3 (use imgArr))
  A.writeImageToBMP "out.bmp" (run imgRGBA32)

-- | flattens 3D Word8 array to 2D image with 255 alpha value at each pixel.
img3dTo2d :: Int -> Int -> Acc (Array DIM3 Word8) -> Acc (Array DIM2 (Word8,Word8,Word8,Word8))
img3dTo2d height width img3d = 
 generate (index2 (lift height) (lift width))
              (\ix -> let (Z :. (h::Exp Int) :. (w::Exp Int)) = unlift ix
                          r = img3d ! lift (Z :. h :. w :. constant 0) :: Exp Word8
                          g = img3d ! lift (Z :. h :. w :. constant 1) :: Exp Word8
                          b = img3d ! lift (Z :. h :. w :. constant 2) :: Exp Word8
                      in lift (r,g,b,constant 255))
```

I assumed that the "out.bmp" image would look like this:

![expected](https://cloud.githubusercontent.com/assets/800982/11152550/286ea4aa-8a2b-11e5-9df0-3c931725b35b.png)

It doesn't. Instead, it looks like this:

![result](https://cloud.githubusercontent.com/assets/800982/11152556/30e9b9d0-8a2b-11e5-854a-262e5bc4bb6b.png)

One of two things is happening.
1. My assumption about how image data should be ordered is wrong. My assumption is that image RGB pixel data starts at the top left, progressing row wise left to right, for each row, until the pixel at the bottom right is reached.
2. Somewhere in the accelerate functions I'm using, my 2D RGBA array is being reversed which would explain the 180 degree rotation, probably inside the implementation of `writeImageToBMP`.

Which is it? I ask because I'm mapping camera frames into accelerate arrays, and the data pointers containing frame data is ordered according to my assumptions in item (1) above. See: http://sourceforge.net/p/libdc1394/mailman/libdc1394-devel/?viewmonth=201511 for confirmation of this for the dc1394 firewire camera API.

What I'd really like to be true is for there to be a way to use the `writeImageToBMP` function on captured firewire frames, without having to reverse the entire array first.

**Comment by tmcdonell** [comment]
It appears the image data starts at the bottom left, not the top left, and traverses left-to-right bottom-to-top. If you make the first element a different colour to the others (e.g. green) you can see this. I'm not sure yet if that is part of our library, the way that BMP is interpreted, or something else.

Does that match what you are seeing?

**Comment by robstewart57** [comment]
Hi @tmcdonell , you're right. Adding a green pixel value to the Haskell:

```haskell
{-# LANGUAGE TypeOperators,ScopedTypeVariables,FlexibleContexts #-}

module Main where

import Data.Array.Accelerate hiding (map,(++))
import Data.Array.Accelerate.Interpreter
import qualified Data.Array.Accelerate as A
import qualified Data.Array.Accelerate.IO as A

main :: IO ()
main = do
  let blue    = [0,46,184]
      red     = [184,0,46]
      green   = [46,184,0]
      shape2x3x3 = Z :. 2 :. 3 :. 3
  let imageData = green ++ red  ++ blue
               ++ red   ++ blue ++ red
  let imgArr    = A.fromList shape2x3x3 imageData
      imgRGBA32 = A.map A.packRGBA32 (img3dTo2d 2 3 (use imgArr))
  A.writeImageToBMP "out.bmp" (run imgRGBA32)

-- | flattens 3D Word8 array to 2D image with 255 alpha value at each pixel.
img3dTo2d :: Int -> Int -> Acc (Array DIM3 Word8) -> Acc (Array DIM2 (Word8,Word8,Word8,Word8))
img3dTo2d height width img3d = 
 generate (index2 (lift height) (lift width))
              (\ix -> let (Z :. (h::Exp Int) :. (w::Exp Int)) = unlift ix
                          r = img3d ! lift (Z :. h :. w :. constant 0) :: Exp Word8
                          g = img3d ! lift (Z :. h :. w :. constant 1) :: Exp Word8
                          b = img3d ! lift (Z :. h :. w :. constant 2) :: Exp Word8
                      in lift (r,g,b,constant 255))
```

This produces:

![out-with-green](https://cloud.githubusercontent.com/assets/800982/11165637/8626627c-8b0c-11e5-910e-04e5c5c6dcda.png)

Images in Matlab and in OpenCV are indexed (0,0) at the top left of the image, see:
http://uk.mathworks.com/help/images/image-coordinate-systems.html
http://stackoverflow.com/a/25644503/1526266

It's probably reasonable then for an accelerate-io user to assume that when they are constructing an accelerate array for accelerate-io to write to a BMP file, they define their array values in row-major-order, starting from the top left. Otherwise, users using cameras to 1) capture a frame, 2) process the image with accelerate and 3) write the result to a BMP file, will have to reorder every frame before step 3,  which would be a performance bottleneck. See the link to the dc1394 firewire mailing discussion above, and here's an example of user code doing so:
https://github.com/robstewart57/firewire-image-io/blob/master/src/Data/Array/Accelerate/IO/Firewire.hs#L51

Here's a blog post about such a scenario (the reordering is hidden inside the `formatFrame` function in the `withFirewireCamera` example): http://www.macs.hw.ac.uk/~rs46/posts/2015-11-06-firewire-gpu.html

**Comment by robstewart57** [comment]
Just to bring the relevant reply from Damien Douxchamps about the dc1394 firewire camera library:

>> On Tue, 2015-11-10 at 11:23 +0000, Rob Stewart wrote:
>> Take this example RGB image, which is
>> 3 pixels in width, 2 pixels in height:
>> 
>> (1,1,1) (4,4,4) (5,6,7)
>> (9,9,9) (8,7,6) (7,7,7)
>> 
>> Will the *image pointer point to:
>> 
>> [1,1,1,4,4,4,5,6,7,9,9,9,8,7,6,7,7,7]
>
> This is the correct order. The data is always sent row by row,
> upper-left corner first, lower-right corner last.

**Comment by tmcdonell** [comment]
okay, thanks for following up. I have some deadlines over the next week but will have a look if I can. I have a suspicion that this is happening in the underlying `bmp` library we're using, but I haven't checked yet.

**Comment by robstewart57** [comment]
That said, I've just taken a look at the BMP file structure definition, see: https://en.wikipedia.org/wiki/BMP_file_format#Pixel_array_.28bitmap_data.29

> The pixel array is a block of 32-bit DWORDs, that describes the image pixel by pixel. Normally pixels are stored "upside-down" with respect to normal image raster scan order, starting in the lower left corner, going from left to right, and then row by row from the bottom to the top of the image.

The BMP library then appears to be doing the right thing.

The `writeImageToBMP` and `readImageFromBMP` in accelerate-io compose nicely. Defining an accelerate array by hand with `fromList` or from a camera, does not compose nicely with `writeImageToBMP`. Perhaps then a utility function could be added to accelerate-io to flip the row indexing on a 2D array, to be used before `writeImageToBMP`. I'd be happy to submit a pull request, but I need to know: which accelerate function should be used to reverse the row wise index of a 2D array, without copying. E.g.

Re-indexing:

```
  0 1 2
-|------->
0|
1|
2|
 v
``` 

```
  0 1 2
-|------->
2|
1|
0|
 v
```

Without copying.

**Comment by tmcdonell** [comment]
So one question I want to know is how everybody (@mchakravarty, @robeverest, @rrnewton) tends to think of the data layout in a 2D array, and how other systems (e.g. matlab, numpy) do this as well. Should we prefer raster order, with `(0,0)` at the top left:

```
   0  1  2
  +------>
0 |
1 |
2 |
  v
```

(which you may be suggesting?)

Or with `(0,0)` at the bottom left:

```
  ^
2 |
1 |
0 |
   +------>
   0  1  2
```

In which case `fromList` and `writeImageToBMP` are doing the right thing.

As a test, the latter appears to be what repa/gloss also appear to be doing. The following gives the image with the green box in the bottom left corner.

```haskell
import Data.Array.Repa                              as R
import Graphics.Gloss.Raster.Array

img :: Array D DIM2 Color
img =
  let blue      = (0,46,184)
      red       = (184,0,46)
      green     = (46,184,0)
      imageData = [ green, red, blue, red, blue, red ]
      imgArr    = R.map (\(r,g,b) -> rgb8w r g b)
                $ R.fromListUnboxed (Z :. 2 :. 3) imageData
  in
  imgArr

main :: IO ()
main =
  animateArray
    (InWindow "Test" (300,200) (10,10))
    (100,100)
    (const img)
```

Either way, we should really make this convention explicit in the documentation somewhere.

By the way, to flip the image vertically in Accelerate:

```haskell
flipV
    :: Elt a
    => Acc (Array DIM2 a)
    -> Acc (Array DIM2 a)
flipV arr =
  let Z :. h :. _ = unlift (shape arr)          :: Z :. Exp Int :. Exp Int
      p ix        = let Z :. y :. x = unlift ix
                    in  index2 (h - y - 1) x
  in
  backpermute (shape arr) p arr
```

Although, it may be more efficient to do that while reading/writing the BMP file.

**Comment by tmcdonell** [comment]
Actually `flipV` and `flipH` seem reasonable to add to the prelude. They go well with the existing `transpose`, `reverse` etc. helper functions for 1D and 2D arrays.

**Comment by cpdurham** [comment]
Just wanted to add, no fuss, but i've been working with a machine vision camera that adheres to a bunch of machine vision software standards like genicam. writeImageToBMP definitely flips the image vertically compared to the software packaged with the camera. When i take the raw data and put it into JuicyPixels, it matches the orientation of the vision software.

**Comment by tmcdonell** [comment]
I finally circled round to have a look at this again, and I think it should be fixed now...
