### ISSUE TITLE
Missing class methods

### ISSUE THREAD

**Issue by vladfi1** [AccelerateHS/accelerate#299]
It looks like the Floating instance for Exp is missing a few methods, namely sinh, cosh, and tanh. These should be really easy to add.

**Comment by tmcdonell** [comment]
Yes! These exist in HEAD already for the [main package](https://github.com/AccelerateHS/accelerate/blob/master/Data/Array/Accelerate/AST.hs#L1024) as well as the [various](https://github.com/AccelerateHS/accelerate-cuda/blob/master/Data/Array/Accelerate/CUDA/CodeGen/Arithmetic.hs
) [backends](https://github.com/AccelerateHS/accelerate-llvm/blob/master/accelerate-llvm/Data/Array/Accelerate/LLVM/CodeGen/Arithmetic.hs#L203). They should be in the next (major) release, once I find some time to do that...
