### ISSUE TITLE
Bug in Cuda backend?

### ISSUE THREAD

**Issue by vladfi1** [AccelerateHS/accelerate#302]
I was going to file an issue about bad performance when this happened:
```
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/Array/Remote/Table.hs:148:41: (lookup): dead weak pair: 139909651213792
```
Profiling a similar program reveals that 60% of the time is spent in GC, and gives the following report:
```
	Wed Feb  3 19:37 2016 Time and Allocation Profiling Report  (Final)

	   profile-cuda +RTS -p -s -h -RTS

	total time  =        2.20 secs   (2197 ticks @ 1000 us, 1 processor)
	total alloc = 1,625,912,888 bytes  (excludes profiling overheads)

COST CENTRE         MODULE                                     %time %alloc

compile.code        Data.Array.Accelerate.CUDA.Compile          10.1   23.3
ppr                 Data.Array.Accelerate.CUDA.CodeGen.Base      9.3    8.3
hashWithSalt        Data.Array.Accelerate.CUDA.CodeGen.Monad     2.5    4.5
==                  Data.Array.Accelerate.Trafo.Sharing          2.4    3.8
blockSize           Data.Array.Accelerate.CUDA.Analysis.Launch   2.3    4.4
liftIO              Data.Array.Accelerate.CUDA.State             2.0    0.3
lookup/go           Data.HashTable.ST.Basic                      1.7    0.1
==                  Data.Array.Accelerate.Trafo.Sharing          1.7    2.5
create              Data.Array.Accelerate.CUDA.Context           1.6    0.0
delete'.go          Data.HashTable.ST.Basic                      1.6    0.3
readArray           Data.HashTable.Internal.IntArray             1.3    1.7
codegenOpenExp.cvtE Data.Array.Accelerate.CUDA.CodeGen           1.2    1.1
streaming           Data.Array.Accelerate.CUDA.Execute           1.2    0.5
lookup              Data.HashTable.ST.Basic                      1.0    0.5
insert              Data.HashTable.ST.Basic                      1.0    0.4
fmap                Data.Array.Accelerate.CUDA.State             1.0    1.0
matchStableAcc      Data.Array.Accelerate.Trafo.Sharing          0.9    1.1
compile.key         Data.Array.Accelerate.CUDA.Compile           0.6    3.0
usesOfPreAcc        Data.Array.Accelerate.Trafo.Shrink           0.3    1.1
```
I'm probably doing something very wrong :(

**Comment by tmcdonell** [comment]
Is this with accelerate-cuda-0.15.* from Hackage? If so, can you please try again with the github version and let us know how that goes. @robeverest made a lot of improvements to memory management recently so that might be fixed already (and if not, we definitely want to know!)

As for why it spends so much time in GC, if you can share your program with us (or a smaller/example version) we might be able to help there too, otherwise it is difficult to say.

**Comment by vladfi1** [comment]
The crash was actually with the latest accelerate from github (I needed the Floating methods I mentioned in another post). The programs that I'm using to run these are pretty large and complicated. Essentially they repeatedly execute an IO action which does lots of matrix operations backed by accelerate arrays.

**Comment by vladfi1** [comment]
Here's a short example that's similar in spirit to what I'm doing:
```
module Main where

import Data.IORef
import Data.Array.Accelerate
import Data.Array.Accelerate.CUDA

import Prelude hiding (zipWith, replicate, (++), sum, map)

type Matrix e = Array DIM2 e

dot :: (Elt a, IsNum a) => Acc (Vector a) -> Acc (Vector a) -> Acc (Scalar a)
dot xs ys = fold1 (+) (zipWith (*) xs ys)

norm xs = map sqrt (dot xs xs)

mult
  :: (Elt a, IsNum a) =>
     Acc (Matrix a) -> Acc (Vector a) -> Acc (Vector a)

mult m v = fold1 (+) (zipWith (*) m vs)
  where
    n = indexHead . indexTail $ shape m
    vs = replicate (lift $ Z :. n :. All) v

main = do
  let n = 1000 :: Int
  
  let m = fill (constant $ Z :. n :. n) (constant (1 :: Float))
  vRef <- newIORef $ fill (constant $ Z :. n) (constant 1)
  
  let iterate = do
      v <- readIORef vRef
      let mv = mult m v
          vv = norm v
          v' = map (/ the vv) mv
      writeIORef vRef v'
  
  traverse (const iterate) [1..100]
  
  v <- readIORef vRef
  print $ run (norm v)
```

If I compile this into an executable and run it I get the crash. When I loaded it up with ghci/cabal repl and run main, it crashed the very first time, but then ran smoothly on each subsequent iteration.

**Comment by vladfi1** [comment]
Increasing the iterations to 1000 gets it to crash every time. Are there any tweaks I can make to try to get this to work?

**Comment by tmcdonell** [comment]
Thanks for the test case, I was able to reproduce this on my machine.

I guess your real program is not like this, but if you are iterating the same operation then you could try using `awhile` to do the iteration in Accelerate, rather than unfolding a single large pipeline to execute at the end.

```haskell
      i :: Acc (Scalar Int)
      i  = unit (constant 0)

      loop = A.asnd
           $ awhile (\iv -> A.map (A.<* 100) (A.afst iv))
                    (\iv -> let v' = iterate (A.asnd iv)
                                i' = A.map (+1) (A.afst iv)
                            in
                            lift (i',v'))
                    (lift (i,v0))
```

You might also try storing the result (after `run`) into your `IORef`. The approach you have taken is really the right way to go (minimises data transfers, for example), but as a work around this should at least keep you moving forward while we track down this bug...

**Comment by vladfi1** [comment]
Unfortunately I can't express my computation as a pure Acc -> Acc function, since I'm doing a big graph traversal that relies on IORefs. What I'd like to do is perhaps force the computation to be evaluated after each dot/mult or something like that. Also, and forgive me if this doesn't make sense, but could the dot/mult operations be cached to avoid recompilation? The profiling output suggests to me that a lot of the time is being spent compiling kernels.

**Comment by tmcdonell** [comment]
Okay, so looks like my second suggestion might help you, where instead of `writeIORef vRef v'` you first force the computation ala `writeIORef vRef (run v')`.

The compiled kernels will be cached, but see the notes in the docs to make sure you are benefiting from this: https://github.com/AccelerateHS/accelerate-cuda/blob/master/Data/Array/Accelerate/CUDA.hs#L41

**Comment by vladfi1** [comment]
I'm confused. Calling run will change the type stored in the IORef - are you saying I should then call use when doing the linear algebra? That seems like it would needlessly transfer memory back and forth.

**Comment by vladfi1** [comment]
Also, I'm not sure how relevant this is, but here's the result of profiling the interpreter backend:
```
	Wed Feb  3 16:04 2016 Time and Allocation Profiling Report  (Final)

	   profile-accelerate +RTS -p -s -h -RTS

	total time  =        0.57 secs   (571 ticks @ 1000 us, 1 processor)
	total alloc = 545,466,920 bytes  (excludes profiling overheads)

COST CENTRE                              MODULE                                   %time %alloc

==                                       Data.Array.Accelerate.Trafo.Sharing        8.8   11.2
==                                       Data.Array.Accelerate.Trafo.Sharing        4.4    7.6
matchStableAcc                           Data.Array.Accelerate.Trafo.Sharing        2.8    3.3
determineScopesSharingAcc.scopesAcc      Data.Array.Accelerate.Trafo.Sharing        2.3    0.5
matchStableExp                           Data.Array.Accelerate.Trafo.Sharing        2.3    1.8
makeOccMapSharingAcc.traverseAcc.\       Data.Array.Accelerate.Trafo.Sharing        2.1    2.2
simplifyOpenExp.cvtE                     Data.Array.Accelerate.Trafo.Simplify       1.8    1.7
simplifyOpenExp.indexCons                Data.Array.Accelerate.Trafo.Simplify       1.8    1.2
freezeOccMap                             Data.Array.Accelerate.Trafo.Sharing        1.8    2.8
lookupWithASTName                        Data.Array.Accelerate.Trafo.Sharing        1.6    0.2
usesOfPreAcc.countP                      Data.Array.Accelerate.Trafo.Shrink         1.4    0.2
usesOfPreAcc.countE                      Data.Array.Accelerate.Trafo.Shrink         1.4    0.2
delete'                                  Data.HashTable.ST.Basic                    1.2    0.4
writeLoad                                Data.HashTable.ST.Basic                    1.2    1.2
rebuildA                                 Data.Array.Accelerate.Trafo.Substitution   1.2    1.5
growTable/rehash                         Data.HashTable.ST.Basic                    1.1    0.2
lookup/go                                Data.HashTable.ST.Basic                    1.1    0.0
lookup                                   Data.HashTable.ST.Basic                    1.1    0.7
delete'.go                               Data.HashTable.ST.Basic                    1.1    0.4
rebuildE                                 Data.Array.Accelerate.Trafo.Substitution   1.1    2.1
rebuildEA                                Data.Array.Accelerate.Trafo.Substitution   1.1    1.4
makeOccMapSharingExp.travE.\.reconstruct Data.Array.Accelerate.Trafo.Sharing        1.1    1.0
determineScopesSharingExp.scopesExp      Data.Array.Accelerate.Trafo.Sharing        1.1    0.7
shrinkExp.shrinkE                        Data.Array.Accelerate.Trafo.Shrink         0.9    2.3
readLoad                                 Data.HashTable.ST.Basic                    0.7    1.0
readArray                                Data.HashTable.Internal.IntArray           0.5    3.3
convertSharingExp                        Data.Array.Accelerate.Trafo.Sharing        0.2    1.0
readDelLoad                              Data.HashTable.ST.Basic                    0.0    1.0
usesOfPreAcc                             Data.Array.Accelerate.Trafo.Shrink         0.0    3.4
```
This sounds to me like a lot of the time is being spent trying to cache kernels - specifically, comparing to see if various kernels have been seen before. It seems like there should be some way to tell accelerate to compile a kernel once, and then use some handle to refer to the kernel in the future when applying it. Again, I have only basic knowledge of how this all works, so forgive me if my comments don't make sense.

**Comment by tmcdonell** [comment]
> I'm confused. Calling run will change the type stored in the IORef - are you saying I should then call use when doing the linear algebra? That seems like it would needlessly transfer memory back and forth.

No you are absolutely right, this is a bad idea. I only proposed it as a _temporary_ work around so that you can continue with your project while we hunt down the problem. Sorry that I wasn't clear enough.

@robeverest do you have any spare cycles at the moment?

**Comment by robeverest** [comment]
I should have a bit of time later in the week. This sort of error hasn't cropped up in a while so I'm a little surprised, but I'll try to figure out what it is. @tmcdonell @vladfi1 I assume you're both using GHC 7.10?

**Comment by robeverest** [comment]
I took a look at it and think I've narrowed it down. @vladfi1 This patch offers a temporary fix that seems to work. At least for me it did.

```diff
diff --git a/Data/Array/Accelerate/Array/Remote/Table.hs b/Data/Array/Accelerate/Array/Remote/Table.hs
index af93fba..4b8d23f 100644
--- a/Data/Array/Accelerate/Array/Remote/Table.hs
+++ b/Data/Array/Accelerate/Array/Remote/Table.hs
@@ -38,13 +38,13 @@ module Data.Array.Accelerate.Array.Remote.Table (
 
 import Control.Concurrent                                       ( yield )
 import Control.Concurrent.MVar                                  ( MVar, newMVar, withMVar, modifyMVar_, mkWeakMVar )
-import Control.Concurrent.Unique                                ( Unique )
 import Control.Monad.IO.Class                                   ( MonadIO, liftIO )
 import Data.Functor
 import Data.Hashable                                            ( hash )
 import Data.Maybe                                               ( isJust )
 import Data.Proxy
 import Data.Typeable                                            ( Typeable, gcast )
+import Data.Unique
 import Foreign.Storable                                         ( sizeOf )
 import System.Mem                                               ( performGC )
 import System.Mem.Weak                                          ( Weak, deRefWeak )
@@ -329,7 +329,7 @@ makeStableArray
     :: (MonadIO m, Typeable a, Typeable e, ArrayPtrs a ~ Ptr e, ArrayElt a)
     => ArrayData a
     -> m StableArray
-makeStableArray !ad = return $! hash (id arrayElt ad)
+makeStableArray !ad = return $! hashUnique (id arrayElt ad)
   where
     id :: ArrayEltR e -> ArrayData e -> Unique
     id ArrayEltRint     (AD_Int ua)     = uniqueArrayId ua
diff --git a/Data/Array/Accelerate/Array/Unique.hs b/Data/Array/Accelerate/Array/Unique.hs
index 007e6e2..83622b4 100644
--- a/Data/Array/Accelerate/Array/Unique.hs
+++ b/Data/Array/Accelerate/Array/Unique.hs
@@ -21,7 +21,7 @@ module Data.Array.Accelerate.Array.Unique (
 
 -- library
 import Control.Applicative
-import Control.Concurrent.Unique
+import Data.Unique
 import Foreign.Ptr
 import Foreign.ForeignPtr
 import Foreign.ForeignPtr.Unsafe
```

@tmcdonell It seems it's a problem with our use of `Control.Concurrent.Unique` and how it does hashing.  I need to dig into it a bit further though. More to follow...

**Comment by robeverest** [comment]
Yup, it seems the problem was our use of `Control.Concurrent.Unique`. 

@vladfi1 If you try the latest version you should find your no longer getting those errors. Let us know if it still happens in your larger program.

@tmcdonell While you changing my simple `Int` counter for unique arrays to an actual unique value was very much a Good Thing, we can't rely on hashes of unique values not to collide. This may make it a bit tricky if we want to use `IntMap`s instead of hash tables later on, as we would have to deal with collisions ourselves.

**Comment by tmcdonell** [comment]
I have actually been slightly suspicious about this unique library, but I do really like [the idea] that it is fully concurrent. We should at least let @ekmett know and file a ticket over there.

**Comment by vladfi1** [comment]
Thanks @robeverest for figuring this one out! The program does indeed run now, the only issue is the poor performance. I suppose I should file another issue for that.

**Comment by tmcdonell** [comment]
@vladfi1 Yes, this ticket has gotten pretty long, so probably best to open a new one where we can focus on the performance issue.

**Comment by tmcdonell** [comment]
@robeverest I have some questions over on the patch itself for you...
