### ISSUE TITLE
An indexed map over arrays?

### ISSUE THREAD

**Issue by robstewart57** [AccelerateHS/accelerate#304]
In the vector library there's this useful function:

    imap :: (Int -> a -> b) -> Vector a -> Vector b

And in Data.Map there's this similar function:

    mapWithKey :: (k -> a -> b) -> Map k a -> Map k b

I'm looking for something similar in the accelerate library, something like:

    imap :: (Shape ix, Elt a, Elt b) => (Exp ix -> Exp a -> Exp b) -> Acc (Array ix a) -> Acc (Array ix b)

That is, a map that provides your function not only the element at a position, but also the index at that position? Is there such a function in the accelerate library? What would the implementation of such a function look like?

**Comment by tmcdonell** [comment]
Like this?

```Haskell
imap :: (Shape ix, Elt a, Elt b)
     => (Exp ix -> Exp a -> Exp b)
     -> Acc (Array ix a)
     -> Acc (Array ix b)
imap f xs = A.zipWith f (A.generate (shape xs) id) xs
```

**Comment by robstewart57** [comment]
@tmcdonell Thanks very much!

> Like this?

Exactly like that :+1:

**Comment by robstewart57** [comment]
@tmcdonell There's a use case where it might be helpful to have something very similar:

```haskell
imapL :: (Shape ix, Elt a, Elt b) => (Exp Int -> Exp a -> Exp b) -> Acc (Array ix a) -> Acc (Array ix b)
```

So, the index is `Exp Int` rather than `Exp ix`, where "L" indicates that this is a linear index, rather than a shape index. They'll be a better name for this primitive rather than `imapL`, I'm sure.

The use case is this:

```haskell
imapL (\idx elem -> myArray !! (idx-1) + elem + myArray !! (idx+1) / 4 ) myArray
```

I realise that this is a stencil. and accelerate has special support for stencils. In my use case above, I don't care that my slide my stencil computation over one row to the next (in a 2D array) at the right most elements -- I don't need clamping support or wrap-around support at the edges.

Thoughts on an `imap` derivative based on linear indexing, rather than shape indexing?

**Comment by robeverest** [comment]
So `imapL` as you call it, can be defined in terms of imap like so:
```haskell
imapL f a = imap (f . toIndex (shape a)) a
```

While I can see this is useful, I'm not sure whether this should be added to the prelude. If it were, we'd really have to ask ourselves why not have linear versions of all the other index based operations as well?
