### ISSUE TITLE
llvm-native "forkOS_entry: interrupted" and "no default instance yet" errors

### ISSUE THREAD

**Issue by robstewart57** [AccelerateHS/accelerate#307]
I'm running three programs that uses `Data.Array.Accelerate.LLVM.Native.run`. I am getting a runtime error:

    forkOS_entry: interrupted

These are the programs:

1. https://github.com/robstewart57/END-dsl-implementations/blob/master/haskell/small-image-processing-dsl/app/deep-accelerate/prog1.hs
2. https://github.com/robstewart57/END-dsl-implementations/blob/master/haskell/small-image-processing-dsl/app/deep-accelerate/prog3.hs
3. https://github.com/robstewart57/END-dsl-implementations/blob/master/haskell/small-image-processing-dsl/app/deep-accelerate/prog4.hs

For two more programs I'm seeing a different error:

```
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/LLVM/CodeGen/Skeleton.hs:187:19: (stencil1): no default instance yet
```

Those programs are

1. https://github.com/robstewart57/END-dsl-implementations/blob/master/haskell/small-image-processing-dsl/app/deep-accelerate/prog2.hs
2. https://github.com/robstewart57/END-dsl-implementations/blob/master/haskell/small-image-processing-dsl/app/deep-accelerate/prog5.hs

All these programs use a library, whic itself uses Accelerate functions: https://github.com/robstewart57/END-dsl-implementations/blob/master/haskell/small-image-processing-dsl/src/DeepAccelerate.hs

What is the remedy for the two errors I am experiencing?

**Comment by mikusp** [comment]
It seems that `accelerate-llvm` does not support stencil operations yet. See https://github.com/AccelerateHS/accelerate-llvm#current-status

**Comment by robstewart57** [comment]
@mikusp Ah, thanks for the heads up.

**Comment by tmcdonell** [comment]
yes, @mikusp is correct, sadly. The `forkOS_entry` error is just a byproduct of failing to terminate gracefully after the "no default instance yet" error.

**Comment by tmcdonell** [comment]
I added basic support for stencils. Expect performance to be terrible, as it is doing the dumbest thing possible (so, I'm not going to mark this as done on the status page yet), but it should at least work now so let me know if you run into problems.

**Comment by robstewart57** [comment]
@tmcdonell Hero! I was just about to run timing measurements.
