### ISSUE TITLE
Incompatible change in CUDAForeignAcc between 0.15 and 0.15.1

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#308]
Henning Thielemann posted [on the mailing list](https://groups.google.com/forum/#!topic/accelerate-haskell/_X2eKLswbyI):

> I just tried to compile old code and ran into the following 
> incompatibility: 
> 
> In 0.15.0.0 we have: 
>    CUDAForeignAcc :: String -> (as -> CIO bs) -> CUDAForeignAcc as bs 
> 
> Whereas in 0.15.1.0 we have:
>    CUDAForeignAcc :: String -> (Stream -> as -> CIO bs) -> CUDAForeignAcc as bs 
> 
> Unfortunately this is an (incompatible) change at a minor version bump. 
> This makes the version bounds invalid that I used in my dependent 
> packages. :-( Could you re-upload 0.15.1 as 0.16 and deprecate 0.15.1 at 
> Hackage?

**Comment by kathawala** [comment]
Does anyone know how the CUDA foreign functions are supposed to be written to accommodate a "Stream"? I see this example (https://github.com/alpmestan/accelerate-blas/blob/586f15f68db3e5ce3df93b376c2600e52cadf6ed/src/Data/Array/Accelerate/BLAS/Internal/Dot.hs) which imports a foreign function using BL as the foreign library to import from. But this relies on the 0.15.0.0 version of "CUDAForeignAcc".

How would one write a version of those linked functions to accommodate the 0.15.1.0 version of "CUDAForeignAcc"?

**Comment by robeverest** [comment]
If you're using cublas, like the example you linked does, you would need to call `setStream` from the cublas library in the foreign function before calling the function that actually does the work. In the above example this would be `BL.sdot` or `BL.ddot`. So, for example, you could change 

```haskell
execute h n v1ptr v2ptr optr
  = BL.sdot h n v1ptr 1 v2ptr 1 optr
```
to
```haskell
execute h n v1ptr v2ptr optr
  = BL.setStream h stream >> BL.sdot h n v1ptr 1 v2ptr 1 optr
```

**Comment by kathawala** [comment]
@robeverest 

Thanks so much for the reply! While I have your ear, we've been having other issues with cublas and had to write some FFI bindings ourselves. In particular, calling `create` through cublas consistently gives "CUBLAS Exception: library not initialised", while writing the one-line FFI binding for `cublasCreate` ourselves doesn't have that problem. Any ideas? We're using CUDA6.5 and the most recent versions of other libraries, on OS X 10.10.

**Comment by robeverest** [comment]
I'm afraid I actually have no idea why that's happening. I've not used the cublas bindings myself. I took brief a look at them and I can't see anything wrong, certainly nothing that would cause the error you're seeing. Are you getting that exception when calling `create` itself to create a handle or when calling subsequent functions that take the handle?

**Comment by tmcdonell** [comment]
Finally, I have remembered to do this.
https://hackage.haskell.org/package/accelerate-cuda-0.16.0.0
