### ISSUE TITLE
Wrong fromList behavior on pairs

### ISSUE THREAD

**Issue by matt-noonan** [AccelerateHS/accelerate#309]
fromList in accelerate-2.0.0.0 seems to have incorrect behavior when applied to lists of pairs. With the following Main.hs:

    module Main where

    import Data.Array.Accelerate hiding (length, (++))

    main :: IO ()
    main = do
      let zs  = [(1,2)] :: [(Int,Int)]
          vec = fromList (Z :. length zs) zs
      putStrLn $ show zs ++ "  =>  " ++ show vet

at 2098038b9316e2a5d9bed54c61bf4582469d9e06, the output is `[(1,2)]  =>  Array (Z :. 1) [(2,2)]`.  accelerate-0.15.1.0 gives the expected output `[(1,2)]  =>  Array (Z :. 1) [(1,2)]` instead.

A minimal working example is attached, built on OS X 10.11.3 with `stack --resolver=lts-3.15`.
[mwe.zip](https://github.com/AccelerateHS/accelerate/files/146000/mwe.zip)

**Comment by robeverest** [comment]
Thanks for the thorough report. 

The problem was in lazy allocation. I've pushed a fix that makes the example you gave work as it should. Feel free to reopen the issue if it doesn't work for you.
