### ISSUE TITLE
CUDA backend and multithreads

### ISSUE THREAD

**Issue by xinhuazhang** [AccelerateHS/accelerate#311]
Hi,

I am wondering if I could use CUDA backend and say, +RTS -N8 at the same time? I do notice that if I use both of them, an error could happen, not every time though. And there is no error if I only use a single CPU core. Does the LLVM backend aim for this situation?

Thanks

**Comment by tmcdonell** [comment]
I have been using the LLVM backend with multiple RTS threads without issue so far. I often use both the CPU (with +RTS -N) and GPU backends together in the same program.

**Comment by xinhuazhang** [comment]
I have not been able to try LLVM backend because I have trouble installing llvm-general package with shared-llvm flag on. 

Now I have figured it out. I installed LLVM from source codes using CMAKE. In this case, it won't create shared libraries such as libLLVM-3.5.2.so and libLLVM-3.5.so. Then Cabal will report an error: Missing C library: LLVM-3.5.2svn. Using ./configure solves this problem.

**Comment by xinhuazhang** [comment]
@tmcdonell I have trouble installing accelerate-llvm. I tried to install it via Cabal. But it said that it depends on accelerate == 2.0.* . Is it a developmental version?

**Comment by tmcdonell** [comment]
Yes, accelerate-llvm is still in development, so you'll need to build it against the development version of accelerate as well.

If you use stack, it will pull in the necessary dependencies from github for you.

**Comment by xinhuazhang** [comment]
When you said LLVM backend, did you mean ghc -fllvm or accelerate-llvm?

**Comment by tmcdonell** [comment]
The `accelerate-llvm` package (i.e. the LLVM backend for _accelerate_, not for GHC)
