### ISSUE TITLE
Cyclic expression in Exp

### ISSUE THREAD

**Issue by Semoire** [AccelerateHS/accelerate#312]
Hello, I don't know if this is a correct place to post but I saw other similar issues here so I thought I'd take a shot. Close this if it's wrong.
I am doing an implementation of GDBSCAN using accelerate and I am hitting a wall with this Cyclic expressions.

The code is
```
        classifyPoints :: A.Acc (A.Array A.DIM2 DBScanPoint) -> A.Acc (A.Vector (Int, Bool))
        classifyPoints graph = A.generate (A.shape points) (\ ix -> let (A.Z A.:. i) = A.unlift ix :: A.Z A.:. A.Exp Int
                                                                        adjacency = A.slice graph (A.lift $ A.Z A.:. i A.:. A.All)
                                                                        core = (A.length $ (A.filter (\ x -> (A.fst x) A./=* 0) $ adjacency))
                                                                        isCore = A.lift (A.length $ adjacency, A.constant True)
                                                                        notCore = A.lift (A.length $ adjacency, A.constant False)
                                                                     in core A.>* minPts A.? (isCore, notCore))
```
and I believe the problem is in the slice and filter lines. Basically I'm trying to sum along each "row" of an nxn adjacency matrix to find if it's a core point. However, my "idea" on how to do it seems to cause massively nested parallelism when I think about it after the fact. Is there any functions that either 1. Do what I want in a different way or 2. Allow me to remove the nested parallelism with the same process?

**Comment by tmcdonell** [comment]
Hm, the tricky thing here is the filter, but since you appear to just be counting the number of elements which pass the predicate, you can still do it by remembering that reductions are rank-polymorphic, which allows us to instead of slicing out a row on each row individually, process all rows at once:

```haskell
classifyPoints :: Acc (Array DIM2 Int) -> Acc (Vector (Int,Bool))
classifyPoints graph =
  let
      core    = A.fold (+) 0 $ A.map (\x -> x A.==* 0 ? ( 0, 1 )) graph
      ans     = A.map (\adj -> adj A.>* minPts
                                 ? ( lift (adj, constant True)
                                   , lift (adj, constant False)
                                   )) core
  in
  ans
```

I can't tell from just the snippet, but hopefully that same idea works in your full program...

**Comment by Semoire** [comment]
That seemed to work perfect. I tried something similar before but I just realized that the type of fold and sfoldl were vastly different. Just so I understand, and if you read this at all, fold, in being rank polymorphic, simply reduces the dimensions of the array by one by passing the passed function over it?

Sorry for the off topic post.

**Comment by tmcdonell** [comment]
Not a problem, glad I could help! Good luck and feel free to ask again if you have any more questions.
