### ISSUE TITLE
Getting around nested parallelism in a calculating the median of a stencil

### ISSUE THREAD

**Issue by Semoire** [AccelerateHS/accelerate#313]
Hello,
I am working on a NxN median filter for a image processing project and I am having trouble on how to find the median of a stencil. Is the best way to do by a series of ? switchs? I can't think of a way to sort each of the stencils without either pushing them to the CPU which would be horribly inefficient or hitting nested parallelism. As the NxN stencils are fixed at compile time, I could always write a program to generate the hideous chain of ?s but I would like to know if there is a more practical and idiomatic way.

This is actually a more general question as well. What is the best way to do sequential algorithms on each thread within a parallel function that doesn't involve sfoldl? I know you can map an sfold but is there another part of the API that I am missing that forces each thread to sequentially do something to get around nested parallelism.

Thank you

**Comment by robeverest** [comment]
As you've closed this, you may have already found a solution, but to answer your question, there is currently no way to force something to be done sequentially. To solve the problem of finding the median of a stencil, there are a couple of techniques that might work.

One is, as you suggested, to use metaprogramming to generate a function using lots of `?` that selects the median from a stencil of a known size. However, my inclination is that this might not be as performant as you'd like.

The other would be to use `while` to perform the selection naively; i.e first find the smallest value and how often it occurs, then the second smallest, then the 3rd, all the way up to k/2. For small stencils I believe this could work.
