### ISSUE TITLE
EKG makes it impossible to run two copies of an accelerate-examples binary

### ISSUE THREAD

**Issue by rrnewton** [AccelerateHS/accelerate#315]
I wanted to run two copies of the raytracer to do a side-by-side on the interpreter vs cuda.  But I get this error:

```
accelerate-ray: bind: resource busy (Address already in use)
```

I assume that's from ekg?  Actually that error stops me from even running `accelerate-ray -h` to see the help ;-).

Perhaps these errors should be caught and turned into a warning.  Most users probably don't care if EKG comes up or not.

**Comment by tmcdonell** [comment]
Seems reasonable. Failing to start EKG shouldn't be fatal.

Since you don't want it anyway, just `cabal configure -f-ekg`.
