### ISSUE TITLE
bug in Accelerate.Interpreter

### ISSUE THREAD

**Issue by proposition** [AccelerateHS/accelerate#316]
Hi, I've got that mistake at my terminal

```haskell
*** Exception:
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/Trafo/Sharing.hs:461:9: (convertSharingExp): inconsistent valuation @ shared 'Exp' tree with stable name 221932;
  env' = [221934]
```
So, I decided to follow by direction!

**Comment by robeverest** [comment]
Can you post the code where this problem was occurring?

Despite what the message says, this is not necessarily an an internal error as it can sometimes occur due to nested parallelism, which Accelerate doesn't support.

**Comment by proposition** [comment]
That message appear when send ```I.run $ forallpoint f1 f2```
So, that is my code:

```haskell
{-# LANGUAGE TypeOperators #-}
{-# Language ScopedTypeVariables #-}
{-# Language FlexibleContexts #-}

import Data.Array.Accelerate as A
import Data.Array.Accelerate.Interpreter as I
--import Data.List

type Point10 = DIM9 :. Int
type Coeffs = Point10 :. Int :. Int :. Int :. Int :. Int :. Int 

--index4 :: Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp DIM4
--index4 i j k l = lift (Z:.i:.j:.k:.l)

index10 :: Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Point10
index10 x0 x1 x2 x3 x4 x5 x6 x7 x8 x9 = lift (Z:.x0:.x1:.x2:.x3:.x4:.x5:.x6:.x7:.x8:.x9)

fromCoeffs sh =
    let
        (Z:.f01:.f02:.f03:.f04:.f05:.f06:.f07:.f08:.f09:.f10:.f11:.f12:.f13:.f14:.f15:.f16) = unlift sh
        a01 = fill (index1 1) f01 :: Acc (Array DIM1 Int)
        a02 = fill (index1 1) f02 :: Acc (Array DIM1 Int)
        a03 = fill (index1 1) f03 :: Acc (Array DIM1 Int)
        a04 = fill (index1 1) f04 :: Acc (Array DIM1 Int)
        a05 = fill (index1 1) f05 :: Acc (Array DIM1 Int)
        a06 = fill (index1 1) f06 :: Acc (Array DIM1 Int)
        a07 = fill (index1 1) f07 :: Acc (Array DIM1 Int)
        a08 = fill (index1 1) f08 :: Acc (Array DIM1 Int)
        a09 = fill (index1 1) f09 :: Acc (Array DIM1 Int)
        a10 = fill (index1 1) f10 :: Acc (Array DIM1 Int)
        a11 = fill (index1 1) f11 :: Acc (Array DIM1 Int)
        a12 = fill (index1 1) f12 :: Acc (Array DIM1 Int)
        a13 = fill (index1 1) f13 :: Acc (Array DIM1 Int)
        a14 = fill (index1 1) f14 :: Acc (Array DIM1 Int)
        a15 = fill (index1 1) f15 :: Acc (Array DIM1 Int)
        a16 = fill (index1 1) f16 :: Acc (Array DIM1 Int)
    in
      a01 A.++ a02 A.++ a03 A.++ a04 A.++ a05 A.++ a06 A.++ a07 A.++ a08 A.++ a09 A.++ a10 A.++ a11 A.++ a12 A.++ a13 A.++ a14 A.++ a15 A.++ a16  

fromPoint10 sh =
    let
        (Z:.f01:.f02:.f03:.f04:.f05:.f06:.f07:.f08:.f09:.f10) = unlift sh
        a01 = fill (index1 1) f01 :: Acc (Array DIM1 Int)
        a02 = fill (index1 1) f02 :: Acc (Array DIM1 Int)
        a03 = fill (index1 1) f03 :: Acc (Array DIM1 Int)
        a04 = fill (index1 1) f04 :: Acc (Array DIM1 Int)
        a05 = fill (index1 1) f05 :: Acc (Array DIM1 Int)
        a06 = fill (index1 1) f06 :: Acc (Array DIM1 Int)
        a07 = fill (index1 1) f07 :: Acc (Array DIM1 Int)
        a08 = fill (index1 1) f08 :: Acc (Array DIM1 Int)
        a09 = fill (index1 1) f09 :: Acc (Array DIM1 Int)
        a10 = fill (index1 1) f10 :: Acc (Array DIM1 Int)
    in
      a01 A.++ a02 A.++ a03 A.++ a04 A.++ a05 A.++ a06 A.++ a07 A.++ a08 A.++ a09 A.++ a10

coeflist = use $ fromList (Z:.30) [0,1,1,1,0,1,1,1,0,0,0,1,1,0,1,0,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,1] :: Acc (Array DIM1 Int)
-- TODO: написать ленточный генератор
pointlist = use $ fromList (Z:.1033) [1..] :: Acc (Array DIM1 Int)

gen0 :: Acc(Array DIM1 Int) -> Exp Int -> Exp Int
gen0 xs i = xs ! index1 i
gencoef = gen0 coeflist
genpoint = gen0 pointlist

-- ! можно ли передавать число (даже типа Exp Int) в функцию generate?
takecoef n = generate (index1 16)
    (\xi ->
        let
            (Z:.i) = unlift xi
            p = i + n
        in
            gencoef p)

takepoint n = generate (index1 10)
    (\xi ->
        let
            (Z:.i) = unlift xi
            p = i + n
        in
            genpoint p)

monoms :: Exp Int -> Exp Int -> Exp Int -> Exp Int -> Acc (Array DIM1 Int)
monoms x y z t =
    let
        a = fill (index1 1) 1 :: Acc (Array DIM1 Int)
        b = a A.++ A.map (* x) a
        c = b A.++ A.map (* y) b
        d = c A.++ A.map (* z) c
    in
        d A.++ A.map (* t) d

calcfunc :: Acc (Array DIM1 Int) -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int
calcfunc coefs x y z t = flip mod 2 $ the $ A.sum $ A.zipWith (*) coefs $ monoms x y z t

onpoint :: Acc (Vector Int) -> Acc (Vector Int) -> Acc (Vector Int) -> Exp Int
onpoint f1 f2 point10 =
    let
        f3 = A.reverse f2
        f4 = A.reverse f1
        x1 = point10 ! index1 0
        x2 = point10 ! index1 1
        x3 = point10 ! index1 2
        x4 = point10 ! index1 3
        x5 = point10 ! index1 4
        x6 = point10 ! index1 5
        x7 = point10 ! index1 6
        x8 = point10 ! index1 7
        x9 = point10 ! index1 8
        x0 = point10 ! index1 9
        -- Left --------------------
        -- 1234
        b1 = calcfunc f1 x1 x2 x3 x4
        b2 = calcfunc f2 x1 x2 x3 x4
        b3 = calcfunc f3 x1 x2 x3 x4
        b4 = calcfunc f4 x1 x2 x3 x4
        -- 1567
        a1 = calcfunc f1 b1 x5 x6 x7
        b5 = calcfunc f2 b1 x5 x6 x7
        b6 = calcfunc f3 b1 x5 x6 x7
        b7 = calcfunc f4 b1 x5 x6 x7
        -- 2589
        a2 = calcfunc f1 b2 b5 x8 x9
        a5 = calcfunc f2 b2 b5 x8 x9
        b8 = calcfunc f3 b2 b5 x8 x9
        b9 = calcfunc f4 b2 b5 x8 x9
        -- 3680
        a3 = calcfunc f1 b3 b6 b8 x0
        a6 = calcfunc f2 b3 b6 b8 x0
        a8 = calcfunc f3 b3 b6 b8 x0
        b0 = calcfunc f4 b3 b6 b8 x0
        -- 4790
        a4 = calcfunc f1 b4 b7 b9 b0
        a7 = calcfunc f2 b4 b7 b9 b0
        a9 = calcfunc f3 b4 b7 b9 b0
        a0 = calcfunc f4 b4 b7 b9 b0
        -- Right -------------------
        -- 4790
        c4 = calcfunc f1 x4 x7 x9 x0
        c7 = calcfunc f2 x4 x7 x9 x0
        c9 = calcfunc f3 x4 x7 x9 x0
        c0 = calcfunc f4 x4 x7 x9 x0
        -- 3680
        c3 = calcfunc f1 x3 x6 x8 c0
        c6 = calcfunc f2 x3 x6 x8 c0
        c8 = calcfunc f3 x3 x6 x8 c0
        e0 = calcfunc f4 x3 x6 x8 c0
        -- 2589
        c2 = calcfunc f1 x2 x5 c8 c9
        c5 = calcfunc f2 x2 x5 c8 c9
        e8 = calcfunc f3 x2 x5 c8 c9
        e9 = calcfunc f4 x2 x5 c8 c9
        -- 1567
        c1 = calcfunc f1 x1 c5 c6 c7
        e5 = calcfunc f2 x1 c5 c6 c7
        e6 = calcfunc f3 x1 c5 c6 c7
        e7 = calcfunc f4 x1 c5 c6 c7
        -- 1234
        e1 = calcfunc f1 c1 c2 c3 c4
        e2 = calcfunc f2 c1 c2 c3 c4
        e3 = calcfunc f3 c1 c2 c3 c4
        e4 = calcfunc f4 c1 c2 c3 c4
    in
        mod (a0 + e0) 2 + mod (a1 + e1) 2 + mod (a2 + e2) 2 + mod (a3 + e3) 2 + mod (a4 + e4) 2 + mod (a5 + e5) 2 + mod (a6 + e6) 2 + mod (a7 + e7) 2 + mod (a8 + e8) 2 + mod (a9 + e9) 2

forallpoint f1 f2 = generate (index1 1024)
    (\ix ->
        let
            (Z:.i) = unlift ix
            point = takepoint i
        in
            onpoint f1 f2 point)

f1 = takecoef 2
f2 = takecoef 4
```

**Comment by tmcdonell** [comment]
The critical problem is probably in `calcfunc`, which takes some scalar values, computes a collective operation `A.sum ...` using them, and then retrieve the result using `the` in order to return a scalar. This is classic nested parallelism.

More generally, a couple of comments:
 - Accelerate has support for up to 15-wide tuples, so you should probably use that rather than the shape syntax `Z` and `(:.)`. These can be nested, and larger sizes can be added easily.
 - I have a feeling that a large part of this module should actually just be at the scalar level. `f1` and `f2` for example are tiny 16-element arrays, far too small to benefit from parallelism.
 - You may be interested in my package, [linear-accelerate](https://github.com/tmcdonell/linear-accelerate) and an example which uses it heavily in [accelerate-lulesh](https://github.com/tmcdonell/accelerate-lulesh/blob/master/src/LULESH.hs). Your `onpoint` function looks suspiciously to me like computing some operation over the corners of a hexahedron...

**Comment by proposition** [comment]
I don't understand what is the problem in function
```haskell
calcfunc coefs x y z t = flip mod 2 $ the $ A.sum $ A.zipWith (*) coefs $ monoms x y z t
```
It works
```
h> I.run $ unit $ calcfunc f0 1 0 1 1
Array (Z) [0]
h> I.run $ unit $ calcfunc f0 1 0 0 1
Array (Z) [0]
h> I.run $ unit $ calcfunc f0 0 0 0 1
Array (Z) [1]
```
The mistake above creates only in function ```forallpoint```. All functions before that work.

I try to solve 4-simplex equation on two colors (0,1) by brute force. For my goals need a generator of binary numbers (or all combinations long k from numbers 0 and 1). I decided that the types very useful,
because I can create all that binary numbers lake shapes. I didn't find functions like ```Exp (Shape) -> Acc (Array)``` but, it's not a problem I've written it.

The code above is only part of the common future function.
General task I couldn't solve because it consists of 2^ (4*16+10) operations. I think it isn't real so, I've chosen part of that big set and its mast consist of 2^ (2*16+10) operations. 

In the future, I want run on all f1, f2 in ```generator shape16```

**Comment by tmcdonell** [comment]
I point to `calcfunc` because, while its type is `Exp -> Exp`, inside it you are actually doing parallel computations in `Acc`. While that works fine by itself, once you call `calcfunc` from another parallel operation like `forallpoint` then you run into trouble. Having `the` within `calcfunc` is what is leading you astray --- it is kind of like hiding an `unsafePerformIO` within a function, tricking you that it is pure when really it was not...

Another example, `forallpoint` calls `takepoint` at each index, but `takepoint` is a parallel function whose operation depends on the scalar input. Slightly more subtle...

Usually the way around this is to start thinking of, instead of do one operation at a time and then map to each element, how can we do all operations as a parallel step.

Also, remember that Accelerate is a metaprogramming language, meaning that you can generate your program. Perhaps this won't work in your full program, but for example, since your `coeflist` is constant, you could implement `calcfunc` like this:

```haskell
monoms :: Exp Int -> Exp Int -> Exp Int -> Exp Int -> [Exp Int]
monoms x y z w = ...

calcfunc :: [Exp Int] -> Exp Int -> Exp Int -> Exp Int -> Exp Int -> Exp Int
calcfunc coefs x y z w =  flip mod 2 $ P.sum (P.zipWith (*) coefs (monoms x y z w))
```

Where `P.sum` and `P.zipWith` are the regular Prelude versions.

Flat data parallelism is, of course, a restrictive programming model, but you can get used to working with it.

**Comment by proposition** [comment]
If the ```monoms``` will return ```[Exp Int]```, will an answer be embedded in GPU or CPU memory? I thought that Accelerate allows GPU memory only contain Acc type or Exp tape. That is my first serious program on Haskell and first work with the GPU, I tried to avoid all another types.

**Comment by tmcdonell** [comment]
Correct, only `Exp` and `Acc` things will ever exist on the GPU.

But, we only actually begin GPU execution after you call `run :: Acc a -> a`. Until then, a function that returns an `Exp a` or `Acc a` is _constructing_ the program that we will execute _later_; i.e. building an abstract syntax tree (AST) which represents our program. But, an AST is just a data structure, and from that point of view, `monoms` returns a list of data structures, and `calcfunc` takes in a list of data structures and a few other bits, and returns a combined data structure. Coming full circle, `run` just turns this data structure into code, compiles, and executes it. This is why we are able to work with a `[Exp Int]`.

NOTE: `[Exp Int]` is very different from `Exp [Int]`: The latter is the one which says we are trying to construct a list of ints `[Int]` _on the GPU_, which is the thing we can not do.

Does that help?

**Comment by proposition** [comment]
Thank you! It was very useful for me. I changed everything in my code.

**Comment by tmcdonell** [comment]
Glad that we could help! Feel free to open a new issue if you have any other questions. Good luck with your program (:
