### ISSUE TITLE
CUDA backend stream out of memory

### ISSUE THREAD

**Issue by XinhuaZhang** [AccelerateHS/accelerate#319]
I have a list of 5000 data. If I use stream to process them, the GPU memory will run out. If I reduce the number of data, then it's OK. This suggests that the GPU memory usage depends on the length of the data. 

Since the stream uses the same CUDA kernel for those data, how can it run out of GPU memory?

**Comment by tmcdonell** [comment]
Is this with the Hackage version or github HEAD?

If you have some sample code you could provide that would help us debug this. I guess this is a problem with not processing the list elements lazily enough, but will be difficult to nail down without a specific test.

**Comment by XinhuaZhang** [comment]
It is accelerate-cuda 0.15.1.1. I will try to make a simple test code.

**Comment by XinhuaZhang** [comment]
@tmcdonell I found what caused the problem. It is because I tried to modified some codes in accelerate-fft, applying 2D fft to a 3D array, that is considering every 2D layer in the 3D array separately. I think this is faster than applying 2D fft to 2D arrays using stream and then concatenating them together.

 I copied several functions in FFT.hs, but I didn't copy the pragma
`{-# RULES
  "interleave/deinterleave" forall sh x. deinterleave sh (interleave x) = x;
  "deinterleave/interleave" forall sh x. interleave (deinterleave sh x) = x
 #-}`
,  `{-# NOINLINE deinterleave #-}` and `{-# NOINLINE interleave #-}`
Sorry, it is my fault.

**Comment by tmcdonell** [comment]
Okay, glad you found the problem! (:
