### ISSUE TITLE
for Mac

### ISSUE THREAD

**Issue by proposition** [AccelerateHS/accelerate#322]
Hello,

I try install accelerate-cuda on my Mac, but I don't sure that it is posible. I've installed CUDA driver and CUDA-7.5.27 for mac. I've run an example "Hello World!" by nvcc. But I can't use the GPU by accelerate in haskell. I've been getting mistakes like this:
```
h> C.run $ listOnPoint 43 43
*** Exception: CUDA Exception: *** Exception: CUDA Exception: *** Exception: CUDA Exception: Segmentation fault: 11

```

I have 
```
> system_profiler SPDisplaysDataType
Graphics/Displays:

    Intel HD Graphics 5000:

      Chipset Model: Intel HD Graphics 5000
      Type: GPU
      Bus: Built-In
      VRAM (Dynamic, Max): 1536 MB
      Vendor: Intel (0x8086)
      Device ID: 0x0a26
      Revision ID: 0x0009
      Displays:
        Color LCD:
          Display Type: LCD
          Resolution: 1440 x 900
          Pixel Depth: 32-Bit Color (ARGB8888)
          Main Display: Yes
          Mirror: Off
          Online: Yes
          Built-In: Yes
```
```
> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Apr_11_13:23:40_CDT_2016
Cuda compilation tools, release 7.5, V7.5.26
```
Please answer me, maybe I can't use GPU or maybe I've done some mistakes when I installed accelerate-cuda?

**Comment by tmcdonell** [comment]
Which example program did you run from the CUDA samples? The system profiler output only lists the Intel graphics card as available, no NVIDIA cards on that list...

**Comment by proposition** [comment]
Intel graphics card doesn't support CUDA? I run that example
https://www.pdc.kth.se/resources/computers/historical-computers/zorn/how-to/how-to-compile-and-run-a-simple-cuda-hello-world

**Comment by tmcdonell** [comment]
Sorry, Intel graphics cards do not support CUDA.

But, you might be interested in our (currently work in progress) Accelerate backend for multicore CPUs [`accelerate-llvm`](https://github.com/AccelerateHS/accelerate-llvm), which will definitely run on your machine.
