### ISSUE TITLE
Accelerate FFI seems to break -ddump(-simpl)?-dot

### ISSUE THREAD

**Issue by niobium0** [AccelerateHS/accelerate#324]
What I got:

*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/Pretty/Graphviz.hs:297:32: (prettyDelayedOpenAcc): expected array variable
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/Pretty/Graphviz.hs:297:32 in accelerate-2.0.0.0-2Jpk3wEius2KBPIV3NxXny:Data.Array.Accelerate.Pretty.Graphviz

**Comment by tmcdonell** [comment]
Oh, hm. Is there a particular program that this occurs with (that you could share), or does it happen with every program you have tried?

**Comment by niobium0** [comment]
Simplest usage of FFI reproduces behavior.
https://gist.github.com/niobium0/b4b0297dca1c378ccd5ab848a82af4cc

**Comment by tmcdonell** [comment]
![aforeign](https://cloud.githubusercontent.com/assets/728113/17622860/4b3e2cda-60e0-11e6-8f4e-20ca623c9bfb.png)

**Comment by tmcdonell** [comment]
Thanks for reporting! Should be fixed now.

I am glad that others find these extra features useful (:

**Comment by niobium0** [comment]
:) And I'm seriously impressed how fast you respond to issues.
