### ISSUE TITLE
Question: Has anybody gotten pascal working with cuda 8?

### ISSUE THREAD

**Issue by cpdurham** [AccelerateHS/accelerate#330]
I heard that Pascal has issues with cuda 7.5, was wondering if anybody had any luck getting cuda 8 rc working with accelerate-cuda. Or rather, are there any known reasons why this cannot work until changes are made to the code base?

Thanks!

**Comment by tmcdonell** [comment]
I don't have a pascal GPU (\*wink\*) but will see about updating the CUDA bindings at least. I'm currently travelling but will be back in a week.

**Comment by cpdurham** [comment]
Hey, just checking to make sure you saw my email

**Comment by tmcdonell** [comment]
Yep, sorry, just got back to Sydney. Responded just now.

**Comment by cpdurham** [comment]
Cuda 8 on a pascal gpu works with no issues, forgot to update this, closing
