### ISSUE TITLE
Add documentation for pagerank example

### ISSUE THREAD

**Issue by tmcdonell** [AccelerateHS/accelerate#334]
@robeverest please add some some short documentation on how to run the `pagerank` program from `accelerate-examples`.

https://github.com/AccelerateHS/accelerate-examples/blob/master/examples/pagerank/README.md

**Comment by robeverest** [comment]
I just added a short description of where to get sample data from and how to run the program. Let me know if there's anything missing.

**Comment by tmcdonell** [comment]
Awesome! Thanks (:
