### ISSUE TITLE
accelerate-llvm-ptx broken (with Quadro m5000, GHC-8.0.2, Ubuntu 16.04)

### ISSUE THREAD

**Issue by Qinka** [AccelerateHS/accelerate#345]
```
modprobe: ERROR: could not insert 'nvidia_367_uvm': Invalid argument
*** Exception:
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/LLVM/PTX/State.hs:50:9: (unhandled): CUDA Exception: unknown error
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/LLVM/PTX/State.hs:50:9 in accelerate-llvm-ptx-1.0.0.0-I22yTgCTcVwIDpoGE32huc:Data.Array.Accelerate.LLVM.PTX.State
```

I just try to run the example on the *Get Start*(on the GitHub page) and it BROKEN, (sad).

**Comment by tmcdonell** [comment]
That `modprobe` message is worrying. What version of the CUDA toolkit do you have?

Can you also:

 1. Confirm that your CUDA install works. Try running one of the sample programs, usually located in `/usr/local/cuda/samples`.

 2. Test just the Haskell CUDA bindings. Running the included `nvidia-device-query` executable may be enough.
