### ISSUE TITLE
whence accelerate-llvm-ptx?

### ISSUE THREAD

**Issue by conal** [AccelerateHS/accelerate#349]
I get a 404 error when trying to follow the [accelerate-llvm-ptx](https://github.com/AccelerateHS/accelerate-llvm-ptx) link in the [accelerate README](https://github.com/AccelerateHS/accelerate/blob/master/README.md).

**Comment by tmcdonell** [comment]
Whoops! I'll fix that post haste.

It's part of the accelerate-llvm repo: https://github.com/AccelerateHS/accelerate-llvm

**Comment by conal** [comment]
Thanks.
