### ISSUE TITLE
Break out the Matrix Market parser from accelerate-examples into a separate package

### ISSUE THREAD

**Issue by ocramz** [AccelerateHS/accelerate#352]
I think this module is important enough to deserve its own library : https://hackage.haskell.org/package/accelerate-examples-0.15.1.0/src/examples/smvm/MatrixMarket.hs

**Comment by tmcdonell** [comment]
That seems reasonable. Is there anything in there that you think should be changed/generalised to be more useful for others (or at least, for your own particular use case)?

**Comment by ocramz** [comment]
I'd like to use it in https://github.com/ocramz/sparse-linear-algebra and I had started writing my own attoparsec parser before noticing this module. 

The only changes I can think of right now are 
* a bit better exceptions (i.e. ditching `fail` and `error` in favor of the 'exceptions' paradigm; `throwM MismatchedType` or something..)
* generalize to Floating class from the Float type 

Also, I can take care of setting up a new library, with your permission, and giving all due credit.

**Comment by tmcdonell** [comment]
Okay, I think you might as well go ahead and start the new library yourself; I'm a bit busy right now and I don't want that to slow you down. Good luck!

**Comment by tmcdonell** [comment]
Let me know when it is out and I'll switch `accelerate-examples` over to using it instead.

**Comment by ocramz** [comment]
Will do! Thanks @tmcdonell :)

**Comment by ocramz** [comment]
@tmcdonell I've started https://github.com/ocramz/matrix-market-attoparsec , copied the module and mentioned you and `accelerate` in CONTRIBUTORS.md . I'll let you know when it's in a usable shape!

**Comment by ocramz** [comment]
@tmcdonell It's now up as https://hackage.haskell.org/package/matrix-market-attoparsec , on Stackage too. It now uses `scientific` instead of returning Float, and it fixes a bug with signed entries and parsing of indentation.

**Comment by tmcdonell** [comment]
Works great! Thanks! (:

**Comment by tmcdonell** [comment]
build failure on GHC-7.8: https://travis-ci.org/tmcdonell/accelerate-examples/jobs/203339541#L839

**Comment by ocramz** [comment]
Oh yes, 7.8.4 didn't have `deriving Typeable`. I'm on it!

**Comment by ocramz** [comment]
Fixed it in the latest matrix-market-attoparsec, it's up on Hackage, should
be in tomorrow's (Feb. 21) Stackage nightly. Apologies for the bug!

**Comment by tmcdonell** [comment]
Thanks for the speedy fix @ocramz! (:
