### ISSUE TITLE
Backpermute error on 3-dimensional arrays where each dimension is a different size

### ISSUE THREAD

**Issue by sh54** [AccelerateHS/accelerate#353]
I have managed to find some issues using `backpermute` on certain 3-dimensional arrays where each dimension is a different size.

Here is one failing example:

```haskell
backpermuteErrorDemonstration :: IO ()
backpermuteErrorDemonstration = do
  let arr = fromList shape [1..] :: Array DIM3 Int
  putStrLn $ show $ run $ rotate3D $ use arr
    where
      x = 8 :: Int
      y = 4 :: Int
      z = 2 :: Int
      shape = Z :. x :. y :. z
      rotate3D :: Elt e => Acc (Array DIM3 e) -> Acc (Array DIM3 e)
      rotate3D arr = backpermute (swap (Acc.shape arr)) swap arr
        where
          swap :: Exp DIM3 -> Exp DIM3
          swap ix =
            let Z :. m :. k :. l = unlift ix  :: Z :. Exp Int :. Exp Int :. Exp Int
            in  lift $ Z :. k :. l :. m
```

This is just rearranging some array `Z :. x :. y :. z` to `Z :. y :. z :. x`.

`rotate3D` is borrowed from the accelerate-fft project.

The error I get out of this is:

> ./Data/Array/Accelerate/Array/Representation.hs:111:39: (toIndex): index out of bounds: (4,4)
> CallStack (from HasCallStack):
>   error, called at ./Data/Array/Accelerate/Array/Representation.hs:111:39 in accelerate-1.0.0.0-I62rca2AQIX3AWBfaBYfvP:Data.Array.Accelerate.Array.Representation
> CallStack (from -prof):
>   Data.Array.Accelerate.Array.Representation.toIndex.\ (Data/Array/Accelerate/Array/Representation.hs:111:39-49)
>   Data.Array.Accelerate.Array.Representation.toIndex (Data/Array/Accelerate/Array/Representation.hs:(111,3)-(112,60))
>   Data.Array.Accelerate.Array.Sugar.toIndex (Data/Array/Accelerate/Array/Sugar.hs:1050:3-64)
>   Data.Array.Accelerate.Interpreter.evalPreOpenExp (Data/Array/Accelerate/Interpreter.hs:(717,1)-(788,84))
>   Data.Array.Accelerate.Interpreter.evalPreOpenFun (Data/Array/Accelerate/Interpreter.hs:(697,1)-(699,63))
>   Data.Array.Accelerate.Interpreter.evalPreFun (Data/Array/Accelerate/Interpreter.hs:692:1-66)
>   Data.Array.Accelerate.Interpreter.evalOpenAcc.evalF (Data/Array/Accelerate/Interpreter.hs:179:7-49)
>   Data.Array.Accelerate.Interpreter.evalOpenAcc.delayed (Data/Array/Accelerate/Interpreter.hs:(172,7)-(173,91))
>   Data.Array.Accelerate.Interpreter.backpermuteOp.\ (Data/Array/Accelerate/Interpreter.hs:623:30-39)
>   Data.Array.Accelerate.Array.Representation.iter.iter' (Data/Array/Accelerate/Array/Representation.hs:(148,7)-(149,60))
>   Data.Array.Accelerate.Array.Representation.iter.\ (Data/Array/Accelerate/Array/Representation.hs:146:41-52)
>   Data.Array.Accelerate.Array.Representation.iter (Data/Array/Accelerate/Array/Representation.hs:91:3-26)
>   Data.Array.Accelerate.Array.Representation.iter (Data/Array/Accelerate/Array/Representation.hs:(146,3)-(149,60))
>   Data.Array.Accelerate.Array.Sugar.iter (Data/Array/Accelerate/Array/Sugar.hs:1056:3-65)
>   Data.Array.Accelerate.Interpreter.backpermuteOp (Data/Array/Accelerate/Interpreter.hs:(622,1)-(623,40))
>   Data.Array.Accelerate.Interpreter.evalOpenAcc (Data/Array/Accelerate/Interpreter.hs:(165,1)-(230,97))
>   Data.Array.Accelerate.Interpreter.run.execute (Data/Array/Accelerate/Interpreter.hs:(88,5)-(91,66))
>   Data.Array.Accelerate.Interpreter.run (Data/Array/Accelerate/Interpreter.hs:(85,1)-(91,66))
>   Main.backpermuteErrorDemonstration (app/Main.hs:(218,1)-(232,39))
>   Main.CAF:backpermuteErrorDemonstration3 (<no location info>)

Note that if the line `in  lift $ Z :. k :. l :. m` gets altered to `in  lift $ Z :. k :. m :. l` then the code runs fine oddly enough.

My workaround has been to use `generate`.

**Comment by tmcdonell** [comment]
Thanks! I've fixed `rotate3D` in `accelerate-fft`. You are correct, the shape and index permutations should have been the reverse of each other, instead of using `swap` in both cases.
