### ISSUE TITLE
llvm-general issues when building accelerate-examples on linux box

### ISSUE THREAD

**Issue by andygill** [AccelerateHS/accelerate#355]
When building accelerate-examples on a linux machine, I get this failure I've been unable to fix. I have the latest version of cabal.

````
% stack setup --upgrade-cabal 
% stack install
Cabal file warning in /local/andygill/git/accelerate-examples/.stack-work/downloaded/gSwW0m0hjufs/llvm-general/llvm-general.cabal: Ignoring unknown section type: custom-setup
There were multiple candidates for the Cabal entry "Config" (/local/andygill/git/accelerate-examples/examples/smvm/Config.hs), picking /local/andygill/git/accelerate-examples/examples/nofib/Config.hs
There were multiple candidates for the Cabal entry "Main.hs" (/local/andygill/git/accelerate-examples/examples/smvm/Main.hs), picking /local/andygill/git/accelerate-examples/examples/nofib/Main.hs
No packages found in snapshot which provide a "llvm-config" executable, which is a build-tool dependency of "llvm-general"
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595
[...]

--  While building package llvm-general-3.8.0.0 using:
[...]
    Process exited with code: ExitFailure 1
    Logs have been written to: /local/andygill/git/accelerate-examples/.stack-work/logs/llvm-general-3.8.0.0.log

    setup: The program 'llvm-config' version ==3.8.* is required but it could not
    be found.
````

when I try to build just llvm-general, I get

````
% stack install llvm-general
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595

llvm-general-3.8.0.0: configure (lib)
setup: The program 'llvm-config' version ==3.8.* is required but it could not
be found.

--  While building package llvm-general-3.8.0.0 using:
...
````

**Comment by tmcdonell** [comment]
It is looking for your llvm installation. If you have a Debian/Ubuntu system, there are instructions for getting it via apt on http://apt.llvm.org. In summary, you need to do something along the lines of...

```
$ wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
$ sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main"
$ sudo apt-get install llvm-3.9-dev
```

I'd recommend llvm-3.9 for now, until https://github.com/bscarlet/llvm-general/pull/194 gets merged. You'll need to change your `stack.yaml` to point to the 3.9 version (it is there already, just comment out the 3.8 line and uncomment 3.9. Perhaps I should host my own fork that includes the fix...)

Good luck! (:

(If you are not on a ubuntu/debian system, then your package manager still probably includes it. Otherwise, I could help you build llvm from source.)

**Comment by andygill** [comment]
Thanks @tmcdonell 

Would you recommend we switch from RH24 to Debian/Ubuntu, for accelerate work? This is an option for our K-20 machine, which will only be working with accelerate-based code.

**Comment by tmcdonell** [comment]
I don't have any RH boxes around so can't really comment on how well it works (although I assume it is fine). All the linux boxes I have access to are running Ubuntu.
