### ISSUE TITLE
How do you effectively handle non-commutative folds?

### ISSUE THREAD

**Issue by RasmusWL** [AccelerateHS/accelerate#358]
Hi there. I am working on a project to implement segmented reductions, and was curious as to how you handle non-commutative reductions effectively.

I can see that for the version of Accelerate described in [Trevor's PhD thesis](http://www.cse.unsw.edu.au/~tmcdonell/papers/TrevorMcDonell_PhD_submission.pdf) the fold function was required to be both commutative and associative (stated on page 23).

In the current version, it is only required that the fold function is associative, as stated in [Data/Array/Accelerate/Language.hs:389](https://github.com/AccelerateHS/accelerate/blob/b6c1621/Data/Array/Accelerate/Language.hs#L389)

It is described anywhere how you support effective reductions when you don't require the fold function to be commutative? I could imagine that you perform a transpose on the input array to ensure memory coalescing, but I couldn't find this documented anywhere.

**Comment by tmcdonell** [comment]
Hi!

As you found, yes, reductions in `accelerate-cuda` had to be both associative and commutative. This is not required for the `accelerate-llvm` backends though ([e.g.](https://github.com/AccelerateHS/accelerate-examples/blob/master/examples/nofib/Test/Prelude/Fold.hs#L259)).

The strategy for segmented (or multidimensional) reductions is different from that of reducing an entire array to a single element. For the former, I just use one thread block per segment; it is pretty straightforward then since you don't need to coordinate thread blocks, but is not a great strategy if your segments are very small (< thread block dimension), or perhaps if segment lengths are highly variable. Similarly, you could use one warp per segment (which I suspect cuSPARSE does, based on looking at its progenitor CUSP).

No transpose is necessary.

Um, not sure if that answers the question or not..?

**Comment by RasmusWL** [comment]
Thanks for the quick reply. I'll try to explain myself more clearly.

In the case of either a "1D array to scalar" fold, or a "`n` dimensional array to a `n-1` dimensional array" fold, it is my understanding that you make each thread read multiple elements. These indexes of these elements will be separated by a stride to ensure memory coalescing, so thread `tid` would read elements at indexes: 
* `offset + tid`
* `offset + tid + stride`
* `offset + tid + stride * 2` 
* ...

I was interested in how you transform the input array to allow for such a stride. In the case of a non-commutative folding function `f`, if the input array has not been transformed we must initially fold adjacent elements, so thread `tid` must read elements `offset + tid`, `offset + tid + 1`, `offset + tid + 2`, and so on. This doesn't allow for memory coalescing, so I'm just wonder what kind of transformation you apply to the input array to avoid having to use `stride == 1`.

**Comment by tmcdonell** [comment]
In Accelerate threads of a warp and block _cooperatively_ reduce elements in a tree-reduction. That is, thread 0 reads element `xs[offset]`, thread 1 at `xs[offset+1]`, etc... which maintains coalescing. Then, threads cooperatively reduce using shared memory. You can still this with non-commutative operations.

Striding comes in later; once you get the warp-sized reduction down you can build on that.

**Comment by RasmusWL** [comment]
Okay, thanks for elaborating.

I tried to read the code for accelerate-cuda where I could see a stride of [`warpSize`][cuda] being used for `n`-dimensional folds, and I thought it was the same happening in the accelerate-ptx code for [mkFoldDim][ptx], but I must admit I had time reading it without knowing anything about the internal API.

I think I understand what is happening now, after looking at the code in an editor where I can see the whitespace properly. Thanks for bearing with me, if you can verify that I understand the approach correctly now, I think I that will be the last of my questions :)

The code generation for folding over the inner dimension of an n-dimensional array, `mkFoldDim`, works by assigning a single block to a single segment (for simplicity). A block will have to process the elements from indexes `[start,end)` of the flat input array. The block will reduce the segment over multiple iterations, with iteration counter `i=0` for the first iteration.

1. In iteration `i`, thread `tid` reads element `tid + i*blocksize` (if within bounds).
2. All threads that read an element within bounds performs a cooperative in-block reduction. (there are two versions of this in-block reduction, a simple when all threads read an element, and a more complex for when only *some* threads did)
3. If there are still elements in the segment that have not been processed, add the result of the in-block reduction to the accumulator of thread 0, and goto step 1.
4. When all elements have been processed, thread 0 will return the final result, and apply the "seed" value if it exists (initial element that does not need to be the neutral element).

The code for reducing a 1D array to a single value uses multiple blocks that produces a temporary array (to allow higher parallelism), and therefore launches the reduction kernel recursively, until there is a single value left. (there is also a special case for a small 1D array that can fit into a single block)



---

ps, there is still a note in the [FoldSeg](foldseg-note) code about some problems with `__syncthreads()`. However, from the Fold code that problem seems to be resolved :)

[cuda]: https://github.com/AccelerateHS/accelerate-cuda/blob/cd8d31c/Data/Array/Accelerate/CUDA/CodeGen/Reduction.hs#L523
[ptx]: https://github.com/AccelerateHS/accelerate-llvm/blob/f8bd8411efcbfc106818cd4e4975e6a3db191fa1/accelerate-llvm-ptx/Data/Array/Accelerate/LLVM/PTX/CodeGen/Fold.hs#L361
[foldseg-note]: https://github.com/AccelerateHS/accelerate-llvm/blob/f8bd841/accelerate-llvm-ptx/Data/Array/Accelerate/LLVM/PTX/CodeGen/FoldSeg.hs#L193

**Comment by tmcdonell** [comment]
Yep, I think you have it (:
The approach is pretty straightforward. If you have a particular use case, you might be able to optimise parts of it to better suit.

That code you linked in `accelerate-cuda` is (one of) the place(s) which prevents non-commutative reductions. Past sins coming back to haunt me...

RE that note... sometimes CUDA does not behave as you would expect, or how the documentation says that it should. I never got to the bottom of why that workaround was necessary.

**Comment by RasmusWL** [comment]
Great, thanks for helping me out!

I am working on a project to generate efficient code for reductions of regularly shaped multidimensional arrays, and I'd be happy to send you more details for inspiration once I am done :)

Feel free to close this issue now though :)

---

Concerning the `__syncthreads()` issue, the [CUDA C Programming Guide](cuda-c-guide) has the following to say:

> __syncthreads() acts as a barrier at which all threads in the block must wait before any is allowed to proceed.

[cuda-c-guide]: http://docs.nvidia.com/cuda/cuda-c-programming-guide/

**Comment by tmcdonell** [comment]
That sounds just like Accelerate! Feel free to send us a PR with your optimised implementation (-;

Good luck!
