### ISSUE TITLE
Linking error in LLVM when compiling against PTX

### ISSUE THREAD

**Issue by electroCutie** [AccelerateHS/accelerate#361]
I get the following error when building
Preprocessing executable 'helloFail' for minRepro-0.1.0.0...
    [1 of 1] Compiling Main             ( src/HelloFail.hs, .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/helloFail/helloFail-tmp/Main.o )
    Linking .stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/helloFail/helloFail ...
    /usr/lib/llvm-4.0/lib/libLLVMSupport.a(Compression.cpp.o): In function `llvm::zlib::compress(llvm::StringRef, llvm::SmallVectorImpl<char>&, llvm::zlib::CompressionLevel)':
    (.text._ZN4llvm4zlib8compressENS_9StringRefERNS_15SmallVectorImplIcEENS0_16CompressionLevelE+0x29): undefined reference to `compressBound'
    /usr/lib/llvm-4.0/lib/libLLVMSupport.a(Compression.cpp.o): In function `llvm::zlib::compress(llvm::StringRef, llvm::SmallVectorImpl<char>&, llvm::zlib::CompressionLevel)':
    (.text._ZN4llvm4zlib8compressENS_9StringRefERNS_15SmallVectorImplIcEENS0_16CompressionLevelE+0xb7): undefined reference to `compress2'
    /usr/lib/llvm-4.0/lib/libLLVMSupport.a(Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x75): undefined reference to `setupterm'
    /usr/lib/llvm-4.0/lib/libLLVMSupport.a(Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0x98): undefined reference to `tigetnum'
    /usr/lib/llvm-4.0/lib/libLLVMSupport.a(Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xa1): undefined reference to `set_curterm'
    /usr/lib/llvm-4.0/lib/libLLVMSupport.a(Process.cpp.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
    (.text._ZN4llvm3sys7Process23FileDescriptorHasColorsEi+0xa9): undefined reference to `del_curterm'
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)

My system is Xubuntu 16.10
$ uname -a
Linux X-L6 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ dpkg -l | grep llvm | grep 4.0
ii  libllvm4.0:amd64                                     1:4.0~svn297204-1~exp1                      amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm4.0-dbg:amd64                                 1:4.0~svn297204-1~exp1                      amd64        Modular compiler and toolchain technologies, debugging libraries
ii  llvm-4.0                                             1:4.0~svn297204-1~exp1                      amd64        Modular compiler and toolchain technologies
ii  llvm-4.0-dev                                         1:4.0~svn297204-1~exp1                      amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-4.0-doc                                         1:4.0~svn297204-1~exp1                      all          Modular compiler and toolchain technologies, documentation
ii  llvm-4.0-examples                                    1:4.0~svn297204-1~exp1                      all          Modular compiler and toolchain technologies, examples
ii  llvm-4.0-runtime                                     1:4.0~svn297204-1~exp1                      amd64        Modular compiler and toolchain technologies, IR interpreter
ii  llvm-4.0-tools                                       1:4.0~svn297204-1~exp1                      amd64        Modular compiler and toolchain technologies, tools

(latest and greatest from http://apt.llvm.org/ )

$ lspci | grep -i nvidia
01:00.0 VGA compatible controller: NVIDIA Corporation GK107 [GeForce GT 740] (rev a1)
01:00.1 Audio device: NVIDIA Corporation GK107 HDMI Audio Controller (rev a1)

accelerate-llvm git version f1d8b57aea5d891d1c1ec3a2bfa31a4c5a8aae19

I will attach a minimal reproduction project momentarily

**Comment by tmcdonell** [comment]
Hm, linker errors like that are usually because `llvm-hs` isn't built with `-fshared-llvm` (though it should be the default these days) (GHCi and by extension Template Haskell have some trouble with static libraries). Try setting it explicitly, with either `cabal install llvm-hs -fshared-llvm`, or in your `stack.yaml`:

```yaml
flags:
  llvm-hs:
    shared-llvm: true
```

and let me know how it goes?

The included `stack-*.yaml` files should work as well.

```sh
$ ln -s stack-8.0.yaml stack.yaml
$ stack setup
$ stack build
```

**Comment by tmcdonell** [comment]
Could you please run the following and tell me what you get?

```sh
$ llvm-config-4.0 --libs --link-static
$ llvm-config-4.0 --libs --link-shared
```

**Comment by electroCutie** [comment]
$ llvm-config-4.0 --libs --link-static
-lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMMIRParser -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMCoverage -lLLVMTableGen -lLLVMOrcJIT -lLLVMXCoreDisassembler -lLLVMXCoreCodeGen -lLLVMXCoreDesc -lLLVMXCoreInfo -lLLVMXCoreAsmPrinter -lLLVMSystemZDisassembler -lLLVMSystemZCodeGen -lLLVMSystemZAsmParser -lLLVMSystemZDesc -lLLVMSystemZInfo -lLLVMSystemZAsmPrinter -lLLVMSparcDisassembler -lLLVMSparcCodeGen -lLLVMSparcAsmParser -lLLVMSparcDesc -lLLVMSparcInfo -lLLVMSparcAsmPrinter -lLLVMRISCVDesc -lLLVMRISCVCodeGen -lLLVMRISCVInfo -lLLVMPowerPCDisassembler -lLLVMPowerPCCodeGen -lLLVMPowerPCAsmParser -lLLVMPowerPCDesc -lLLVMPowerPCInfo -lLLVMPowerPCAsmPrinter -lLLVMNVPTXCodeGen -lLLVMNVPTXDesc -lLLVMNVPTXInfo -lLLVMNVPTXAsmPrinter -lLLVMMSP430CodeGen -lLLVMMSP430Desc -lLLVMMSP430Info -lLLVMMSP430AsmPrinter -lLLVMMipsDisassembler -lLLVMMipsCodeGen -lLLVMMipsAsmParser -lLLVMMipsDesc -lLLVMMipsInfo -lLLVMMipsAsmPrinter -lLLVMLanaiDisassembler -lLLVMLanaiCodeGen -lLLVMLanaiAsmParser -lLLVMLanaiDesc -lLLVMLanaiInstPrinter -lLLVMLanaiInfo -lLLVMHexagonDisassembler -lLLVMHexagonCodeGen -lLLVMHexagonAsmParser -lLLVMHexagonDesc -lLLVMHexagonInfo -lLLVMBPFDisassembler -lLLVMBPFCodeGen -lLLVMBPFDesc -lLLVMBPFInfo -lLLVMBPFAsmPrinter -lLLVMARMDisassembler -lLLVMARMCodeGen -lLLVMARMAsmParser -lLLVMARMDesc -lLLVMARMInfo -lLLVMARMAsmPrinter -lLLVMAMDGPUDisassembler -lLLVMAMDGPUCodeGen -lLLVMAMDGPUAsmParser -lLLVMAMDGPUDesc -lLLVMAMDGPUInfo -lLLVMAMDGPUAsmPrinter -lLLVMAMDGPUUtils -lLLVMAArch64Disassembler -lLLVMAArch64CodeGen -lLLVMAArch64AsmParser -lLLVMAArch64Desc -lLLVMAArch64Info -lLLVMAArch64AsmPrinter -lLLVMAArch64Utils -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMLineEditor -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMTransformUtils -lLLVMBitWriter -lLLVMAnalysis -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMBitReader -lLLVMProfileData -lLLVMCore -lLLVMSupport -lLLVMDemangle

$ llvm-config-4.0 --libs --link-shared
-lLLVM-4.0

**Comment by tmcdonell** [comment]
Okay, those look fine. It should be able to link against the shared library if you add the `shared-llvm` flag.

**Comment by electroCutie** [comment]
Yep, there it goes.
Thanks 1e6!

**Comment by tmcdonell** [comment]
No worries, have fun! ^_^
