### ISSUE TITLE
gcc failed in phase Linker when building examples

### ISSUE THREAD

**Issue by currymj** [AccelerateHS/accelerate#368]
I'm trying to build the examples. I get the following set of errors during linking. I have LLVM 4.0 installed from their apt repository, as far as I know. I'm on Ubuntu 16.10. This is using the standard stack-8.0.yaml file. This is possibly related to #366 or #361. Are there any common misconfigurations I should check for? Any other steps I should take to provide useful information?

I am really looking forward to using Accelerate. I appreciate any help anyone can provide with this problem.

```
mcurry@stbb18:~/accelerate-examples$ CC=clang-4.0 CXX=clang++-4.0 stack build
Cabal file warning in /home/mcurry/accelerate-examples/.stack-work/downloaded/cvPn6FwVWNLW/linear-accelerate.cabal: Ignoring unknown section type: custom-setup
There were multiple candidates for the Cabal entry "Config" (/home/mcurry/accelerate-examples/examples/smvm/Config.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Config.hs
There were multiple candidates for the Cabal entry "Main.hs" (/home/mcurry/accelerate-examples/examples/smvm/Main.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Main.hs
accelerate-examples-1.0.0.0: build (lib + exe)
Preprocessing library accelerate-examples-1.0.0.0...
Preprocessing executable 'accelerate-crystal' for
accelerate-examples-1.0.0.0...
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/accelerate-crystal/accelerate-crystal ...
/home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.8/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ/libHSllvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ.a(TargetC.o): In function `LLVM_Hs_LookupTarget':
(.text.LLVM_Hs_LookupTarget+0x70): undefined reference to `llvm::TargetRegistry::lookupTarget(std::string const&, llvm::Triple&, std::string&)'
/home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.8/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ/libHSllvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ.a(TargetC.o): In function `LLVM_Hs_GetDefaultTargetTriple':
(.text.LLVM_Hs_GetDefaultTargetTriple+0xa): undefined reference to `llvm::sys::getDefaultTargetTriple()'
/home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.8/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ/libHSllvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ.a(TargetC.o): In function `LLVM_Hs_GetProcessTargetTriple':
(.text.LLVM_Hs_GetProcessTargetTriple+0xa): undefined reference to `llvm::sys::getProcessTriple()'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
There were multiple candidates for the Cabal entry "Config" (/home/mcurry/accelerate-examples/examples/smvm/Config.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Config.hs
There were multiple candidates for the Cabal entry "Main.hs" (/home/mcurry/accelerate-examples/examples/smvm/Main.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Main.hs

--  While building package accelerate-examples-1.0.0.0 using:
      /home/mcurry/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:accelerate-examples exe:accelerate-crystal exe:accelerate-fft exe:accelerate-fluid exe:accelerate-hashcat exe:accelerate-kmeans exe:accelerate-mandelbrot exe:accelerate-nbody exe:accelerate-nofib exe:accelerate-pagerank exe:accelerate-ray exe:accelerate-smoothlife exe:accelerate-smvm exe:accelerate-tunnel --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by currymj** [comment]
Also, attempting the simple `Dotp.hs` example on the website results in a segfault immediately after calling `run` for either CPU or GPU. This is probably related, right?

**Comment by tmcdonell** [comment]
The only misconfiguration faults that I have seen are the ones that you linked, where `shared-llvm` is set to (or defaults to) `false`. This one looks different.

The standard apt version of llvm should work; that is what the travis-ci bots use (though the bots run ubuntu 12). If you run the following it should complain if the shared library is not available:

```sh
> llvm-config-4.0 --libs --link-shared
-lLLVM-4.0
```

The segfault is probably related, yes.

I wonder if it has something to do with the `CC=clang-4.0 CXX=clang++-4.0` part on the command line, and `ghc` getting confused somewhere along the way. It does say "gcc failed in phase Linker" rather than "clang-4.0 failed ...", so maybe it is picking the C compiler inconsistently?

@cocreature have you seen that linker error before?

**Comment by cocreature** [comment]
I haven’t seen this error myself, but https://github.com/bscarlet/llvm-general/issues/193#issuecomment-276481286 seems like it might be related. In general using a different C compiler than the one used to build LLVM (the APT package uses GCC iirc) can cause problems although I’m not quite sure why and how so the first thing I would try is removing `CC=clang-4.0 CXX=clang++-4.0` unless you have some specific reason for using this.

**Comment by cocreature** [comment]
The output of `llvm-config --cxxflags` (or `llvm-config-4.0`) would also be interesting.

**Comment by currymj** [comment]
The `CC` and `CXX` environment variables were something I put in to see if magical thinking might help. The exact same output occurs without them, as far as I can tell. I've copy pasted at the bottom just in case I missed some subtle change.

Here's the output of the two llvm-config commands. I'm not sure how to interpret them, but they didn't crash.

```
mcurry@stbb18:~/accelerate-examples$ llvm-config-4.0 --cxxflags
-I/usr/lib/llvm-4.0/include -std=c++0x -gsplit-dwarf -Wl,-fuse-ld=gold -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -Werror=date-time -std=c++11 -ffunction-sections -fdata-sections -O2 -g -DNDEBUG  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
```
```
mcurry@stbb18:~/accelerate-examples$ llvm-config-4.0 --libs --link-shared
-lLLVM-4.0
```


Output without `CC` and `CXX` (I checked beforehand, these vars are definitely empty):

``
mcurry@stbb18:~/accelerate-examples$ stack build
Cabal file warning in /home/mcurry/accelerate-examples/.stack-work/downloaded/cvPn6FwVWNLW/linear-accelerate.cabal: Ignoring unknown section type: custom-setup
There were multiple candidates for the Cabal entry "Config" (/home/mcurry/accelerate-examples/examples/smvm/Config.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Config.hs
There were multiple candidates for the Cabal entry "Main.hs" (/home/mcurry/accelerate-examples/examples/smvm/Main.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Main.hs
accelerate-examples-1.0.0.0: build (lib + exe)
Preprocessing library accelerate-examples-1.0.0.0...
Preprocessing executable 'accelerate-crystal' for
accelerate-examples-1.0.0.0...
Linking .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/accelerate-crystal/accelerate-crystal ...
/home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.8/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ/libHSllvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ.a(TargetC.o): In function `LLVM_Hs_LookupTarget':
(.text.LLVM_Hs_LookupTarget+0x70): undefined reference to `llvm::TargetRegistry::lookupTarget(std::string const&, llvm::Triple&, std::string&)'
/home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.8/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ/libHSllvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ.a(TargetC.o): In function `LLVM_Hs_GetDefaultTargetTriple':
(.text.LLVM_Hs_GetDefaultTargetTriple+0xa): undefined reference to `llvm::sys::getDefaultTargetTriple()'
/home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.8/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ/libHSllvm-hs-4.0.0.0-AbtHV1rJCyE3TPeh26OXlJ.a(TargetC.o): In function `LLVM_Hs_GetProcessTargetTriple':
(.text.LLVM_Hs_GetProcessTargetTriple+0xa): undefined reference to `llvm::sys::getProcessTriple()'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
There were multiple candidates for the Cabal entry "Config" (/home/mcurry/accelerate-examples/examples/smvm/Config.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Config.hs
There were multiple candidates for the Cabal entry "Main.hs" (/home/mcurry/accelerate-examples/examples/smvm/Main.hs), picking /home/mcurry/accelerate-examples/examples/nofib/Main.hs

--  While building package accelerate-examples-1.0.0.0 using:
      /home/mcurry/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:accelerate-examples exe:accelerate-crystal exe:accelerate-fft exe:accelerate-fluid exe:accelerate-hashcat exe:accelerate-kmeans exe:accelerate-mandelbrot exe:accelerate-nbody exe:accelerate-nofib exe:accelerate-pagerank exe:accelerate-ray exe:accelerate-smoothlife exe:accelerate-smvm exe:accelerate-tunnel --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by tmcdonell** [comment]
Can you provide the output of `ghc-pkg describe llvm-hs-4.0.1.0`, particularly the `extra-libraries` section?

**Comment by currymj** [comment]
The `stack.yaml` as it exists specifies `llvm-hs-4.0.0.0`. I changed it to the newer version. Here's the output of `stack exec ghc-pkg describe llvm-hs-4.0.1.0` after that change.

The `extra-libraries` section is `extra-libraries: stdc++ LLVM-4.0`.

```
name: llvm-hs
version: 4.0.1.0
id: llvm-hs-4.0.1.0-HyYqdSIlp8J1u1v2yrRU4W
key: llvm-hs-4.0.1.0-HyYqdSIlp8J1u1v2yrRU4W
license: BSD3
copyright: (c) 2013 Benjamin S. Scarlet and Google Inc.
maintainer: Anthony Cowley, Stephen Diehl, Moritz Kiefer <moritz.kiefer@purelyfunctional.org>
stability: experimental
homepage: http://github.com/llvm-hs/llvm-hs/
synopsis: General purpose LLVM bindings
description:
    llvm-hs is a set of Haskell bindings for LLVM <http://llvm.org/>. Unlike other current Haskell bindings,
    it uses an ADT to represent LLVM IR (<http://llvm.org/docs/LangRef.html>), and so offers two advantages: it
    handles almost all of the stateful complexities of using the LLVM API to build IR; and it supports moving IR not
    only from Haskell into LLVM C++ objects, but the other direction - from LLVM C++ into Haskell.
category: Compilers/Interpreters, Code Generation
author: Anthony Cowley, Stephen Diehl, Moritz Kiefer <moritz.kiefer@purelyfunctional.org>, Benjamin S. Scarlet
exposed: True
exposed-modules:
    LLVM LLVM.Analysis LLVM.CodeGenOpt LLVM.CodeModel LLVM.CommandLine
    LLVM.Context LLVM.Diagnostic LLVM.ExecutionEngine
    LLVM.Internal.Analysis LLVM.Internal.Atomicity
    LLVM.Internal.Attribute LLVM.Internal.BasicBlock
    LLVM.Internal.CallingConvention LLVM.Internal.Coding
    LLVM.Internal.CommandLine LLVM.Internal.Constant
    LLVM.Internal.Context LLVM.Internal.DataLayout
    LLVM.Internal.DecodeAST LLVM.Internal.Diagnostic
    LLVM.Internal.EncodeAST LLVM.Internal.ExecutionEngine
    LLVM.Internal.FastMathFlags LLVM.Internal.FloatingPointPredicate
    LLVM.Internal.Function LLVM.Internal.Global LLVM.Internal.Inject
    LLVM.Internal.InlineAssembly LLVM.Internal.Instruction
    LLVM.Internal.InstructionDefs LLVM.Internal.IntegerPredicate
    LLVM.Internal.LibraryFunction LLVM.Internal.MemoryBuffer
    LLVM.Internal.Metadata LLVM.Internal.Module LLVM.Internal.OrcJIT
    LLVM.Internal.OrcJIT.CompileOnDemandLayer
    LLVM.Internal.OrcJIT.IRCompileLayer LLVM.Internal.Operand
    LLVM.Internal.PassManager LLVM.Internal.RawOStream
    LLVM.Internal.RMWOperation LLVM.Internal.String
    LLVM.Internal.TailCallKind LLVM.Internal.Target
    LLVM.Internal.Threading LLVM.Internal.Type LLVM.Internal.Value
    LLVM.Internal.FFI.Analysis LLVM.Internal.FFI.Attribute
    LLVM.Internal.FFI.Assembly LLVM.Internal.FFI.BasicBlock
    LLVM.Internal.FFI.BinaryOperator LLVM.Internal.FFI.Bitcode
    LLVM.Internal.FFI.Builder LLVM.Internal.FFI.ByteRangeCallback
    LLVM.Internal.FFI.Cleanup LLVM.Internal.FFI.CommandLine
    LLVM.Internal.FFI.Constant LLVM.Internal.FFI.Context
    LLVM.Internal.FFI.DataLayout LLVM.Internal.FFI.ExecutionEngine
    LLVM.Internal.FFI.Function LLVM.Internal.FFI.GlobalAlias
    LLVM.Internal.FFI.GlobalValue LLVM.Internal.FFI.GlobalVariable
    LLVM.Internal.FFI.InlineAssembly LLVM.Internal.FFI.Instruction
    LLVM.Internal.FFI.InstructionDefs LLVM.Internal.FFI.Iterate
    LLVM.Internal.FFI.LLVMCTypes LLVM.Internal.FFI.MemoryBuffer
    LLVM.Internal.FFI.Metadata LLVM.Internal.FFI.Module
    LLVM.Internal.FFI.OrcJIT
    LLVM.Internal.FFI.OrcJIT.CompileOnDemandLayer
    LLVM.Internal.FFI.OrcJIT.IRCompileLayer
    LLVM.Internal.FFI.PassManager LLVM.Internal.FFI.PtrHierarchy
    LLVM.Internal.FFI.RawOStream LLVM.Internal.FFI.SMDiagnostic
    LLVM.Internal.FFI.Target LLVM.Internal.FFI.Threading
    LLVM.Internal.FFI.Transforms LLVM.Internal.FFI.Type
    LLVM.Internal.FFI.User LLVM.Internal.FFI.Value LLVM.Module
    LLVM.OrcJIT LLVM.OrcJIT.CompileOnDemandLayer
    LLVM.OrcJIT.IRCompileLayer LLVM.PassManager LLVM.Relocation
    LLVM.Target LLVM.Target.LibraryFunction LLVM.Target.Options
    LLVM.Threading LLVM.Transforms
hidden-modules: Control.Monad.AnyCont Control.Monad.AnyCont.Class
                Control.Monad.Trans.AnyCont
abi: 4853b134aa95a9f5381ca12c267a129d
trusted: False
import-dirs: /home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.1.0-HyYqdSIlp8J1u1v2yrRU4W
library-dirs: /home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/lib/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.1.0-HyYqdSIlp8J1u1v2yrRU4W
              /usr/lib/llvm-4.0/lib
dynamic-library-dirs: /home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/lib/x86_64-linux-ghc-8.0.2
                      /usr/lib/llvm-4.0/lib
data-dir: /home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/share/x86_64-linux-ghc-8.0.2/llvm-hs-4.0.1.0
hs-libraries: HSllvm-hs-4.0.1.0-HyYqdSIlp8J1u1v2yrRU4W
extra-libraries:
    stdc++ LLVM-4.0
include-dirs: /usr/lib/llvm-4.0/include
depends:
    array-0.5.1.1 base-4.9.1.0 bytestring-0.10.8.1 containers-0.5.7.1
    llvm-hs-pure-4.0.0.0-2EKQPzemceCEww6fPxl71c
    mtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6
    parsec-3.1.11-113irVHGgd88sRnywByDNw template-haskell-2.11.1.0
    transformers-0.5.2.0
    transformers-compat-0.5.1.4-IuFogs8HAVUJBWVNMhtssu
    utf8-string-1.0.1.1-1DpjxLeTvGg7ttZZojxJR5
haddock-interfaces: /home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/doc/llvm-hs-4.0.1.0/llvm-hs.haddock
haddock-html: /home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.0/8.0.2/doc/llvm-hs-4.0.1.0
pkgroot: "/home/mcurry/accelerate-examples/.stack-work/install/x86_64-linux/lts-8.0/8.0.2"
```

**Comment by tmcdonell** [comment]
This is really strange. Some other things that might be worth trying:

 1. `stack test llvm-hs`. It might be easier to clone that package separately to do this.

 2. See if a simpler program works. Something like the following, either compiled or in ghci:
```haskell
import Data.Array.Accelerate as A
import Data.Array.Accelerate.LLVM.Native as CPU
let xs = fromList (Z:.10) [0..] :: Vector Float
CPU.run $ A.map (+1) (use xs)
```

**Comment by currymj** [comment]
The problem turned out to be with an ancient version of gcc that had I had somehow inadvertently installed. Replacing it with gcc 6 fixed everything.

**Comment by tmcdonell** [comment]
Ah, great, glad you found it!
Sorry this was such a hassle for you, I should have thought of that earlier ):
