### ISSUE TITLE
Your library is excellent

### ISSUE THREAD

**Issue by currymj** [AccelerateHS/accelerate#372]
Utterly fantastic. Just rewrote a simple Monte Carlo computation and got a greater than thousandfold speedup over my own crappy versions in Matlab and Python. Annoyances with type inference aside, everything was well-designed and did what was needed. Admittedly, part of the problem with my old code was that I'm just not a skilled parallel programmer. The types you've designed are an extremely useful tool for thinking though -- so even if not all of that thousandfold speedup is due to the technical merits of Accelerate, I think it should still get the credit.

This might not be strictly appropriate for a Github issue, but I wanted to let you guys know!

**Comment by tmcdonell** [comment]
NICE! This makes me super happy ^_^
