### ISSUE TITLE
accelerate-mandelbrot non-exhaustive patterns when using cuda

### ISSUE THREAD

**Issue by noughtmare** [AccelerateHS/accelerate#377]
When running `accelerate-mandelbrot --cuda` it throws this exception:

```
accelerate-mandelbrot: Data/Array/Accelerate/CUDA/CodeGen.hs:(408,7)-(476,69): Non-exhaustive patterns in case
```

Other examples (like `accelerate-smoothlife --cuda`) do work correctly.

**Comment by tmcdonell** [comment]
Please you [accelerate-llvm-ptx](https://hackage.haskell.org/package/accelerate-llvm-ptx) instead. accelerate-cuda is deprecated.
