### ISSUE TITLE
accelerate-fluid moving mouse off screen causes internal error

### ISSUE THREAD

**Issue by noughtmare** [AccelerateHS/accelerate#378]
Running `accelerate-fluid --cuda` and then clicking and while holding the left mouse button down moving off the screen freezes my entire computer for a few seconds and then gives me this error:

```
accelerate-fluid: 
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/CUDA/State.hs:88:9: (unhandled): CUDA Exception: the launch timed out and was terminated
```

Moving to the right or left works, but moving to the bottom or top causes this error.

**Comment by tmcdonell** [comment]
Do you have the same problem with [accelerate-llvm-ptx](https://hackage.haskell.org/package/accelerate-llvm-ptx)? Please switch to that instead.

**Comment by tmcdonell** [comment]
Most likely that is a bug with the GUI code though, feeding in some garbage to the backend...

**Comment by noughtmare** [comment]
I have tried with llvm-ptx and it causes the same error:
```
accelerate-fluid: 
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/LLVM/PTX/State.hs:50:9: (unhandled): CUDA Exception: the launch timed out and was terminated
```

**Comment by tmcdonell** [comment]
I suspect it is just a problem with the GUI code. It should be pretty easy to fix. Thanks for the report!
