### ISSUE TITLE
Unable to get target for 'nvptx64-nvidia-cuda'

### ISSUE THREAD

**Issue by noughtmare** [AccelerateHS/accelerate#379]
When I try to run any of the examples in `accelerate-examples` with the `--llvm-ptx` option I get this error:

```
accelerate-ray: : error: unable to get target for 'nvptx64-nvidia-cuda', see --version and --triple.
```

I have built llvm-4.0 from source with the NVPTX target enabled by following [the guide at accelerate-llvm](https://github.com/AccelerateHS/accelerate-llvm#building-from-source).

OS: Arch Linux
Kernel: x86_64 Linux 4.10.9-1-ARCH
CPU: Intel Core i7-6700HQ
GPU: Quadro M1000M

I have installed cuda version 8.0.61-1 with pacman.

**Comment by tmcdonell** [comment]
What is the output of `llc --version` (or `llc-4.0`)?

**Comment by noughtmare** [comment]
```
LLVM (http://llvm.org/):
  LLVM version 4.0.0
  Optimized build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake

  Registered Targets:
    nvptx   - NVIDIA PTX 32-bit
    nvptx64 - NVIDIA PTX 64-bit
    x86     - 32-bit X86: Pentium-Pro and above
    x86-64  - 64-bit X86: EM64T and AMD64
```

**Comment by tmcdonell** [comment]
I'm not sure why it is not picking that up then. Unless you have multiple versions of LLVM lying around and it is linking against the wrong one for some reason.

**Comment by noughtmare** [comment]
I found the problem: I didn't recompile completely after installing the NVPTX enabled version of llvm.

**Comment by tmcdonell** [comment]
Ah, that makes sense. Glad you found the problem! (:
