### ISSUE TITLE
accelerate-mandelbrot seems to require CUDA?

### ISSUE THREAD

**Issue by nlw0** [AccelerateHS/accelerate#383]
I am a total beginner. I'm trying to run some examples in my notebook that only has a basic Intel graphics card. I think I'm trying to use the accelerate-llvm-native backend (installed accelerate-llvm-ptx before by mistake). But no matter what I try, I still end up having this message when I try to run the accelerate-mandelbrot example:

```accelerate-mandelbrot: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory```

I did manage to run accelerate-canny before. So, are these example all generic or does accelerate-mandelbrot require the CUDA backend somehow? Or is it some quirk in my installation that is preventing it to work? Or should I still have the library installed anyway despite not intending to use the ptx backend? (I am trying to install it on Ubuntu, but it ends up replacing the drivers, then the problem is that I lose GLX...)

**Comment by tmcdonell** [comment]
It shouldn't require a CUDA GPU. Telling it explicitly not to build against the GPU backend should be enough, so try adding the following to your `stack.yaml`:

```yaml
flags:
  accelerate-fft:
    cuda: false
    llvm-ptx: false
  accelerate-examples:
    cuda: false
    llvm-ptx: false
```

Or equivalently with cabal:

```
$ cabal install accelerate-fft -f-llvm-ptx -f-cuda
$ cabal install accelerate-examples -f-llvm-ptx -f-cuda
```

Let me know if that helps.

**Comment by nlw0** [comment]
Worked with cabal, thanks a lot! Still trying to figure out how to use stack...

**Comment by tmcdonell** [comment]
Great!

Using stack to just build the example programs will be easier once I get all the packages onto Stackage, so I should [follow up](https://github.com/AccelerateHS/accelerate-llvm/issues/11) on that. This does raise an interesting point though, and I guess the stackage configuration will need to not build against the PTX backend. hmm..

Anyway this seems good now so closing. Let me know if you have any other problems (:

**Comment by nlw0** [comment]
I think my issue with stack was not related to accelerate, but to some weird incorrect setup in my box. Gotta investigate... But thanks, hope to have more interesting problems going forward. :)
