### ISSUE TITLE
Wrong number of arguments in printf

### ISSUE THREAD

**Issue by roboguy13** [AccelerateHS/accelerate#390]
There are at least two spots where `printf` is provided with the wrong number of arguments: [here](https://github.com/AccelerateHS/accelerate/blob/be851212c1f5c26e948b85c5e428207c78bdae16/Data/Array/Accelerate/Classes/RealFrac.hs#L165) and [here](https://github.com/AccelerateHS/accelerate/blob/22d49629ade9b9b8e93985362323b1259155df37/Data/Array/Accelerate/Classes/RealFloat.hs#L141).

As it stands, it looks like if you run into one of these outside of GHCi you just get the message `printf: argument list ended prematurely`. Inside GHCi, it looks like you get a partial printing of the format string.

Incidentally, on a slightly different topic (this is related to the specific error that I got. Maybe I should open a separate ticket): is it planned to implement `isInfinite` (I see that `isNaN` [looks like it's implemented](https://github.com/AccelerateHS/accelerate/issues/164))?

**Comment by tmcdonell** [comment]
derp ):

Thanks for the report. On the one hand, at least this is not on the critical path, but on the other the helpful error message itself fails \\:

Separate issue is for `isInfinite` best. No reason for not implementing it yet, I just didn't get around to it / forgot (always feel free to remind me about stuff like this).

**Comment by tmcdonell** [comment]
BTW I have added all the missing operations from `RealFloat` now.
