### ISSUE TITLE
Enable the use of accelerate-llvm without pinning git commits (i.e. add to Stackage)

### ISSUE THREAD

**Issue by rdnetto** [AccelerateHS/accelerate#393]
At present, it is necessary to add several packages to `stack.yaml` via git commits to use accelerate. This makes it much harder to get started with. Ideally, all of the packages should be in a LTS resolver.

To achieve this, we need to do the following:
* release a new version of `accelerate`
* release a new version of `accelerate-llvm`, which will depend on the new `accelerate`
* add the above versions, as well as `nvvm` to Stackage (instructions [here](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md))
* update `accelerate-examples` to have a Stack file which uses only the versions in the resolver.

It would be nice to have `accelerate-io` added as well, but it has a dependency on `repa` which is not in Stackage right now.

If there's anything I can do to help with this, just let me know.

**Comment by rdnetto** [comment]
I just realised that lts-9.1 contains `accelerate-1.0.0.0`, which improves things a bit. Unfortunately, the latest version of `accelerate-llvm` (1.0.0.0) doesn't accept `llvm-hs-pure-4.2.0, which is in the LTS, and the master version of `accelerate-llvm` requires `accelerate-1.1.*` and `cuda >= 0.8`, neither of which are in Hackage/Stackage yet. This means that the situation is unchanged - it's still necessary to pull everything from git.

**Comment by tmcdonell** [comment]
Yeah, I have been meaning to organise this for a while ):

I'm preparing new 1.1 releases and once they are out will see about getting those into stackage. I think all that needs to be done is:
 - [ ] check everything works with ghc-8.2
 - [ ] do something about [this](https://github.com/haskell/Cabal/issues/4677) (improve usability of new `accelerate-llvm-native` feature)

I'll ping Ben and see about getting repa updated too (I am sure others would like it back in stackage as well)

**Comment by rdnetto** [comment]
Awesome, thanks for the quick response. :)

**Comment by tmcdonell** [comment]
Should be in stackage nightly soon. https://github.com/fpco/stackage/pull/2880
