### ISSUE TITLE
Make a gitter room for Accelerate

### ISSUE THREAD

**Issue by NickSeagull** [AccelerateHS/accelerate#396]
I think it would be very useful to have one for discussing stuff in a more immediate fashion.

**Comment by tmcdonell** [comment]
hm, there seems to be https://gitter.im/AccelerateHS, but I don't think it is public? I am trying to find the settings...

**Comment by tmcdonell** [comment]
Ah, I had to create a lobby room first, this should work: https://gitter.im/AccelerateHS/Lobby

**Comment by NickSeagull** [comment]
Great, thanks!!
