### ISSUE TITLE
accelerate-llvm-native-1.1.0.1 | ghc-8.0.2-a | win10 | Internal error

### ISSUE THREAD

**Issue by oRole** [AccelerateHS/accelerate#401]
Hi, 

I'm using GHC 8.02a, Windows 10 with MSYS/Mingw64-bit and LLVM-5.0.0. The installation of accelerate-llvm-native-1.1.0.1 worked just fine, but when I run my application I get the following error:

```
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
.\Data\Array\Accelerate\LLVM\Native\Link\COFF.hs:34:3: (loadObject): not implemented yet: https://github.com/AccelerateHS/accelerate/issues/395
CallStack (from HasCallStack):
  error, called at .\Data\Array\Accelerate\LLVM\Native\Link\COFF.hs:34:3 in accelerate-llvm-native-1.1.0.1-2HNR34BMm9rGF1GAAf7UUB:Data.Array.Accelerate.LLVM.Native.Link.COFF
```

I saw that there is already an issue stating that the loadObject method is not implemented yet. ([Issue 395](https://github.com/AccelerateHS/accelerate/issues/395)). Are there any updates planned?

**Comment by tmcdonell** [comment]
Hi! Sorry, I only just saw this and your other bug report ):

Hm, ok. I will try and get access to a windows box or set up a VM.

**Comment by oRole** [comment]
Hi! Don't worry! Please see my reply to issue [#400](https://github.com/AccelerateHS/accelerate/issues/400#issuecomment-339522762). As I'm the only one that complains about that, I don't want you to end up with too much work. I just switched to accelerate-cuda.

**Comment by NickSeagull** [comment]
If its worth something, I've faced the same issue on Windows, but I ended up using a Vagrant box.

**Comment by tmcdonell** [comment]
Closing as dup of #395 to keep the comments in one place.
