### ISSUE TITLE
CUDA Exception: invalid device ordinal

### ISSUE THREAD

**Issue by amcphail** [AccelerateHS/accelerate#403]
[slurm-65968200.txt](https://github.com/AccelerateHS/accelerate/files/1451788/slurm-65968200.txt)

I can supply more information if requested.

**Comment by tmcdonell** [comment]
Hi!

1. is this a multi-gpu system?

2. could you send the result of running `nvidia-device-query` please

3. can you try using the github version of the code?

**Comment by amcphail** [comment]
Hi,

1. This is running on a cluster.  The particular details for the node I used are:


Name | Nodes | CPUs | Architecture | Speed(GHz) | CPUcores | Coprocessors/ GPUs | Memory(GB) | CPU cores | Coprocessor cores
GPGPU d | 5 | 2 x Intel E5-2680 | Sandy Bridge | 2.7 | 16 | 2 x  NVIDIA K20X | 128 | 80 | 24,960 (Kepler)

So yes, it looks like there are 2 GPUs per node.

2. I cannot find the executable `nvidia-device-query` there is `nvidia-settings` among others.

3. I shall attempt to build the github version.

**Comment by tmcdonell** [comment]
The `nvidia-device-query` program is part of the `cuda` Haskell bindings package. If you built your program with `stack` it would be available via `stack exec nvidia-device-query`, for example.

The github version has some improvements to handling multiple GPUs that are in exclusive mode (this is the only circumstance I have seen the `invalid device ordinal` error before)

**Comment by amcphail** [comment]
Here is the output of `nvidia-device-query` but I'm not convinced it was run on the node that caused the error.  The cluster has a number of different GPU nodes.

[nvidia-device-query.txt](https://github.com/AccelerateHS/accelerate/files/1455193/nvidia-device-query.txt)

**Comment by tmcdonell** [comment]
Thanks. That at least shows that the GPUs in that cluster run in exclusive mode. If your application uses multiple threads each trying to run on the GPU at the same time, that might be the source of the problem?

If you can post a small test case (or a link to your code) I can have a closer look.

**Comment by tmcdonell** [comment]
I think you managed to get accelerate working, so closing this. Feel free to reopen/create a new ticket if you still have issues with this machine (:
