### ISSUE TITLE
Unhelpful error message with nested parallelism

### ISSUE THREAD

**Issue by Taneb** [AccelerateHS/accelerate#405]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

I am trying to learn how to use `accelerate`, and when writing a matrix-vector multiplication function, I received a confusing and unhelpful error message which is apparently an internal error

## Expected behaviour

Either my code working, or a more helpful error message explaining what I have done wrong

## Current behaviour

```
*** Exception: 
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/Trafo/Sharing.hs:664:9: (convertSharingExp): inconsistent valuation @ shared 'Exp' tree with stable name 22;
  env' = [24]
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/Trafo/Sharing.hs:664:9 in accelerate-1.1.1.0-AzKRKrVIGrPBUoMkFIZ7Sm:Data.Array.Accelerate.Trafo.Sharing
```

## Steps to reproduce (for bugs)

```
{-# LANGUAGE RebindableSyntax #-}
module Matrix where

import Data.Array.Accelerate
import Data.Array.Accelerate.Interpreter

type Matrix = Array DIM2

(!*) :: Acc (Matrix Int) -> Acc (Vector Int) -> Acc (Vector Int)
a !* b = 
  let
    i, j, k :: Exp Int
    Z :. i :. j = unlift (shape a)
    Z :. k = unlift (shape b)
  in generate (lift $ Z :. i) $ \ix ->
    let
      m :: Exp Int
      Z :. m = unlift ix
    in the $ sum $ generate (lift $ Z :. j) $ \ix' ->
      let
        n :: Exp Int
        Z :. n = unlift ix'
      in (a ! lift (Z :. m :. n))

-- some testing arrays

a :: Acc (Matrix Int)
a = use $ fromList (Z:.2:.2) [1,1,1,0]

b :: Acc (Vector Int)
b = use $ fromList (Z:.2) [1,0]


-- exhibits bug

bug :: Vector Int
bug = run $ a !* b
```
## Your environment

- Version used: accelerate-1.1.1.0
- Backend(s) used and version: Interpreter
- Operating system and version: NixOS 17.10
- Link to your project:
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:

**Comment by tmcdonell** [comment]
I agree, this is not a good error message.

I wonder if it is possible to get some information about where in the user code this error came from, so we can point it back to (in this case), the use of `the` and on which line. hmm...

**Comment by tmcdonell** [comment]
I have improved the error message at least, so closing for now. Thanks again for the report!
