### ISSUE TITLE
Linker error with native runQ

### ISSUE THREAD

**Issue by samft** [AccelerateHS/accelerate#406]
I'm having trouble with Data.Array.Accelerate.LLVM.Native.runQ when used in a library, or when it is running an Accelerate program defined in a library.

I've put up some minimal tests at [https://github.com/samft/accelerate-minimal-tests](https://github.com/samft/accelerate-minimal-tests). All the examples with runN work, whatever way I structure the project. But:

- if I use runQ in a library, though the library itself compiles, I get a linker error if I then try and use the library from an executable (see runq-exe-from-lib).
- if I define the accelerate program by a test function in a library, and then try to runQ it from an executable, I also get a linker error (see runq-exe-from-funclib).

I've tested on both macOS 10.13.1 and Ubuntu 17.10, and get equivalent errors. On macOS the error for the first case is:
```
Configuring runq-exe-0.1.0.0...
Preprocessing executable 'runq-exe-from-lib' for runq-exe-0.1.0.0..
Building executable 'runq-exe-from-lib' for runq-exe-0.1.0.0..
[1 of 1] Compiling Main             ( Main.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/runq-exe-from-lib/runq-exe-from-lib-tmp/Main.o )
Linking .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/runq-exe-from-lib/runq-exe-from-lib ...
Undefined symbols for architecture x86_64:
  "_map_fa818c972a85ead9", referenced from:
      _runqzmlibzm0zi1zi0zi0zm1DL5Vy02ayVLaLOlt917Bm_Lib_libFunc17_closure in libHSrunq-lib-0.1.0.0-1DL5Vy02ayVLaLOlt917Bm.a(Lib.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
```

And for the second I get the almost identical:
```
Configuring runq-exe-0.1.0.0...
Preprocessing executable 'runq-exe-from-funclib' for runq-exe-0.1.0.0..
Building executable 'runq-exe-from-funclib' for runq-exe-0.1.0.0..
[1 of 1] Compiling Main             ( Main.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/runq-exe-from-funclib/runq-exe-from-funclib-tmp/Main.o ) [Data.Array.Accelerate.LLVM.Native changed]
Data.Array.Accelerate.LLVM.Native.Plugin: linking module ‘Main’ with:
  /Users/samft/.accelerate/accelerate-llvm-1.1.0.0/accelerate-llvm-native-1.1.0.1/x86_64-apple-darwin17.2.0/ivybridge/rel/meepFA81BC970D55EAD9.o

Linking .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/runq-exe-from-funclib/runq-exe-from-funclib ...
Undefined symbols for architecture x86_64:
  "_map_fa81bc970d55ead9", referenced from:
      _Main_zuzuacceleratezullvmzunativezu4202fd5ae0_closure in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to seeinvocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
```

Thanks for any help!

**Comment by tmcdonell** [comment]
Whoa, thanks for the very comprehensive examples! (:
I can reproduce this on my machine. Will take a look asap.

**Comment by tmcdonell** [comment]
Once [GHC#14298](https://ghc.haskell.org/trac/ghc/ticket/14298) lands we can start to move away from this plugin approach.
