### ISSUE TITLE
map-ping causes error: (convertSharingExp): inconsistent valuation @ shared 'Exp' tree with stable name 357

### ISSUE THREAD

**Issue by considerate** [AccelerateHS/accelerate#408]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

I'm trying to write an AI for playing the game Othello. Currently I'm porting some of the game logic to Accelerate.
I have written a function called `canPlace` that takes a colour of the next player to play and the current
board configuration and a position on the board. This function return an `Exp Bool` with True if the player can place at the specific position. With manual testing I can verify that the function gives the
correct result for all positions. However, when I try to map this function over an `Array DIM2 DIM2` containing the positions I get the following error:

```Haskell
*Main Board BoardAcc Replicate CPU Data.Array.Accelerate> CPU.run positions 
Matrix (Z :. 8 :. 8) 
  [Z :. 0 :. 0,Z :. 0 :. 1,Z :. 0 :. 2,Z :. 0 :. 3,Z :. 0 :. 4,Z :. 0 :. 5,Z :. 0 :. 6,Z :. 0 :. 7,
   Z :. 1 :. 0,Z :. 1 :. 1,Z :. 1 :. 2,Z :. 1 :. 3,Z :. 1 :. 4,Z :. 1 :. 5,Z :. 1 :. 6,Z :. 1 :. 7,
   Z :. 2 :. 0,Z :. 2 :. 1,Z :. 2 :. 2,Z :. 2 :. 3,Z :. 2 :. 4,Z :. 2 :. 5,Z :. 2 :. 6,Z :. 2 :. 7,
   Z :. 3 :. 0,Z :. 3 :. 1,Z :. 3 :. 2,Z :. 3 :. 3,Z :. 3 :. 4,Z :. 3 :. 5,Z :. 3 :. 6,Z :. 3 :. 7,
   Z :. 4 :. 0,Z :. 4 :. 1,Z :. 4 :. 2,Z :. 4 :. 3,Z :. 4 :. 4,Z :. 4 :. 5,Z :. 4 :. 6,Z :. 4 :. 7,
   Z :. 5 :. 0,Z :. 5 :. 1,Z :. 5 :. 2,Z :. 5 :. 3,Z :. 5 :. 4,Z :. 5 :. 5,Z :. 5 :. 6,Z :. 5 :. 7,
   Z :. 6 :. 0,Z :. 6 :. 1,Z :. 6 :. 2,Z :. 6 :. 3,Z :. 6 :. 4,Z :. 6 :. 5,Z :. 6 :. 6,Z :. 6 :. 7,
   Z :. 7 :. 0,Z :. 7 :. 1,Z :. 7 :. 2,Z :. 7 :. 3,Z :. 7 :. 4,Z :. 7 :. 5,Z :. 7 :. 6,Z :. 7 :. 7]
*Main Board BoardAcc Replicate CPU Data.Array.Accelerate> CPU.run $ Data.Array.Accelerate.map (canPlace blackTile initialBoard) positions
*** Exception: 
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/Trafo/Sharing.hs:664:9: (convertSharingExp): inconsistent valuation @ shared 'Exp' tree with stable name 357;
  env' = [288,298,280]
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/Trafo/Sharing.hs:664:9 in accelerate-1.1.0.0-7lmA6RvdcM24Zj46B405wk:Data.Array.Accelerate.Trafo.Sharing
```

## Expected behaviour

```Haskell
*Main Board BoardAcc Replicate CPU Data.Array.Accelerate> CPU.run $ Data.Array.Accelerate.map (canPlace blackTile initialBoard) positions
Matrix (Z :. 8 :. 8) 
  [False,False,False,False,False,False,False,False,
   False,False,False,False,False,False,False,False,
   False,False,False,True,False,False,False,False,
   False,False,True,False,False,False,False,False,
   False,False,False,False,False,True,False,False,
   False,False,False,False,True,False,False,False,
   False,False,False,False,False,False,False,False,
   False,False,False,False,False,False,False,False]
```
## Current behaviour

Currently, I get the above error noting inconsistent valuation of shared 'Exp'.

## Steps to reproduce (for bugs)

https://gist.github.com/considerate/b14fa091be6687c6a0e8ca6eb0a3dd13
 1. Run `map (canPlace blackTile initialBoard) positions`

## Your environment

- Version used: accelerate-1.1.0.0
- Backend(s) used and version: accelerate-llvm-native
- Operating system and version: macOS High Sierra 10.13.1

**Comment by considerate** [comment]
Is this a case of nested parallelism because the `initialBoard` passed to `canPlace` is of type `Acc (Array DIM2 Int)` and `positions` is of type `Acc (Array DIM2 DIM2)`?
If so, how could I go about avoiding this nesting? I ultimately want to use this to generate all possible moves from the current board configuration and would like to have the final function `nextMoves :: Player -> Acc (Array DIM2 Int) -> Acc (Array DIM3 Int)`.

**Comment by tmcdonell** [comment]
Yes, the error is due to nested parallelism. Most likely this is due to the use of [`the`](http://hackage.haskell.org/package/accelerate-1.1.1.0/docs/Data-Array-Accelerate.html#v:the) in the function `canPlace`.

However, since the `directions` array is constant, I managed to avoid it like this:

```haskell
directions :: [Exp DIM2]
directions = [constant (Z :. dy :. dx)
    | dx <- [-1,0,1] :: [Int]
    , dy <- [-1,0,1] :: [Int]
    , P.not (dx P.== 0 P.&& dy P.== 0)
    ]

canPlace :: Exp Int -> Board -> Exp DIM2 -> Exp Bool
canPlace me board index = freeTile && canCapture
  where
    freeTile       = (getTile board index) == emptyTile
    captureLengths = P.map (captureRow me board index) directions
    canCapture     = P.foldl (||) (constant False) (P.map (> 0) captureLengths)
```

Hope that helps (and is still useful for your `nextMoves` function)!

**Comment by considerate** [comment]
Thank you very much for your quick response! It does indeed seem like the cause of the error was due to the `the` function. I must admit that the nested-parallelism restriction causes me to reason about my code in ways I'm not yet familiar with.

Once again, thank you for taking the time to look at this and even present a solution.
