### ISSUE TITLE
unrecognized gpu name

### ISSUE THREAD

**Issue by JonathanFraser** [AccelerateHS/accelerate#410]
I am submitting a...
- [x] bug report
- [ ] feature request

## Description
accelerate runs fine with interpreter and native backends however, the ptx backend throws an error. The error seems to indicat and unrecognized gpu. 

## Expected behaviour
Expect the gpu code to be compiled successfully

## Current behaviour
on running ptx.run it throws this error

```
"*** Exception:
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/LLVM/PTX/Compile.hs:195:24: (compile): ptxas - -o /home/binaryblade/.accelerate/accelerate-ll
vm-1.1.0.0/accelerate-llvm-ptx-1.1.0.1/nvptx64-nvidia-cuda/ptx40/rel/morpF807D1E151E6A2B5.sass -arch=sm_21 (exit 255)
ptxas fatal   : Value 'sm_21' is not defined for option 'gpu-name'

CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/LLVM/PTX/Compile.hs:195:24 in accelerate-llvm-ptx-1.1.0.1-Ji8KJ5iYokFBMCSD
KQlM71:Data.Array.Accelerate.LLVM.PTX.Compile
```

## Possible solution (optional)
unknown

## Steps to reproduce (for bugs)
running a computation on the ptx backend

## Your environment

- Version used: 1.1.0.1 accelerate-llvm-ptx
- Backend(s) used and version: accelerate-llvm-ptx
- Operating system and version: gentoo (kernel-4.14.11)
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:
```
CUDA device query (Driver API, statically linked)
CUDA driver version 9.1
CUDA API version 9.0
Detected 1 CUDA capable device

Device 0: GeForce GTX 560M
  CUDA capability:                    2.1
  CUDA cores:                         192 cores in 4 multiprocessors (48 cores/MP)
  Global memory:                      3 GB
  Constant memory:                    64 kB
  Shared memory per block:            48 kB
  Registers per block:                32768
  Warp size:                          32
  Maximum threads per multiprocessor: 1536
  Maximum threads per block:          1024
  Maximum grid dimensions:            65535 x 65535 x 65535
  Maximum block dimensions:           1024 x 1024 x 64
  GPU clock rate:                     1.55 GHz
  Memory clock rate:                  1.25 GHz
  Memory bus width:                   192-bit
  L2 cache size:                      384 kB
  Maximum texture dimensions         
    1D:                               65536
    2D:                               65536 x 65535
    3D:                               2048 x 2048 x 2048
  Texture alignment:                  512 B
  Maximum memory pitch:               2 GB
  Concurrent kernel execution:        Yes
  Concurrent copy and execution:      Yes, with 1 copy engine
  Runtime limit on kernel execution:  Yes
  Integrated GPU sharing host memory: No
  Host page-locked memory mapping:    Yes
  ECC memory support:                 No
  Unified addressing (UVA):           Yes
  PCI bus/location:                   1/0
  Compute mode:                       Default
    Multiple contexts are allowed on the device simultaneously
```

**Comment by tmcdonell** [comment]
I think your GPU architecture has been deprecated in CUDA-9.x. I get the same error from nvcc-9.1 when trying to compile regular CUDA code (not via accelerate) for 2.x.

Try installing CUDA-8, which can still be found [here](https://developer.nvidia.com/cuda-toolkit-archive).

Note that you'll need to reinstall the `cuda` package to make sure that it builds against the new toolkit version correctly. Something like `stack exec ghc-pkg -- unregister cuda --force` should be enough to force that to happen. You can check with something like:

```
ghci> import Foreign.CUDA.Driver as CUDA
ghci> CUDA.libraryVersion
8000
```

**Comment by JonathanFraser** [comment]
It appears you are correct, according to the wikipage cuda dropped support for 2.x devices in version 9.0.
