### ISSUE TITLE
Not sure how to iterate

### ISSUE THREAD

**Issue by JonathanFraser** [AccelerateHS/accelerate#411]
I am submitting a...
- [ ] bug report
- [ ] feature request
- [x] support request 

## Description
I am trying to iterate a differential equation many times, however it seems to be causing a CUDA memory exhaustion. 

The code is [here](https://gist.github.com/JonathanFraser/244b05a2b07624eab1e45e649f243893)

and I am invoking with 
`res = programAdvance start 1000000`

it was my presumption that this would round trip back to system memory. Perhaps this isn't the case? Either way, this should be memory bound at 2 * 1000 Doubles.

## Expected behaviour
It would produce the result of iterating 1000000 times

## Current behaviour
we get an exception 
```
"*** Exception:
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/LLVM/PTX/State.hs:51:9: (unhandled): CUDA Exception: out of memory
CallStack (from HasCallStack):
  error, called at ./Data/Array/Accelerate/LLVM/PTX/State.hs:51:9 in accelerate-llvm-ptx-1.1.0.1-8NhWjfu2YCQKd9GJCFX9eZ:Data.Array.Accelerate.LLVM.PTX.State
```

## Steps to reproduce (for bugs)
see code gist

## Your environment
- Version used: 1.1.1.0
- Backend(s) used and version: llvm-ptx
- Operating system and version: gentoo 4.14.11-r2
- Link to your project: N/A
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:
```
CUDA device query (Driver API, statically linked)
CUDA driver version 9.1
CUDA API version 9.0
Detected 1 CUDA capable device

Device 0: Quadro K620
  CUDA capability:                    5.0
  CUDA cores:                         384 cores in 3 multiprocessors (128 cores/MP)
  Global memory:                      2 GB
  Constant memory:                    64 kB
  Shared memory per block:            48 kB
  Registers per block:                65536
  Warp size:                          32
  Maximum threads per multiprocessor: 2048
  Maximum threads per block:          1024
  Maximum grid dimensions:            2147483647 x 65535 x 65535
  Maximum block dimensions:           1024 x 1024 x 64
  GPU clock rate:                     1.124 GHz
  Memory clock rate:                  900.0 MHz
  Memory bus width:                   128-bit
  L2 cache size:                      2 MB
  Maximum texture dimensions         
    1D:                               65536
    2D:                               65536 x 65536
    3D:                               4096 x 4096 x 4096
  Texture alignment:                  512 B
  Maximum memory pitch:               2 GB
  Concurrent kernel execution:        Yes
  Concurrent copy and execution:      Yes, with 1 copy engine
  Runtime limit on kernel execution:  Yes
  Integrated GPU sharing host memory: No
  Host page-locked memory mapping:    Yes
  ECC memory support:                 No
  Unified addressing (UVA):           Yes
  PCI bus/location:                   1/0
  Compute mode:                       Default
    Multiple contexts are allowed on the device simultaneously
```

**Comment by tmcdonell** [comment]
Strangely enough, this works in HEAD, thought I don't think I made any relevant changes to make it so. I can reproduce this with the 1.1 release though.

It is easy enough to fix though by changing `programAdvance` to a left fold.

```haskell
programAdvance :: State -> Int -> State
programAdvance initial count = P.foldl' (\state _ -> programRun state) initial [0..count-1]
```

With the left fold it is clearer to GHC that the old program state can be discarded immediately, and we can free up that device memory.

#### coda

Running in debug mode with `+ACC -ddump-gc-stats -ACC` is indicative:

with `foldr`:
```
[ 237.911] gc: 24,000 bytes allocated locally
[ 237.911] gc: 444,751,872 bytes allocated on the remote device
[ 237.911] gc: 8,000 bytes copied to the remote device
[ 237.911] gc: 24,000 bytes copied from the remote device
[ 237.911] gc: 3 bytes evicted from the remote (3 evictions, 3 GCs)
```

with `foldl`:
```
[ 206.105] gc: 24,000 bytes allocated locally
[ 206.105] gc: 3,850,240 bytes allocated on the remote device
[ 206.105] gc: 8,000 bytes copied to the remote device
[ 206.105] gc: 24,000 bytes copied from the remote device
[ 206.105] gc: 0 bytes evicted from the remote (0 evictions, 0 GCs)
```

The last line, number of evictions, is the important one here (though the number of bytes evicted seems wrong; I'm probably just printing out the wrong counter). It suggests the `foldr` version is keeping around the intermediate results for too long, and at some point we run out of device memory and have to forcibly evict stuff; I'm not sure why that eviction process isn't working with 1.1 though. Sadly I didn't record the high-water mark; that would have been the most relevant thing here \\:

**Comment by tmcdonell** [comment]
Oh, in this case the "bytes allocated on the remote device" field is a pretty good approximation for the high-water mark; you can see the difference...

**Comment by JonathanFraser** [comment]
I can see how a `foldl` might be more efficient, however my prelude seems to not export the strict version of it `foldl'`.  Not sure what the deal is there, `i'm running ghc-8.0.2`

**Comment by tmcdonell** [comment]
Oh, I imported that from [`Data.List`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-List.html#v:foldl-39-). Sorry for the confusion!
