### ISSUE TITLE
Failed to load interface for `Data.Array.Accelerate.IO' 

### ISSUE THREAD

**Issue by amcphail** [AccelerateHS/accelerate#413]
I am submitting a...
- [x ] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Current behaviour
/gpfs1m/projects/uoa00057/amcp011/accelerate/test-io/src/Numeric/GPE/SaveData.hs:29:1: error:
    Failed to load interface for ‘Data.Array.Accelerate.IO’
    Perhaps you meant
      Data.Array.Accelerate (from accelerate-1.2.0.0)
      Data.Array.Accelerate.AST (from accelerate-1.2.0.0)
      Data.Array.Accelerate.Lift
    Use -v to see a list of the files searched for.

## Your environment

[amcp011@build-sb test-io]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2

[amcp011@build-sb test-io]$ cabal --version
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library 

[amcp011@build-sb test-io]$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0

[amcp011@build-sb test-io]$ uname -a
Linux build-sb 2.6.32-279.14.1.el6.x86_64 #1 SMP Mon Oct 15 13:44:51 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by amcphail** [comment]
I am submitting a...
- [x ] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

When attempting to use the latest version from github of accelerate-io ghc fails to find the interface


## Expected behaviour


Expect compile to complete.

## Current behaviour
/gpfs1m/projects/uoa00057/amcp011/accelerate/test-io/src/Numeric/GPE/SaveData.hs:29:1: error:
    Failed to load interface for ‘Data.Array.Accelerate.IO’
    Perhaps you meant
      Data.Array.Accelerate (from accelerate-1.2.0.0)
      Data.Array.Accelerate.AST (from accelerate-1.2.0.0)
      Data.Array.Accelerate.Lift
    Use -v to see a list of the files searched for.


## Possible solution (optional)


## Steps to reproduce (for bugs)

`stack build` of the following package:

[gpe-0.1.0.0.tar.gz](https://github.com/AccelerateHS/accelerate/files/1637304/gpe-0.1.0.0.tar.gz)

## Your environment


[amcp011@build-sb test-io]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2

[amcp011@build-sb test-io]$ cabal --version
cabal-install version 1.16.0.2
using version 1.16.0 of the Cabal library 

[amcp011@build-sb test-io]$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0

[amcp011@build-sb test-io]$ uname -a
Linux build-sb 2.6.32-279.14.1.el6.x86_64 #1 SMP Mon Oct 15 13:44:51 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tmcdonell** [comment]
I've changed the interface for `accelerate-io` for the next version, to split the different conversion routines into their own modules, rather than all be exported from the single `Data.Array.Accelerate.IO` module.

There are haddocks for the new version here: http://tmcdonell-bot.github.io/accelerate-travis-buildbot/accelerate-io-1.1.0.0/index.html . It looks like you just need to change the import to `Data.Array.Accelerate.IO.Data.ByteString` instead?

**Comment by amcphail** [comment]
Hi,

Apologies for not looking at the new documentation.  I was going off the hackage documentation.

I am in need of `toPtr` from the `BlockPtrs` section as well as the `ByteStrings` `toByteString` function (note the plural).  Have these been deprecated?

**Comment by tmcdonell** [comment]
Oh, yes good point, I guess these got lost in the reorganisation... I should add those back.

**Comment by tmcdonell** [comment]
I've re-added the `from/toPtrs` and `from/toBytestrings` functions. Note that they are different from the previous versions in that they are non-copying, so don't modify the originals after converting to Accelerate, etc...

Hopefully this works for you now (:

**Comment by amcphail** [comment]
Could you also re-add:

The `BlockPtrs` interface:

`toPtr :: (Shape sh, Elt e) => Array sh e -> BlockPtrs (EltRepr e) -> IO ()`  and `fromPtr`

I take it you are aware that the `to/fromByteStrings` functions used to live in the IO monad.  Is this change because they are non-copying?

**Comment by tmcdonell** [comment]
I'm not sure why the `BlockPtrs` interface is still required?

And yes, the conversion functions no longer live in `IO` because they are non-copying, which is what I am aiming for all functions in the library to be.

**Comment by amcphail** [comment]
Okay, I don't need the `BlockPtrs` interface.  I was allocating the arrays myself which I no longer need to do.  I have no further requests --- I have working code now.

Thanks!
