### ISSUE TITLE
Add Generic.Vector instance to Array DIM1 

### ISSUE THREAD

**Issue by ocramz** [AccelerateHS/accelerate#419]
I am submitting a...
- [ ] bug report
- [x] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

Currently, `Array DIM1` has an IsList instance (https://hackage.haskell.org/package/accelerate-1.1.1.0/docs/src/Data-Array-Accelerate-Array-Sugar.html#line-914), but it would be handy if there were a Generic.Vector (http://hackage.haskell.org/package/vector-0.12.0.1/docs/src/Data.Vector.Generic.Base.html#Vector) interface as well.

## Possible solution (optional)

First of all, `accelerate` should import `vector`. The new transitive dependencies introduced by this are `semigroups`, `primitive`, and their respective dependencies.

```
import qualified Data.Vector.Generic.Mutable.Base as GMV
import qualified Data.Vector.Generic as GV
```

The instance would need to first provide a witness `GMV.MVector (Mutable (Array DIM1)) e => Array DIM1 e`, and subsequently `Elt e => GV.Vector (Array DIM1) e`

The instance would look something like `(MVector (Mutable v) e, Elt e) => GV.Vector (Array DIM1) e`.

**Comment by tmcdonell** [comment]
If I understand correctly, this would then allow a `Data.Vector` computation to store its result directly into an array usable by Accelerate? That sounds like a good idea.
