### ISSUE TITLE
cuDNN support?

### ISSUE THREAD

**Issue by jhoxray** [AccelerateHS/accelerate#421]
I am submitting a...
- [ ] bug report
- [x] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description
Hi! My apologies if this is not the right place to ask, but are there any plans to extend Accelerate to support not just CUDA but also cuDNN library to make it more efficient for deep learning tasks? Has there any work been done on the topic? We are considering getting into this, but since Accelerate is so good working with CUDA trying to understand the state of things first. Thank you!

- Jay

**Comment by tmcdonell** [comment]
Hi Jay!

I currently don't have any specific plans to add cuDNN interoperability myself, but I believe everything that would be required is in there (e.g. support for float-16, packed (AoS) arrays).

I think the process would be similar to the implementation of, e.g. the [`accelerate-fft`](https://hackage.haskell.org/package/accelerate-fft) and [`accelerate-blas`](https://hackage.haskell.org/package/accelerate-blas) libraries. The first step is writing the raw FFI bindings ([`cufft`](https://hackage.haskell.org/package/cufft), [`cublas`](https://hackage.haskell.org/package/cublas), respectively), which can then be wrapped into an API usable from Accelerate. I could help you out of course.

Depending on how you plan to use Accelerate together with cuDNN (e.g. at the start/end of a long cuDNN pipeline vs. intermixed between cuDNN steps) probably affects how much work needs to be put into that second step. I haven't used cuDNN myself so I'm not sure where the most important points are.

Cheers!

**Comment by jhoxray** [comment]
Trevor, thanks a lot, this helps clarify this! If we get to the Accelerate integration step will ping :)
