### ISSUE TITLE
Wierd WHNF case for a random array

### ISSUE THREAD

**Issue by fabricatedmath** [AccelerateHS/accelerate#422]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

I have a gist that illustrates the issue [here](https://gist.github.com/cpdurham/069cb85e0c4efa4b1ceb67124e40a5cd). 

Ran into this issue where I use the accelerate mwc random package to yield some random values, I then multiply them against a non-forced fromFunction array and I get all zeros as the output going through llvm-ptx. However if I force the fromFunction array, everything works as expected. Strangely, if I grab values with a fromList instead of the randomArray call, everything also works as expected regardless of the fromFunction array being forced.

Gist is much more descriptive

## Your environment

Gist includes a stack.yaml file [here](https://gist.github.com/cpdurham/069cb85e0c4efa4b1ceb67124e40a5cd)

Thought this was worth a mention because I was getting a mvar lock error dealing with similar whnf issues in the past.

**Comment by tmcdonell** [comment]
I was able to reproduce this on a ubuntu machine. Interestingly, the problem goes away with ghc-8.4 (I used nightly-2018-05-15). I'm not sure exactly what is going on here; will try and dig around a bit.
