### ISSUE TITLE
aiterate written in terms of awhile seems really slow

### ISSUE THREAD

**Issue by cpdurham** [AccelerateHS/accelerate#424]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

I wrote a bare bones aiterate function which just takes a count and counts down inside an awhile function, tupling the (Acc a -> Acc a) result and the counter, and it's really slow. I'm getting ~7.6 seconds for 10,000 iterations on a Titan X (Pascal) when I do (A.map (+1))  for the (Acc a -> Acc a) function on a one element Vector)

I know it's apples to oranges, but a comparable program in pytorch is getting 0.16 seconds in cuda on a 1 element array. I'm not sure what kinds of optimizations they do on the AST, but even an array with 1,000,000 elements iterated 10,000 times with a non-trivial function (i.e. log(x*4-1)) is getting 0.43 seconds in pytorch. 

Strangely the accelerate program is the same amount of time for a Vector of size 1,000,000 as it is for a Vector of size 1, ~7.6 seconds

I'm curious if it's because there's some sort of memory transfer between iterations?

Example gist in link below 

## Your environment

- Accelerate version: 1.2.0.0
- Accelerate backend(s) used: accelerate-llvm-ptx
- GHC version: 8.2.2
- Operating system and version: Ubuntu 16.04
- Link to your project/example:  https://gist.github.com/cpdurham/7719adb0dbb0091b35082deeecaff474
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:
```
CUDA device query (Driver API, statically linked)
CUDA driver version 9.1
CUDA API version 9.1
Detected 1 CUDA capable device

Device 0: TITAN X (Pascal)
  CUDA capability:                    6.1
  CUDA cores:                         3584 cores in 28 multiprocessors (128 cores/MP)
  Global memory:                      12 GB
  Constant memory:                    64 kB
  Shared memory per block:            48 kB
  Registers per block:                65536
  Warp size:                          32
  Maximum threads per multiprocessor: 2048
  Maximum threads per block:          1024
  Maximum grid dimensions:            2147483647 x 65535 x 65535
  Maximum block dimensions:           1024 x 1024 x 64
  GPU clock rate:                     1.531 GHz
  Memory clock rate:                  5.005 GHz
  Memory bus width:                   384-bit
  L2 cache size:                      3 MB
  Maximum texture dimensions         
    1D:                               131072
    2D:                               131072 x 65536
    3D:                               16384 x 16384 x 16384
  Texture alignment:                  512 B
  Maximum memory pitch:               2 GB
  Concurrent kernel execution:        Yes
  Concurrent copy and execution:      Yes, with 2 copy engines
  Runtime limit on kernel execution:  Yes
  Integrated GPU sharing host memory: No
  Host page-locked memory mapping:    Yes
  ECC memory support:                 No
  Unified addressing (UVA):           Yes
  PCI bus/location:                   1/0
  Compute mode:                       Default
    Multiple contexts are allowed on the device simultaneously
```

**Comment by cpdurham** [comment]
Interesting, I guess that would make sense, I always thought a kernel launch was super expensive but looks like its ~0.01 ms => 10,000*0.01 = 0.1 seconds which looks about right for your guess for the pytorch example.

Yeah, and just ran your loop example on a vector of size 1 and i'm getting
```
real	0m0.592s
user	0m0.644s
sys	0m0.195s
```
Much closer :)

So with my aiterate vs your loop code, where is your loop code storing the array it's working on in between invocations that makes it that much faster than storing a counter in gpu memory?

**Comment by tmcdonell** [comment]
In all the cases the array it is working on is stored in GPU memory (everything of type `Acc` and `Exp` will be in GPU memory). Due to the way that `run*` works, it only transfers the results back to the CPU when necessary, so despite the multiple calls to `run` will _only_ live in GPU memory, until it needs to  print out the final sum.

With pytorch and my `loop` code, the loop counter is only on the CPU.

In the `aiterate` code, the loop counter is updated and stored on the GPU, so at every iteration it needs to copy that value back to the CPU to decide whether to continue the loop or exit. You can see the implementation of that [here](https://github.com/AccelerateHS/accelerate-llvm/blob/master/accelerate-llvm/src/Data/Array/Accelerate/LLVM/Execute.hs#L406), with the call to `indexRemote` doing the transfer from the GPU back to the CPU.

**Comment by cpdurham** [comment]
Oh, that makes a lot of sense, I figured that the awhile condition was somehow lifted to reside only inside the cuda kernels. Now that I think about it, that would only be possible generally with dynamic parallelism support, right?

**Comment by tmcdonell** [comment]
Correct, we'd need dynamic parallelism support to be able to do that (plus a lot of other changes too, I imagine).

I think this is okay to close now?

**Comment by cpdurham** [comment]
Yeah, thanks for the help!
