### ISSUE TITLE
Potential PTX Bad Compilation of 'filter'.

### ISSUE THREAD

**Issue by TravisWhitaker** [AccelerateHS/accelerate#427]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description
I have a function like this:

```Haskell
indicesOfTruth :: Acc (Array DIM2 Bool) -> Acc (Vector (Int, Int))
indicesOfTruth xs =
    let withInds :: Acc (Array DIM2 (Int, Int, Bool))
        withInds = imap addInds xs
        addInds :: Exp DIM2 -> Exp Bool -> Exp (Int, Int, Bool)
        adInds dim b = let x :: Exp Int
                           y :: Exp Int
                          (Z :. y :. x) = unlift dim
                       in lift (x, y, b)
        accept :: Exp (Int, Int, Bool) -> Exp Bool
        accept (unlift -> (x, y, b)) = b
        dropBool :: Exp (Int, Int, Bool) -> Exp (Int, Int)
        dropBool t = let x :: Exp Int
                         y :: Exp Int
                         b :: Exp Bool
                         (x, y, z) = unlift t
                     in lift (x, y)
    in map dropBool (afst (filter accept withInds))
```
When using the PTX backend this function non-deterministically fails with an invalid memory access. I can't seem to trigger the same failure when using the interpreter or the native LLVM backend. Strangely, whether or not this function fails seems to depend on the aspect ratio of the input array. I can't get it to fail on an array with a 1-to-64 aspect ratio, and it almost always fails on an array with a 1-to-8 aspect ratio.

I'm using the following revs:
- accelerate: b291fb83589e5e0fc94db687a92badd1c1b9c7d9
- accelerate-llvm: 18bee9373fd2dc92834ab6e0d42ff5a7c3b786f8
- GHC 8.4.3
- Nvidia driver 390.67
- GTX 1080TI (compute cap 6.1)

I've built accelerate components with `-fbounds-checks -funsafe-checks -finternal-checks`. `accelerage-llvm-ptx`'s test suite passes on this same system.

For what it's worth, the reason I'm not simply using `map fst . afst . filter snd . indexed` (which I need to play around with a bit to see if it has the same problems...) is simply because I've reduced a much larger definition to this minimal failing case. Changing to `accept = lift True`, `accept = lift False`, or providing an input array where each element is false fixes the issue.

Curious if anyone else can repro this; I'll provide more details once I get the chance to recompile accelerate with `-fdebug`.

**Comment by TravisWhitaker** [comment]
It turns out that this function has the same issue:

```Haskell
indicesOfTruth :: Acc (Array DIM2 Bool)
             -> Acc (Vector (Int, Int))
indicesOfTruth dets =
    let dimToTup :: Exp DIM2 -> Exp (Int, Int)
        dimToTup d = let x :: Exp Int
                         y :: Exp Int
                         (Z :. y :. x) = unlift d
                     in lift (x, y)
    in map dimToTup ((map fst . afst . filter snd . indexed) dets)
```

**Comment by TravisWhitaker** [comment]
And upon even more testing, it seems that any `filter` on a large enough array will fail with an invalid access... I'll try to characterize the failure cases a bit more.

**Comment by TravisWhitaker** [comment]
This _seems_ to be fixed with the latest Nvidia driver, but I'm still a little suspicious.

**Comment by tmcdonell** [comment]
I can't believe I forgot to add a test case for this. Anyway, as you said it seems to be fixed now, so I think we can close this.
