### ISSUE TITLE
Geforce RTX2070 compatibility

### ISSUE THREAD

**Issue by Antystenes** [AccelerateHS/accelerate#433]
I am submitting a...
- [x] bug report
- [ ] feature request
- [x] support request

## Description

Hello. When trying to use accelerate I needed to downgrade llvm from ver. 7.0 to 6.0 only to find out that my gpu (GF RTX2070) is not supported.

## Expected behaviour

Program using accelerate runs without error on RTX2070 GPU

## Current behaviour

Program crashes reporting:

    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    'sm_75' is not a recognized processor for this target (ignoring processor)
    Wikitext2: 
    *** Internal error in package accelerate ***
    *** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
    src/Data/Array/Accelerate/LLVM/PTX/Compile.hs:191:24: (compile): ptxas - -o /home/antystenes/.accelerate/accelerate-llvm-1.2.0.0/accelerate-llvm-ptx-1.2.0.0/llvm-hs-6.0.0/nvptx64-nvidia-cuda/ptx60/rel/morp9c8e2a16a31cc5f0753568ea45488ed58f33a43035dc58c648905bff690271f3.sass -arch=sm_75 (exit 255)
    ptxas /tmp/tmpxft_00004c09_00000000-0_stdin, line 6; error   : PTX .version 6.0 does not support .target sm_75
    ptxas fatal   : Ptx assembly aborted due to errors

## Possible solution 

I may be wrong but maybe adding support for newer llvm would alleviate issues with compatibility? Even if not it still seems like a good idea.

## Steps to reproduce (for bugs)
 1. Compile program which invokes commands launching GPU code when using RTX2070 GPU
 2. Run

## Environment

nvidia-device-query output:

    CUDA device query (Driver API, statically linked)
    CUDA driver version 10.0
    CUDA API version 10.0
    Detected 1 CUDA capable device

    Device 0: GeForce RTX 2070
      CUDA capability:                    7.5
      CUDA cores:                         6912 cores in 36 multiprocessors (192 cores/MP)
      Global memory:                      8 GB
      Constant memory:                    64 kB
      Shared memory per block:            48 kB
      Registers per block:                65536
      Warp size:                          32
      Maximum threads per multiprocessor: 1024
      Maximum threads per block:          1024
      Maximum grid dimensions:            2147483647 x 65535 x 65535
      Maximum block dimensions:           1024 x 1024 x 64
      GPU clock rate:                     1.62 GHz
      Memory clock rate:                  7.001 GHz
      Memory bus width:                   256-bit
      L2 cache size:                      4 MB
      Maximum texture dimensions         
	1D:                               131072
	2D:                               131072 x 65536
	3D:                               16384 x 16384 x 16384
      Texture alignment:                  512 B
      Maximum memory pitch:               2 GB
      Concurrent kernel execution:        Yes
      Concurrent copy and execution:      Yes, with 3 copy engines
      Runtime limit on kernel execution:  Yes
      Integrated GPU sharing host memory: No
      Host page-locked memory mapping:    Yes
      ECC memory support:                 No
      Unified addressing (UVA):           Yes
      PCI bus/location:                   1/0
      Compute mode:                       Default
	Multiple contexts are allowed on the device simultaneously

Accelerate and nvvm libraries versions:
- accelerate-1.2.0.1 
- accelerate-blas-0.2.0.0 
- accelerate-llvm-1.2.0.0 
- accelerate-llvm-ptx-1.2.0.0 
- accelerate-llvm-native-1.2.0.0
- nvvm-0.8.0.3
Stack resolver : lts-12.13

**Comment by tmcdonell** [comment]
I don't have an RTX card right now to try, but I'll update to support LLVM-7 (hopefully this week) and see if that is enough to fix the problem.

**Comment by tmcdonell** [comment]
Sorry I forgot to update this ticket; could you try again with master and let me know if that works? `accelerate-llvm-ptx` should build with llvm-7 now.

**Comment by Antystenes** [comment]
I tried to build with master but it seems that accelerate-io which I also use in my project is incompatible with latest version of accelerate so I wasn't able to check it quickly. I will try in few hours to at least create small demo to check if this backend itself is working on my GPU.

**Comment by TravisWhitaker** [comment]
@Antystenes I ran into the same thing a little while ago and just opened this https://github.com/AccelerateHS/accelerate-io/pull/4. Mind giving it a go?

**Comment by robbert-vdh** [comment]
I've ran into a similar issue, also with an RTX 2070. I tried running the example given on the getting started page, but it seems that the newer generation NVIDIA GPUs have dropped support for some required functionality as mentioned in #414.

```haskell
-- Main.hs
import Data.Array.Accelerate as A
import Data.Array.Accelerate.LLVM.PTX as GPU

dotp :: Acc (Vector Float) -> Acc (Vector Float) -> Acc (Scalar Float)
dotp xs ys = A.fold (+) 0 (A.zipWith (*) xs ys)

main :: IO ()
main =
  let xs = fromList (Z :. 10) [0 ..] :: Vector Float
      ys = fromList (Z :. 10) [1,3 ..] :: Vector Float
   in print $ GPU.run $ dotp (use xs) (use ys)
```

```shell
$ stack run
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.bar.warp.sync
```

I've used the latest versions of accelerate and accelerate-llvm (commits 610cd14c80a11e76654d7eeb9acf779589ec9e19 and AccelerateHS/accelerate-llvm@53901b00b2d6f22dc55df7661bd19bcd7f7341ea), CUDA 10.0.130 and LLVM 7.0.1.

**Comment by TravisWhitaker** [comment]
Yikes, perhaps we need LLVM 8 for sm_75.

**Comment by tmcdonell** [comment]
sm_75 should be available in llvm-8: https://github.com/llvm-mirror/llvm/blob/release_80/lib/Target/NVPTX/NVPTX.td#L57

It might work with llvm-7 though if we just tell llvm to generate code for a slightly earlier architecture in the same generation; so selecting sm_72 might work. I am guessing that after failing to find sm_75 it default to something very old like sm_30, which doesn't support this intrinsic.

**Comment by tmcdonell** [comment]
Yeah, it was defaulting to a really old version. You could try this, I'm skeptical but it might work... https://github.com/AccelerateHS/accelerate-llvm/commit/a7a5c89a35f766dd14f6f2a982ea165bed0fcac1

**Comment by robbert-vdh** [comment]
Sorry for the late response! I've been gone from my desktop for a week so I could only just try it. Running the same example with AccelerateHS/accelerate-llvm@a7a5c89a35f766dd14f6f2a982ea165bed0fcac1, LLVM 7.0.1 and llvm-hs 7.0.1 results in the following (as you'd kind of expect):

```
'sm_75' is not a recognized processor for this target (ignoring processor)
'+ptx63' is not a recognized feature for this target (ignoring feature)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'+ptx63' is not a recognized feature for this target (ignoring feature)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'+ptx63' is not a recognized feature for this target (ignoring feature)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'+ptx63' is not a recognized feature for this target (ignoring feature)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'+ptx63' is not a recognized feature for this target (ignoring feature)
'sm_75' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.bar.warp.sync
```

I would try with LLVM 8.0, but there is no version of `llvm-hs` that supports it yet.

**Comment by tmcdonell** [comment]
> LLVM and CUDA still seem to be working fine in PyTorch and Numba though, so I'm not quite sure what's happening.

It depends on how exactly they are compiling. The latest `nvcc` will know about these devices of course, but we aren't actually using `nvcc`. I'm not sure whether PyTorch and Numba are doing any code generation though, or just using a set of library routines from cuBLAS or similar.

Instead of insisting on the most specific version this device should use (ptx63 and sm_75), also accept the most recent version supported by the current combination of CUDA+LLVM; so in this case something like ptx60 and sm_70 (I would have to check exactly). As long as the major version numbers are correct it should all work fine.

**Comment by robbert-vdh** [comment]
PyTorch is indeed just using precompiled CUDA shaders (I was just trying to see if something else was broken with my setup). I thought Numba used LLVM directly to compile CUDA, but it seems like it does not. It only uses LLVM for optimizing CPU code while using libNVVM for CUDA (is that the same library `nvcc` uses in the background?), so that was just some confusion on my part!

~The 'device kernel image is invalid' error still puzzles me though. Does LLVM or CUDA cache the compiled shaders somewhere? I was messing around in the `Data.Array.Accelerate.LLVM.PTX.Target` module and now everything seems to be broken no matter what I do, and now the compilation functions are not even called anymore.~
I was indeed just facing some caching issues... A quick strace pointed me to `~/.accelerate`, I guess I should have expected that haha. After modifying [withPTXTargetMachine](https://github.com/AccelerateHS/accelerate-llvm/blob/a7a5c89a35f766dd14f6f2a982ea165bed0fcac1/accelerate-llvm-ptx/src/Data/Array/Accelerate/LLVM/PTX/Target.hs#L139-L140) to always use `ptx60` and `sm_70` the example now runs without any issues!

**Comment by TravisWhitaker** [comment]
It might be better to check which version of LLVM we're using, then look up the supported targets. This allows for graceful decay, e.g. if I have LLVM 6 and my target is sm_75, then I should just target sm_70.

**Comment by TravisWhitaker** [comment]
Drat, it seems there's not really an easy way to detect the LLVM version in llvm-hs.

**Comment by robbert-vdh** [comment]
I ended up only having to [cap](https://github.com/robbert-vdh/accelerate-llvm/commit/41696c63b1931830f893949ddc517d089e78c299) the CUDA capability. LLVM doesn't seem to seem to mind being passed a `+ptxXX` feature version it can't do anything with yet.
