### ISSUE TITLE
Synchronization problems with sm_70 and greater.

### ISSUE THREAD

**Issue by TravisWhitaker** [AccelerateHS/accelerate#436]
There seems to be some trouble with spinlocks on Nvidia chips with sm_70 or greater. This little program:

```Haskell
module Main where

import qualified Data.Array.Accelerate as A

import qualified Data.Array.Accelerate.LLVM.PTX as AL

good :: Int -> A.Acc (A.Array A.DIM1 Bool) -> A.Acc (A.Vector Bool, A.Array A.DIM0 Int)
good n arr = A.filter (const (A.constant True)) (A.take (A.constant n) arr)

bad :: Int -> A.Acc (A.Array A.DIM2 Bool) -> A.Acc (A.Vector Bool, A.Array A.DIM1 Int)
bad n arr = A.filter (const (A.constant True)) (A.take (A.constant n) arr)

boolDim1 :: A.Array A.DIM1 Bool
boolDim1 = A.fromList (A.Z A.:. 5) (cycle [True, False])

boolDim2 :: A.Array A.DIM2 Bool
boolDim2 = A.fromList (A.Z A.:. 5 A.:. 5) (cycle [True, False])

main :: IO ()
main = do
    print (AL.runN (good 3) boolDim1)
    print (AL.runN (bad 3) boolDim2)
```

Prints the first result, but hangs forever evaluating the second. The program pins one whole CPU core, and also consumes 100% of the "resources" on the GPU as reported by `nvidia-smi`. I'm using the current `HEAD` of accelerate, accelerate-llvm, and accelerate-llvm-ptx. I have the hardware to confirm that this problem is present with sm_70 (TITAN V, AGX Xavier), sm_75 (GTX 2080 Ti), and _not_ on sm_61. This issue is present with:

- LLVM 6
- LLVM 7
- LLVM 8
- When using `-fno-acc-sharing -fno-exp-sharing -fno-fusion -fno-simplify -fno-fast-math`.
- With accelerate built with `-fbounds-checks -funsafe-checks -finternal-checks`.
- Sprinkling `compute` everywhere has no effect.

The issue seems to occur when a `permute` takes the result of a `backpermute` as an argument. With this little example, doing a `flatten` between `take` and `filter` allows the program to return, but that doesn't fix the problem in general; I have a few other kernels where `flatten` between `backpermute` and `permute` does not solve this problem.

The emitted PTX looks reasonable to me; I suspect that the constraints of the new memory model in sm_70 are being somehow violated, but I have yet to dig into the specifics. Here's the [PTX](https://gist.github.com/TravisWhitaker/f21a87164814e77d84a8a1839b968f0c) for the working part of the program, and here's the [PTX](https://gist.github.com/TravisWhitaker/78d05511d41383eb079508e591d7fe19) for the hanging part.

@tmcdonell If you don't have sm_70 hardware I'd be happy to run any tests you have in mind on your behalf.

**Comment by TravisWhitaker** [comment]
This bit seems suspicious https://docs.nvidia.com/cuda/volta-tuning-guide/index.html#sm-independent-thread-scheduling

> Applications using __syncthreads() or the PTX bar.sync (and their derivatives) in such a way that a barrier will not be reached by some non-exited thread in the thread block must be modified to ensure that all non-exited threads reach the barrier.

**Comment by TravisWhitaker** [comment]
It turns out that the problem is not in the permute spinlock as I suspected. The problematic syncs are the `__syncthread` in `Data.Array.Accelerate.LLVM.PTX.CodeGen.Scan.scanBlockSMem`, and the `__syncwarp`s in `Data.Array.Accelerate.LLVM.PTX.CodeGen.Scan.scanWarpSMem`. If I simply don't do these synchronizations, the program has the correct behavior. Something unique to sm_70 is keeping some threads from ever reaching these syncs.

**Comment by TravisWhitaker** [comment]
sm_70 really does not like the way we're doing scans. In addition to the program above, these tests are exhibiting the same behavior:

- `nofib-llvm-ptx.prelude.scanl'.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanl'.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanl1.*.DIM2.*`
- `nofib-llvm-ptx.prelude.scanl1.*.DIM3.*`
- `nofib-llvm-ptx.prelude.scanr1.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanr1.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanr'.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanr'.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanlSeg.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanlSeg.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanl1Seg.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanl1Seg.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanl'Seg.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanl'Seg.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanrSeg.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanrSeg.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanr1Seg.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanr1Seg.Double.DIM3.*`
- `nofib-llvm-ptx.prelude.scanr'Seg.Double.DIM2.*`
- `nofib-llvm-ptx.prelude.scanr'Seg.Double.DIM3.*`

Going to check if cuda-memcheck's racecheck and synccheck have anything to say about this. The `__syncwarp`s seem to me to be in the right spots...

**Comment by TravisWhitaker** [comment]
Additionally, each of the `*spectral*` tests fails on sm_70 non-deterministically with this behavior (about 1/10 runs). This seems like a separate issue, though.

**Comment by TravisWhitaker** [comment]
There's one more test failing on sm_70:
```
nofib-llvm-ptx
  issues
    137: FAIL (1.04s)
      src/Data/Array/Accelerate/Test/NoFib/Issues/Issue137.hs:31:
      expected: Vector (Z :. 384) [(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000)]
       but got: Vector (Z :. 384) [(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,6),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,5),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(5,6),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,2),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(4,5),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(5,6),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(1,2),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,5),(0,1),(2,3),(0,1),(1,2),(1,2),(0,1),(2,3),(0,1),(3,4),(0,1),(4,5),(0,1),(5,5),(0,1),(4,5),(0,1),(3,4),(0,1),(2,3),(0,1),(1,2),(1,2),(0,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000),(10000,10000)]
```

**Comment by TravisWhitaker** [comment]
Unfortunately, I can't get cuda-memcheck to say anything interesting about this.

My hunch is that there are __syncthread and __syncwarp points that not all threads in a block are able to reach, which is not allowed on sm_70 and later.

**Comment by tmcdonell** [comment]
Thanks for the heads up. It is strange that *removing* the `__syncwarp` from `scanWarpSMem` fixes the issue for you; the documentation implies to me that it should be a necessary addition over previous architectures, which is why I speculatively added it.

I don't have an sm_7x card to debug this properly; I'll poke my boss about buying one..

**Comment by TravisWhitaker** [comment]
Yeah, I agree that some synchronization is necessary there, and I think with a big enough problem there'd be incorrect results without those syncs.

**Comment by TravisWhitaker** [comment]
Ok, I've convinced myself that the root cause is the conditional execution of `scanBlockSMem`. I was able to get cuda-gdb working on a different machine, and when these tests are spinning they're always stuck in the `scan` or `scanP2` kernels.

Most of the scan pass kernels will conditionally do `scanBlockSMem`. In the case of `mkScanAllP1`, `mkScanAllP2`, `mkScanAllP3`, and ` mkScan'AllP1` this is fine. They all work like this:

```Haskell

when (valid i0) $ do
    ...
    scanBlockSMem ...
    ...

return_
```

As with `__syncthreads`, exited threads don't have to participate in `__syncwarp`. However, `mkScan'AllP2` has something like:

```Haskell

imapFromStepTo start bd end $ \offset -> do
    ...
    when (valid i0) $ do
        _syncthreads
        ....
        scanBlockSMem ....
        ........

__syncthreads

-- carry-out stuff

return_
```

I'd expect this to hang on pre-sm_70 cards too, since not all threads will do the `__syncthread` under the `when` block, the `__syncthread` in `scanBlockSMem`, or (on sm_70) the multiple `__syncwarps` in `scanWarpSMem`. There is similar conditional execution of `scanBlockSMem` in `mkScanDim` and mkScan'Dim`. I can get the spinning tests to finish if I either omit these syncs, or `pure (lift True)` all of the execution conditions.

I'm not quite sure the best way to proceed. Without synchronization, `scanWarpSMem` sometimes returns incorrect results. I don't think there's a better way to share the carry in and carry out values, though. Maybe the non-participating threads should run a "dummy" scan block that simply syncs up with the participating threads at the right time? That seems extraordinarily wasteful, since those non-participating threads will just spin.

I'm curious about how we get away with different numbers of `__syncthreads` on pre-sm_70 cards. Perhaps that primitive is somehow weaker or less strict than the documentation suggests?

**Comment by tmcdonell** [comment]
Yes, I believe that pre-sm_70 cards were more lenient with how barriers are handled; I think it was, if any thread of a warp executes a barrier instruction, it is considered as if the entire warp has executed it.

I've started to try and rework scans on this branch (from just eyeballing the code): https://github.com/tmcdonell/accelerate-llvm/tree/wip/436

**Comment by TravisWhitaker** [comment]
Ah nice. I was able to get a working `scanl'` over `DIM1` with the `__ballot_sync` primitive but I think your branch is better.

This fixes the scanl'-related test failures. The remaining test failures are:

- issues.137
- issues.287.{A, B, C}
- issues.362.A

I haven't dug into what's going on with those, though.

**Comment by tmcdonell** [comment]
Ah, sorry, I lost track of this (feel free to ping me more aggressively when I forget to do things). Merged into master now.

I'll leave this ticket open until I can fix the other failures as well.

**Comment by TravisWhitaker** [comment]
Ah nice, thanks!
