### ISSUE TITLE
haddock error in examples/pagerank/Load.hs:18:33

### ISSUE THREAD

**Issue by jwaldmann** [AccelerateHS/accelerate#440]
When I do `cabal install accelerate-examples` (current version from hackage, 1.2.0.1) with   `ghc-options: -haddock` in `.cabal/config`, I get

```
examples/pagerank/Load.hs:18:33: error:
    parse error on input ‘-- ^ From vector’
   |
18 |         -> IO ( V.Vector PageId -- ^ From vector
   |                                 ^^^^^^^^^^^^^^^^
```
Of course, ghc should just ignore, but currently, it outright refuses to compile. (This is https://gitlab.haskell.org/ghc/ghc/issues/8944 )

**Comment by tmcdonell** [comment]
Thanks! For whatever reason this bug doesn't appear when running `stack haddock`, but I fixed the markup so hopefully this won't be a problem in future.
