### ISSUE TITLE
accelerate-llvm-native-1.2.0.1 test suite fails

### ISSUE THREAD

**Issue by idontgetoutmuch** [AccelerateHS/accelerate#445]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

I am running `nix-shell` on

```
with import <nixpkgs> { config.allowUnfree = true; config.allowBroken = true; };

haskellPackages.ghcWithPackages (pkgs: [pkgs.accelerate pkgs.accelerate-llvm pkgs.accelerate-llvm-native pkgs.accelerate-fft])
```

and get

```
Test suite nofib-llvm-native: RUNNING...
nofib-llvm-native
  sharing
    simple:                   OK
    ordering:                 OK
    sort:                     OK (0.03s)
    blowup:                   OK
    bfs:                      OK
    same level
      1:                      OK
      2:                      OK
    empty top
      1:                      OK
      2:                      OK
    pipe:                     OK
    bound variables:          OK
    big tuple:                OK
    iteration
      simple:                 OK
      outside:                OK
      body and condition:     OK
      awhile:                 OK
      iterate:                OK
      nested:                 OK
      unused:                 OK
    nested data-parallelism
      mvm:                    FAIL (expected)
        src/Data/Array/Accelerate/Test/NoFib/Sharing.hs:70:

        *** Internal error in package accelerate ***
        *** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
```

## Expected behaviour

I expect the tests to succeed.

## Current behaviour

The tests fail.

## Possible solution (optional)

At the moment I have no idea.

## Steps to reproduce (for bugs)

 1. Create a shell.nix file as above
 2. `nix-shell`

## Your environment

- Accelerate version: accelerate-llvm-native-1.2.0.1
- Accelerate backend(s) used: None as it won't build
- GHC version: 8.6.5
- Operating system and version:
- Link to your project/example:
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:

```
[sundials@CUDA:~/accelerate]$ uname -a
Linux CUDA 4.19.69 #1-NixOS SMP Thu Aug 29 06:29:00 UTC 2019 x86_64 GNU/Linux
```

```
[sundials@CUDA:~/chebApprox]$ nix-shell -p ghc

[nix-shell:~/chebApprox]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
```

I'm guessing allowing broken isn't a good idea since

```
error: Package ‘accelerate-llvm-native-1.2.0.1’ in /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/development/haskell-modules/hackage-packages.nix:21594 is marked as broken, refusing to evaluate.
```

**Comment by tmcdonell** [comment]
I guess it is failing trying to create the folder `$HOME/.accelerate/`; see if you can create that manually? Then try running a computation manually (anything in ghci should do); it might give you more information (it looks like hedgehog is eating the error message)

**Comment by tmcdonell** [comment]
You could also try running with HEAD: I want to make a release soon so it would be good to know if that works, or otherwise fix it.

**Comment by idontgetoutmuch** [comment]
@tmcdonell I'll see what I can do - my nix skills are still quite primitive

**Comment by trevortknguyen** [comment]
I tried what @idontgetoutmuch suggested with ignoring the test suites while building with Nix and everything worked out, so I think the issue has to do with the test-suite building in Nix.

According to this issue https://github.com/NixOS/nixpkgs/issues/16144 the failure could be caused by calling `cabal build`.

**Comment by tmcdonell** [comment]
@trevortknguyen Ah, thanks! I think this can be closed then.
