### ISSUE TITLE
Consecutive scatters fail when arrays are shared

### ISSUE THREAD

**Issue by ivogabe** [AccelerateHS/accelerate#446]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description

Consider the following code, which creates an array with `[-1, -1]`, writes value 1 to index 0 using a scatter and then writes value 2 to index 1.

```hs
main :: IO ()
main = do
  let a = A.use $ A.fromList (A.Z A.:. 2) [-1, -1 :: Int]
  let b = A.scatter (singleton 0) a (singleton 1)
  let c = A.scatter (singleton 1) b (singleton 2)

  print c
  print $ A.run c

singleton :: A.Elt e => e -> A.Acc (A.Vector e)
singleton e = A.use $ A.fromList (A.Z A.:. 1) [e]
```
GHC will perform common subexpression elimination on this code, which yields something like:
```hs
main :: IO ()
main = do
  let a = A.use $ A.fromList (A.Z A.:. 2) [-1, -1 :: Int]
  let singletonOne = singleton 1
  let b = A.scatter (singleton 0) a singletonOne
  let c = A.scatter singletonOne b (singleton 2)

  print c
  print $ A.run c

singleton :: A.Elt e => e -> A.Acc (A.Vector e)
singleton e = A.use $ A.fromList (A.Z A.:. 1) [e]
```
Note that this optimisation pass can be disabled using `-fno-cse`

## Expected behaviour

The output should be `[1, 2]`

The program should produce the same output, independent on whether common subexpression elimination was performed. In GHC, the pass can be disabled with `-fno-cse`.

## Current behaviour

With `-fno-cse`, the output is `[1,2]` as expected. With CSE, the output is however `[-1, 2]`; the first scatter appears to be ignored.

## Your environment

- Accelerate version:
- Accelerate backend(s) used: accelerate-llvm-native
- GHC version: 8.8
- Operating system and version:
- Link to your project/example:
- If this is a bug with the GPU backend, include the output of `nvidia-device-query`:

**Comment by ivogabe** [comment]
I did some debugging. I didn't find much, but did manage to narrow it down a bit further. I changed the code such that the sharing occurred only in the values-array (the last argument of scatter):
```haskell
main :: IO ()
main = do
  let a = A.use $ A.fromList (A.Z A.:. 2) [-1, -1 :: Int]

  let singletonZero = singleton 0
  let singletonOne  = singleton 1
  let singletonTwo  = singleton 2

  let b = A.scatter singletonZero a singletonTwo
  let c = A.scatter singletonOne  b singletonTwo

  print c
  print $ A.run c
```
This gives the wrong answer, `[-1,2]`, instead of `[2,2]` which the interpreter gives. If you make the singletonTwo not shared, then it will work fine. Then I found three interesting observations:

1. The indices-arrays really have to be defined using `use` (what `singleton` uses).
2. The value array has to be shared, but may be defined using another combinator.
3. If the value array is also used elsewhere, then it will work properly.

So the issue should be called "Consecutive scatters fail when the index arrays are declared with `use` and the value array is shared between the two scatters but not used elsewhere"...

Regarding point 2, the following still fails:
```haskell
main :: IO ()
main = do
  let a = A.use $ A.fromList (A.Z A.:. 2) [-1, -1 :: Int]

  let singletonZero = singleton 0
  let singletonOne  = singleton 1

  let singletonTwo  = fill' 1 2

  let b = A.scatter singletonZero a singletonTwo
  let c = A.scatter singletonOne  b singletonTwo

  print c
  print $ A.run c

singleton :: A.Elt e => e -> A.Acc (A.Vector e)
singleton e = A.use $ A.fromList (A.Z A.:. 1) [e]

fill' :: Int -> Int -> A.Acc (A.Vector Int)
fill' count value = A.fill (A.constant $ A.Z A.:. count) (A.constant value)
```

Regarding point 3, we do get the correct result if you replace `A.run c` with `A.run (A.T2 singletonTwo c)`

**Comment by ivogabe** [comment]
Here are some traces I gathered with `ACCELERATE_LLVM_NATIVE_THREADS=1 stack run -- +ACC -ddump-exec -fforce-recomp --ddump-gc --ddump-sched`. First the trace of the first code block of my previous comment:

```
[   0.023] gc: allocated new host array (size=8, ptr=0x0000004201e7d580)
[   0.023] gc: allocated new host array (size=8, ptr=0x0000004201e7d7c0)
[   0.023] gc: allocated new host array (size=8, ptr=0x0000004201eba0c0)
[   0.023] gc: allocated new host array (size=16, ptr=0x0000004201eba300)
let
  a0 = use (Vector (Z :. 1) [1])
  a1 = use (Vector (Z :. 1) [2])
in
permute
  (\x0 x1 -> x0)
  (let a2 = use (Vector (Z :. 1) [0])
   in
   permute
     (\x0 x1 -> x0)
     (use (Vector (Z :. 2) [-1,-1]))
     (\x0 -> Z :. a2 ! x0)
     (delayed (intersect (shape a2) (shape a1)) (\x0 -> let x1 = a1 ! x0 in x1)))
  (\x0 -> Z :. a0 ! x0)
  (delayed (intersect (shape a0) (shape a1)) (\x0 -> let x1 = a1 ! x0 in x1))
[   0.036] gc: initialise native target with 1 worker threads
[   0.037] sched: fork ThreadId 36 on capability 0
[   0.037] sched: ThreadId 36 sleeping
[   0.058] sched: ThreadId 36 sleeping
[   0.058] gc: allocated new host array (size=16, ptr=0x0000004201ee6e00)
[   0.059] exec: permute/clone 505.031 µs (wall), 9.576 ms (cpu)
[   0.059] exec: permuteS 106.042 µs (wall), 115.927 µs (cpu), 1.09 x speedup
[   0.059] exec: permute/inplace
[   0.059] exec: permuteS 11.632 µs (wall), 10.530 µs (cpu), 0.91 x speedup
[   0.059] sched: ThreadId 36 sleeping
Vector (Z :. 2) [-1,2]
```

And the trace, where I duplicated and inlined the code of singletonTwo and disabled common subexpression elimination:

```
[   0.026] gc: allocated new host array (size=8, ptr=0x0000004201e7b580)
[   0.027] gc: allocated new host array (size=8, ptr=0x0000004201e7b7c0)
[   0.027] gc: allocated new host array (size=8, ptr=0x0000004201db40c0)
[   0.027] gc: allocated new host array (size=8, ptr=0x0000004201db4300)
[   0.027] gc: allocated new host array (size=16, ptr=0x0000004201db4540)
let
  a0 = use (Vector (Z :. 1) [1])
  a1 = use (Vector (Z :. 1) [2])
in
permute
  (\x0 x1 -> x0)
  (let
     a2 = use (Vector (Z :. 1) [0])
     a3 = use (Vector (Z :. 1) [2])
   in
   permute
     (\x0 x1 -> x0)
     (use (Vector (Z :. 2) [-1,-1]))
     (\x0 -> Z :. a2 ! x0)
     (delayed (intersect (shape a2) (shape a3)) (\x0 -> let x1 = a3 ! x0 in x1)))
  (\x0 -> Z :. a0 ! x0)
  (delayed (intersect (shape a0) (shape a1)) (\x0 -> let x1 = a1 ! x0 in x1))
[   0.039] gc: initialise native target with 1 worker threads
[   0.039] sched: fork ThreadId 36 on capability 0
[   0.039] sched: ThreadId 36 sleeping
[   0.062] sched: ThreadId 36 sleeping
[   0.062] gc: allocated new host array (size=16, ptr=0x0000004201de8540)
[   0.062] exec: permute/clone 494.582 µs (wall), 8.761 ms (cpu)
[   0.063] exec: permuteS 127.563 µs (wall), 135.966 µs (cpu), 1.07 x speedup
[   0.063] exec: permute/inplace
[   0.063] exec: permuteS 16.542 µs (wall), 14.938 µs (cpu), 0.90 x speedup
[   0.063] sched: ThreadId 36 sleeping
Vector (Z :. 2) [2,2]
```

Some other minor observations:
- Forcing the permutes to either be in place, or copying, didn't make a difference.
- The problem also occurs on the PTX backend.

**Comment by tmcdonell** [comment]
This seems to be working in AccelerateHS/accelerate-llvm@d089be0a1825d0547f51ab2dc2bd4533d09f37f4 (I'm not sure exactly what fixed it or when)
