### ISSUE TITLE
ZipWith3 and higher don't fuse like producers, because they are defined as generators in Data.Array.Accelerate.Prelude

### ISSUE THREAD

**Issue by jippiedoe** [AccelerateHS/accelerate#452]
I am submitting a...
- [ ] bug report
- [X] feature request
- [ ] support request => you might also like to ask your question on the [mailing list](mailto:accelerate-haskell@googlegroups.com) or [gitter chat](https://gitter.im/AccelerateHS/Lobby).

## Description
Because zipWith3 and up are defined directly as generators, they don't fuse (see example below). Alternate definitions, requiring no changes outside of prelude, do fuse and get optimised away. I'm not sure whether my definition is 'optimal': it generates good code, but maybe there is a way which is more efficient to compile.

## Expected behaviour
Consider this minimal example:
`fusionVsSharing :: Acc (Array DIM1 Int) -> Acc (Array DIM1 Int)`
`fusionVsSharing xs = zipWith3 g as as as`
`  where as = map f xs`
The optimal way to fuse this, without duplicating the map cost, is:
`map (\x -> let y = f x in g y y y)`
In the normal zipWith case, this happens.

## Current behaviour
Because zipWith3 is defined directly as a generator, the compiler can't preserve sharing while fusing the map into the generator.

## Possible solution
Simply replacing the definition for zipWith3 with this one in Prelude produces the earlier mentioned optimal code, by reusing the existing fusion for the normal zipWith:
`zipWith3 f xs ys zs =`
`  zipWith (\(unlift -> (x, y)) z -> f x y z) (zip xs ys) zs`

The same optimisation can be done for the higher level zipWith's ofcourse.
Note that zipX is also defined in terms of zipWithX.

**Comment by tmcdonell** [comment]
Thanks!
