### ISSUE TITLE
stack build error

### ISSUE THREAD

**Issue by 221V** [AccelerateHS/accelerate#454]
Hi!

i trying install accelerate
with stack v 2.1.3
by instructions https://www.acceleratehs.org/get-started/linux
at ubuntu 16.04
and get error, i can not install accelerate :(

how i can install accelerate?
llvm installed, cuda tool installed

I am submitting a...
- [ + ] bug report
- [ + ] support request

## Description
```
happy              > Configuring happy-1.19.5...
happy              > build
happy              > Building happy-1.19.5...
happy              > Preprocessing executable 'happy' for happy-1.19.5...
happy              > setup: The program 'happy' is required but it could not be found
                   
Error: 
--  While building package happy-1.19.5 using:
      /tmp/stack30595/happy-1.19.5/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build --ghc-options ""
    Process exited with code: ExitFailure 1


--  While building package alex-3.2.1 using:
      /tmp/stack30595/alex-3.2.1/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build --ghc-options ""
    Process exited with code: ExitFailure 1
```

## Your environment

- Accelerate version: 1.0.0.0
- Accelerate backend(s) used: cpu
- GHC version: 8.6.3
- Operating system and version: ubuntu 16.04 lts xenial
- Link to your project/example:
  literally this demo
  https://www.acceleratehs.org/get-started/linux

i do not know what to do next

**Comment by tmcdonell** [comment]
Hello! Ah, I am very sorry, I have forgotten to update the webpage instructions for a long time!

Try with your `stack.yaml` something like this:

```yaml
resolver: lts-14.20
extra-deps:
  - accelerate-1.2.0.1
  - accelerate-llvm-1.2.0.1
  - accelerate-llvm-native-1.2.0.1
  - accelerate-llvm-ptx-1.2.0.1
```

You can also put the dependency `accelerate` and one (or both) of the backends into the `.cabal` or `package.yaml` files (whichever you are using) and then `stack build` should direct you to add the necessary packages to the extra-deps field. For the above I believe you'll need llvm-8 installed.

I hope that helps, let me know how it goes.

**Comment by 221V** [comment]
thank you!

now I have gone further than before))
but ... got err again

```
llvm-hs               > [113 of 114] Compiling LLVM.Internal.PassManager
llvm-hs               > [114 of 114] Compiling LLVM.PassManager
llvm-hs               > copy/register
llvm-hs               > Installing library in /home/e/.stack/snapshots/x86_64-linux/2faccd7af261137b3d6490064f186e5139ebfa6771f2ef80016ee640dac65b6a/8.6.5/lib/x86_64-linux-ghc-8.6.5/llvm-hs-8.0.0-D4xWMELznf89Qv1mnKyycc
llvm-hs               > Registering library for llvm-hs-8.0.0..
                       
--  While building package cuda-0.10.1.0 using:
      /tmp/stack22743/cuda-0.10.1.0/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 79/94
```

what deps cuda-0.10.1.0 needs ?
i have NVIDIA GeForce GT 730 (2Gb 128bit)
with 96 cuda cores; and i install
CUDA SDK 8
(but i compile example with cpu backend, not with gpu)

maybe i something lost?
or what.. i do not know

thank you

**Comment by sakehl** [comment]
So the GPU backend (accelerate-llvm-ptx) needs at least version 0.9 of the cuda package. Which corresponds to CUDA 9. So your CUDA version is to low. 

 I'd suggest installing CUDA 10.1 (which the package cuda-0.10.1.0 needs).

**Comment by tmcdonell** [comment]
@221V Yes, @sakehl is correct, upgrading the CUDA installation might help

Otherwise, since you are using the CPU backend, then you can delete the lines for `accelerate-llvm-ptx` in the `stack.yaml` and `.cabal` files to avoid the problem.

Hope that helps!

**Comment by tmcdonell** [comment]
I guess this has been solved, please get in touch if you have further questions or problems (:
