### ISSUE TITLE
n-body example: computation of acceleration

### ISSUE THREAD

**Issue by lennonhill** [AccelerateHS/accelerate#458]
I am submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request

## Description
accel, as defined in https://github.com/AccelerateHS/accelerate-examples/blob/85b132abd8ed006a448d5a0bf7c68c00457bc367/examples/n-body/Common/Body.hs#L67 , computes the acceleration to be applied to a body. advanceBodies (https://github.com/AccelerateHS/accelerate-examples/blob/85b132abd8ed006a448d5a0bf7c68c00457bc367/examples/n-body/Common/World.hs#L26) multiplies this acceleration with each body's mass, yielding a force, which is mistaken for the respective body's acceleration.

## Possible solution
The multiplication in https://github.com/AccelerateHS/accelerate-examples/blob/85b132abd8ed006a448d5a0bf7c68c00457bc367/examples/n-body/Common/World.hs#L39 is not necessary. Instead, the original acceleration should be used.

**Comment by tmcdonell** [comment]
Well spotted, thanks!
