### ISSUE TITLE
Support CUDA 11 

### ISSUE THREAD

**Issue by declension** [AccelerateHS/accelerate#481]
**Is your feature request related to a problem? Please describe.**
On Ubuntu 20.10 (also various other new distro releases), cuda-11 is now the standard apt-controlled version, not least perhaps as Nvidia state:
>  We advise customers updating to Linux Kernel 5.9+ to use the latest NVIDIA Linux GPU driver R455 that will be available for download from NVIDIA website and repositories, starting today.

It's also the [default version to download for 20.04](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004) now.

See brief discussion in [chat room](https://gitter.im/AccelerateHS/Lobby).

**Describe the solution you'd like**
Support for CUDA 11.x within `accelerate` ecosystem would be wonderful :+1: 

**Describe alternatives you've considered**
Using CPU-only builds fails for different reasons around `libffi.so.7` (best as a separate issue)

**Comment by tmcdonell** [comment]
I forgot to ping this ticket but this should all work now 👍
