### ISSUE TITLE
Could not enable debugging options

### ISSUE THREAD

**Issue by zleonhe** [AccelerateHS/accelerate#506]
**Description**
Could not enable debugging option with stack build.

**Steps to reproduce**
I have the following session in `stack.yaml`:
```
flags:
    accelerate:
        debug: true
```
After the build I run my program with `acc-exe +ACC -dverbose` and keep getting
```
Data.Array.Accelerate: Debugging options are disabled.
Reinstall package 'accelerate' with '-fdebug' to enable them.
```
I also tried `stack build --flag accelerate:debug` but ended up with the same error.

**Your environment**

 - Accelerate: 1.3.0.0
 - Accelerate backend(s): LLVM-PTX-1.3.0.0
 - GHC: 8.10.4
 - OS: CentOS 7

**Comment by tomsmeding** [comment]
As far as I know, this is a bug in stack. (I'm not sure whether it has actually been reported yet.)

A workaround is to clone the accelerate repository manually in a subdirectory, checkout the `v1.3.0.0` tag, and add `./accelerate` to the `packages` block in your stack.yaml instead of the `extra-deps` block (where it is now, presumably).

**Comment by tomsmeding** [comment]
How do you currently depend on accelerate in your stack.yaml file? In my previous comment I assumed using `extra-deps`, but I now realise that this may not be the case.

**Comment by zleonhe** [comment]
I indeed included `accelerate` in `extra-deps`. The behaviour/bug from stack is so crazy that I could never expect!

Thanks a lot for the workaround, but gcc10 now complains about TBB version when compiling the `tracy` module. I think I still have to struggle for a while :(

**Comment by tomsmeding** [comment]
@zleonhe Be sure to do `git checkout v1.3.0.0` in the accelerate subdirectory!

**Comment by zleonhe** [comment]
Oh right, thanks for the kind reminder :) I successfully enable the debugging options now.
Thanks again!
