### ISSUE TITLE
[BUG] undefined symbol: _ZTIN4llvm10CallbackVHE

### ISSUE THREAD

**Issue by wujilingfeng** [AccelerateHS/accelerate#515]
**Description**
I have compiled llvm, there gone wrong when I was installing accelerate-llvm-native.
![Screenshot from 2022-03-30 15-11-16](https://user-images.githubusercontent.com/35684738/160803444-dcbad1b5-739d-4901-8bf4-e0f409cf32cd.png)

I don't understand what's mean that _ZTIN4llvm10CallbackVHE.

My os is ubuntu,and I ran the command `cabal install accelerate-llvm-native`.
The command that I used to compile llvm is ` cmake ../llvm -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release   -DLLVM_LINK_LLVM_DYLIB=ON`

**Comment by tmcdonell** [comment]
I don't know what symbol that is either...

Does using llvm from apt work? https://apt.llvm.org For ubuntu I've always just used those packages. It should work if you build from source of course (unless perhaps you have a strange config?) but anyway it's something else to try.

**Comment by wujilingfeng** [comment]
> cmake



> I don't know what symbol that is either...
> 
> Does using llvm from apt work? https://apt.llvm.org For ubuntu I've always just used those packages. It should work if you build from source of course (unless perhaps you have a strange config?) but anyway it's something else to try.

I want to get .so files, Can I get them by the apt?

**Comment by nbos** [comment]
Try compiling llvm with `-DLLVM_ENABLE_RTTI=ON`

**Comment by wujilingfeng** [comment]
> Try compiling llvm with `-DLLVM_ENABLE_RTTI=ON`

Tanks! I fixed it. Because I reinstall ubuntu  -_-!
