### ISSUE TITLE
[BUG] typo in Semigroup instance of Exp (Maybe a)

### ISSUE THREAD

**Issue by rajeshpoddar** [AccelerateHS/accelerate#517]
https://github.com/AccelerateHS/accelerate/blob/5971c5d8e4dbba28d2017e7ce422cf46a20197cb/src/Data/Array/Accelerate/Data/Maybe.hs#L138

Should that be `cond (isNothing mb) ma` instead?

**Comment by tmcdonell** [comment]
yes you are correct, well spotted!
