### ISSUE TITLE
[BUG] Cabal.extra-source-files lists many non-existing cbits files

### ISSUE THREAD

**Issue by amigalemming** [AccelerateHS/accelerate#543]
**Description**

The directory `cbits/tracy` is empty, but `Cabal.extra-source-files` lists many subdirectories and cpp and hpp files.

**Steps to reproduce**

~~~~
accelerate-git$ cabal sdist
cabal: sdist of accelerate-1.3.0.0: filepath wildcard
'cbits/tracy/public/*.cpp' refers to the directory 'cbits/tracy/public', which
does not exist or is not a directory.
filepath wildcard 'cbits/tracy/public/*.cpp' does not match any files.
~~~~

**Your environment**

 - Accelerate: GIT-HEAD, currently 5ceb2da5d9ddc4ea0a5705d46bf4de9321ba17da

**Comment by tomsmeding** [comment]
If I recall correctly, the situation here is that those files _do_ exist if the tracy submodule is cloned, which happens if the `-fdebug` flag is set. And in this case, the C files are actually needed. However, cabal does not allow putting a flag conditional around extra-source-files (perhaps for good reason), so we're in a catch.

What do you need an sdist for?

**Comment by amigalemming** [comment]
Aha, it seems I must pull a submodule.

Ok, the bigger problem is, I want to fetch accelerate/GIT-HEAD in a `cabal.project.local`:

~~~~
source-repository-package
   type: git
   location: https://github.com/AccelerateHS/accelerate/
   tag: 5ceb2da5d9ddc4ea0a5705d46bf4de9321ba17da
~~~~

and this fails because of the missing submodule. I must Cabal teach somehow to also pull that submodule.

**Comment by tomsmeding** [comment]
I see! If this is all you need, then the answer is:
```
source-repository-package
    ...
    post-checkout-command: bash -c "git submodule update --init --recursive"
```
for cabal >= 3.8. For cabal < 3.8, you'll need to put `! ` before `git`, because it had a bug where it thought a unix status code of 1 meant "true".

**Comment by amigalemming** [comment]
Perfect, this solves my problem!

**Comment by tomsmeding** [comment]
Thanks for asking, now there is something that people can find when searching for the error message :)
