### ISSUE TITLE
broken URLs for accelerate on hackage

### ISSUE THREAD

**Issue by jwaldmann** [AccelerateHS/accelerate#62]
sure that's not an accelerate error, but it is annoying. e.g., 

http://hackage.haskell.org/packages/archive/accelerate/0.12.1.0/doc/html/Data-Array-Accelerate-Analysis-Shape.html

It seems haddock is asuming that Data-Array-Accelerate-Analysis should exists.

I'll try to submit this as a haddock issue as well.

**Comment by tmcdonell** [comment]
Hidden modules no longer result in broken links.
